namespace Client
{
    using Properties;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    partial class CarImage
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
 private void InitializeComponent()
        {
            this.gbCarImage = new GroupBox();
            this.picCarNormal = new PictureBox();
            this.picCarSleep = new PictureBox();
            this.picCarStopAlarm = new PictureBox();
            this.picCarFill = new PictureBox();
            this.picCarAlarm = new PictureBox();
            this.picCarStopFill = new PictureBox();
            this.picCarStopNormal = new PictureBox();
            this.picCarStopSleep = new PictureBox();
            this.picCarOnlineSleep = new PictureBox();
            this.picCarOnlineFill = new PictureBox();
            this.picCarOnlineAlarm = new PictureBox();
            this.picCarOnlineNormal = new PictureBox();
            this.lblSleep = new Label();
            this.lblFill = new Label();
            this.lblAlarm = new Label();
            this.lblNormal = new Label();
            this.lblCarDes = new Label();
            this.lblCarStop = new Label();
            this.lblCarOnline = new Label();
            this.gbCarImage.SuspendLayout();
            ((ISupportInitialize) this.picCarNormal).BeginInit();
            ((ISupportInitialize) this.picCarSleep).BeginInit();
            ((ISupportInitialize) this.picCarStopAlarm).BeginInit();
            ((ISupportInitialize) this.picCarFill).BeginInit();
            ((ISupportInitialize) this.picCarAlarm).BeginInit();
            ((ISupportInitialize) this.picCarStopFill).BeginInit();
            ((ISupportInitialize) this.picCarStopNormal).BeginInit();
            ((ISupportInitialize) this.picCarStopSleep).BeginInit();
            ((ISupportInitialize) this.picCarOnlineSleep).BeginInit();
            ((ISupportInitialize) this.picCarOnlineFill).BeginInit();
            ((ISupportInitialize) this.picCarOnlineAlarm).BeginInit();
            ((ISupportInitialize) this.picCarOnlineNormal).BeginInit();
            base.SuspendLayout();
            this.gbCarImage.BackgroundImageLayout = ImageLayout.Center;
            this.gbCarImage.Controls.Add(this.picCarNormal);
            this.gbCarImage.Controls.Add(this.picCarSleep);
            this.gbCarImage.Controls.Add(this.picCarStopAlarm);
            this.gbCarImage.Controls.Add(this.picCarFill);
            this.gbCarImage.Controls.Add(this.picCarAlarm);
            this.gbCarImage.Controls.Add(this.picCarStopFill);
            this.gbCarImage.Controls.Add(this.picCarStopNormal);
            this.gbCarImage.Controls.Add(this.picCarStopSleep);
            this.gbCarImage.Controls.Add(this.picCarOnlineSleep);
            this.gbCarImage.Controls.Add(this.picCarOnlineFill);
            this.gbCarImage.Controls.Add(this.picCarOnlineAlarm);
            this.gbCarImage.Controls.Add(this.picCarOnlineNormal);
            this.gbCarImage.Controls.Add(this.lblSleep);
            this.gbCarImage.Controls.Add(this.lblFill);
            this.gbCarImage.Controls.Add(this.lblAlarm);
            this.gbCarImage.Controls.Add(this.lblNormal);
            this.gbCarImage.Controls.Add(this.lblCarDes);
            this.gbCarImage.Controls.Add(this.lblCarStop);
            this.gbCarImage.Controls.Add(this.lblCarOnline);
            this.gbCarImage.Dock = DockStyle.Fill;
            this.gbCarImage.Location = new Point(20, 20);
            this.gbCarImage.Name = "gbCarImage";
            this.gbCarImage.Size = new Size(393, 256);
            this.gbCarImage.TabIndex = 1;
            this.gbCarImage.TabStop = false;
            this.picCarNormal.Image = Resources._1010;
            this.picCarNormal.Location = new Point(60, 167);
            this.picCarNormal.Name = "picCarNormal";
            this.picCarNormal.Size = new Size(75, 60);
            this.picCarNormal.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarNormal.TabIndex = 23;
            this.picCarNormal.TabStop = false;
            this.picCarSleep.Image = Resources._1010;
            this.picCarSleep.Location = new Point(282, 167);
            this.picCarSleep.Name = "picCarSleep";
            this.picCarSleep.Size = new Size(75, 60);
            this.picCarSleep.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarSleep.TabIndex = 22;
            this.picCarSleep.TabStop = false;
            this.picCarStopAlarm.Image = Resources._1001;
            this.picCarStopAlarm.Location = new Point(134, 108);
            this.picCarStopAlarm.Name = "picCarStopAlarm";
            this.picCarStopAlarm.Size = new Size(75, 60);
            this.picCarStopAlarm.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarStopAlarm.TabIndex = 19;
            this.picCarStopAlarm.TabStop = false;
            this.picCarFill.Image = Resources._1010;
            this.picCarFill.Location = new Point(208, 167);
            this.picCarFill.Name = "picCarFill";
            this.picCarFill.Size = new Size(75, 60);
            this.picCarFill.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarFill.TabIndex = 17;
            this.picCarFill.TabStop = false;
            this.picCarAlarm.Image = Resources._1010;
            this.picCarAlarm.Location = new Point(134, 167);
            this.picCarAlarm.Name = "picCarAlarm";
            this.picCarAlarm.Size = new Size(75, 60);
            this.picCarAlarm.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarAlarm.TabIndex = 18;
            this.picCarAlarm.TabStop = false;
            this.picCarStopFill.Image = Resources._4001;
            this.picCarStopFill.Location = new Point(208, 108);
            this.picCarStopFill.Name = "picCarStopFill";
            this.picCarStopFill.Size = new Size(75, 60);
            this.picCarStopFill.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarStopFill.TabIndex = 20;
            this.picCarStopFill.TabStop = false;
            this.picCarStopNormal.Image = Resources._2111;
            this.picCarStopNormal.Location = new Point(60, 108);
            this.picCarStopNormal.Name = "picCarStopNormal";
            this.picCarStopNormal.Size = new Size(75, 60);
            this.picCarStopNormal.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarStopNormal.TabIndex = 16;
            this.picCarStopNormal.TabStop = false;
            this.picCarStopSleep.Image = Resources._2011;
            this.picCarStopSleep.Location = new Point(282, 108);
            this.picCarStopSleep.Name = "picCarStopSleep";
            this.picCarStopSleep.Size = new Size(75, 60);
            this.picCarStopSleep.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarStopSleep.TabIndex = 21;
            this.picCarStopSleep.TabStop = false;
            this.picCarOnlineSleep.Image = Resources._3000;
            this.picCarOnlineSleep.Location = new Point(282, 49);
            this.picCarOnlineSleep.Name = "picCarOnlineSleep";
            this.picCarOnlineSleep.Size = new Size(75, 60);
            this.picCarOnlineSleep.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarOnlineSleep.TabIndex = 15;
            this.picCarOnlineSleep.TabStop = false;
            this.picCarOnlineFill.Image = Resources._4000;
            this.picCarOnlineFill.Location = new Point(208, 49);
            this.picCarOnlineFill.Name = "picCarOnlineFill";
            this.picCarOnlineFill.Size = new Size(75, 60);
            this.picCarOnlineFill.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarOnlineFill.TabIndex = 14;
            this.picCarOnlineFill.TabStop = false;
            this.picCarOnlineAlarm.Image = Resources._1000;
            this.picCarOnlineAlarm.InitialImage = null;
            this.picCarOnlineAlarm.Location = new Point(134, 49);
            this.picCarOnlineAlarm.Name = "picCarOnlineAlarm";
            this.picCarOnlineAlarm.Size = new Size(75, 60);
            this.picCarOnlineAlarm.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarOnlineAlarm.TabIndex = 13;
            this.picCarOnlineAlarm.TabStop = false;
            this.picCarOnlineNormal.ErrorImage = null;
            this.picCarOnlineNormal.Image = Resources._2000;
            this.picCarOnlineNormal.InitialImage = null;
            this.picCarOnlineNormal.Location = new Point(60, 49);
            this.picCarOnlineNormal.Name = "picCarOnlineNormal";
            this.picCarOnlineNormal.Size = new Size(75, 60);
            this.picCarOnlineNormal.SizeMode = PictureBoxSizeMode.CenterImage;
            this.picCarOnlineNormal.TabIndex = 12;
            this.picCarOnlineNormal.TabStop = false;
            this.lblSleep.AutoSize = true;
            this.lblSleep.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, 134);
            this.lblSleep.Location = new Point(302, 22);
            this.lblSleep.Name = "lblSleep";
            this.lblSleep.Size = new Size(39, 15);
            this.lblSleep.TabIndex = 7;
            this.lblSleep.Text = "休眠";
            this.lblFill.AutoSize = true;
            this.lblFill.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, 134);
            this.lblFill.Location = new Point(227, 22);
            this.lblFill.Name = "lblFill";
            this.lblFill.Size = new Size(39, 15);
            this.lblFill.TabIndex = 6;
            this.lblFill.Text = "重车";
            this.lblAlarm.AutoSize = true;
            this.lblAlarm.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, 134);
            this.lblAlarm.Location = new Point(152, 22);
            this.lblAlarm.Name = "lblAlarm";
            this.lblAlarm.Size = new Size(39, 15);
            this.lblAlarm.TabIndex = 5;
            this.lblAlarm.Text = "报警";
            this.lblNormal.AutoSize = true;
            this.lblNormal.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, 134);
            this.lblNormal.Location = new Point(77, 22);
            this.lblNormal.Name = "lblNormal";
            this.lblNormal.Size = new Size(39, 15);
            this.lblNormal.TabIndex = 4;
            this.lblNormal.Text = "正常";
            this.lblCarDes.AutoSize = true;
            this.lblCarDes.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, 134);
            this.lblCarDes.Location = new Point(11, 188);
            this.lblCarDes.Name = "lblCarDes";
            this.lblCarDes.Size = new Size(39, 15);
            this.lblCarDes.TabIndex = 3;
            this.lblCarDes.Text = "故障";
            this.lblCarStop.AutoSize = true;
            this.lblCarStop.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, 134);
            this.lblCarStop.Location = new Point(11, 129);
            this.lblCarStop.Name = "lblCarStop";
            this.lblCarStop.Size = new Size(39, 15);
            this.lblCarStop.TabIndex = 2;
            this.lblCarStop.Text = "停车";
            this.lblCarOnline.AutoSize = true;
            this.lblCarOnline.Font = new Font("宋体", 11f, FontStyle.Bold, GraphicsUnit.Point, 134);
            this.lblCarOnline.Location = new Point(11, 70);
            this.lblCarOnline.Name = "lblCarOnline";
            this.lblCarOnline.Size = new Size(39, 15);
            this.lblCarOnline.TabIndex = 1;
            this.lblCarOnline.Text = "行驶";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(433, 296);
            base.Controls.Add(this.gbCarImage);
            base.KeyPreview = true;
            base.Name = "CarImage";
            base.Padding = new Padding(20);
            this.Text = "车辆图标说明";
            base.KeyPress += new KeyPressEventHandler(this.CarImage_KeyPress);
            this.gbCarImage.ResumeLayout(false);
            this.gbCarImage.PerformLayout();
            ((ISupportInitialize) this.picCarNormal).EndInit();
            ((ISupportInitialize) this.picCarSleep).EndInit();
            ((ISupportInitialize) this.picCarStopAlarm).EndInit();
            ((ISupportInitialize) this.picCarFill).EndInit();
            ((ISupportInitialize) this.picCarAlarm).EndInit();
            ((ISupportInitialize) this.picCarStopFill).EndInit();
            ((ISupportInitialize) this.picCarStopNormal).EndInit();
            ((ISupportInitialize) this.picCarStopSleep).EndInit();
            ((ISupportInitialize) this.picCarOnlineSleep).EndInit();
            ((ISupportInitialize) this.picCarOnlineFill).EndInit();
            ((ISupportInitialize) this.picCarOnlineAlarm).EndInit();
            ((ISupportInitialize) this.picCarOnlineNormal).EndInit();
            base.ResumeLayout(false);
        }
    
        private IContainer components;
        private GroupBox gbCarImage;
        private Label lblAlarm;
        private Label lblCarDes;
        private Label lblCarOnline;
        private Label lblCarStop;
        private Label lblFill;
        private Label lblNormal;
        private Label lblSleep;
        private PictureBox picCarAlarm;
        private PictureBox picCarFill;
        private PictureBox picCarNormal;
        private PictureBox picCarOnlineAlarm;
        private PictureBox picCarOnlineFill;
        private PictureBox picCarOnlineNormal;
        private PictureBox picCarOnlineSleep;
        private PictureBox picCarSleep;
        private PictureBox picCarStopAlarm;
        private PictureBox picCarStopFill;
        private PictureBox picCarStopNormal;
        private PictureBox picCarStopSleep;
    }
}