namespace Client
{
    using PublicClass;
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Timers;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class CarTextList
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.components = new Container();
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            DataGridViewCellStyle style3 = new DataGridViewCellStyle();
            DataGridViewCellStyle style4 = new DataGridViewCellStyle();
            DataGridViewCellStyle style5 = new DataGridViewCellStyle();
            DataGridViewCellStyle style6 = new DataGridViewCellStyle();
            DataGridViewCellStyle style7 = new DataGridViewCellStyle();
            DataGridViewCellStyle style8 = new DataGridViewCellStyle();
            DataGridViewCellStyle style9 = new DataGridViewCellStyle();
            this.panel1 = new Panel();
            this.lblAreaType = new Label();
            this.cbAreaType = new ComboBox();
            this.txtAreaName = new TextBox();
            this.lblAreaName = new Label();
            this.txtDriverName = new TextBox();
            this.lblDriverName = new Label();
            this.txtSimNum = new TextBox();
            this.lblSimNum = new Label();
            this.txtCarNum = new TextBox();
            this.lblCarNum = new Label();
            this.cboxDriver = new CheckBox();
            this.cboxAccOn = new CheckBox();
            this.cboxSpeed = new CheckBox();
            this.cboxAddress = new CheckBox();
            this.cboxGpsTime = new CheckBox();
            this.cboxReceTime = new CheckBox();
            this.cboxAllDiff = new CheckBox();
            this.cboxLatitude = new CheckBox();
            this.cboxLongitude = new CheckBox();
            this.lblDGVRowCount = new Label();
            this.btnRefresh = new Button();
            this.btnExportExcel = new Button();
            this.cboxSelectedAll = new CheckBox();
            this.ctxMenuStripDgvHeader = new ContextMenuStrip(this.components);
            this.tsMenuItemLongitude = new ToolStripMenuItem();
            this.tsMenuItemLatitude = new ToolStripMenuItem();
            this.tsMenuItemAllDiff = new ToolStripMenuItem();
            this.tsMenuItemReceTime = new ToolStripMenuItem();
            this.tsMenuItemGpsTime = new ToolStripMenuItem();
            this.tsMenuItemAddress = new ToolStripMenuItem();
            this.tsMenuItemSpeed = new ToolStripMenuItem();
            this.tsMenuItemAccOn = new ToolStripMenuItem();
            this.panel2 = new Panel();
            this.dgvCarTextList = new DataGridView();
            this.colSelect = new DataGridViewCheckBoxColumn();
            this.CarName = new DataGridViewTextBoxColumn();
            this.CarTel = new DataGridViewTextBoxColumn();
            this.CarArea = new DataGridViewTextBoxColumn();
            this.CarLongitude = new DataGridViewTextBoxColumn();
            this.CarLatitude = new DataGridViewTextBoxColumn();
            this.CarAllDiff = new DataGridViewTextBoxColumn();
            this.CarReceTime = new DataGridViewTextBoxColumn();
            this.CarGpsTime = new DataGridViewTextBoxColumn();
            this.CarCurrentAddress = new DataGridViewTextBoxColumn();
            this.CarSpeed = new DataGridViewTextBoxColumn();
            this.CarAcc = new DataGridViewTextBoxColumn();
            this.DriverName = new DataGridViewTextBoxColumn();
            this.CarID = new DataGridViewTextBoxColumn();
            this.panel1.SuspendLayout();
            this.ctxMenuStripDgvHeader.SuspendLayout();
            this.panel2.SuspendLayout();
            ((ISupportInitialize) this.dgvCarTextList).BeginInit();
            base.SuspendLayout();
            this.panel1.Controls.Add(this.lblAreaType);
            this.panel1.Controls.Add(this.cbAreaType);
            this.panel1.Controls.Add(this.txtAreaName);
            this.panel1.Controls.Add(this.lblAreaName);
            this.panel1.Controls.Add(this.txtDriverName);
            this.panel1.Controls.Add(this.lblDriverName);
            this.panel1.Controls.Add(this.txtSimNum);
            this.panel1.Controls.Add(this.lblSimNum);
            this.panel1.Controls.Add(this.txtCarNum);
            this.panel1.Controls.Add(this.lblCarNum);
            this.panel1.Controls.Add(this.cboxDriver);
            this.panel1.Controls.Add(this.cboxAccOn);
            this.panel1.Controls.Add(this.cboxSpeed);
            this.panel1.Controls.Add(this.cboxAddress);
            this.panel1.Controls.Add(this.cboxGpsTime);
            this.panel1.Controls.Add(this.cboxReceTime);
            this.panel1.Controls.Add(this.cboxAllDiff);
            this.panel1.Controls.Add(this.cboxLatitude);
            this.panel1.Controls.Add(this.cboxLongitude);
            this.panel1.Controls.Add(this.lblDGVRowCount);
            this.panel1.Controls.Add(this.btnRefresh);
            this.panel1.Controls.Add(this.btnExportExcel);
            this.panel1.Controls.Add(this.cboxSelectedAll);
            this.panel1.Dock = DockStyle.Top;
            this.panel1.Location = new Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(1035, 56);
            this.panel1.TabIndex = 1;
            this.lblAreaType.AutoSize = true;
            this.lblAreaType.Location = new Point(11, 10);
            this.lblAreaType.Name = "lblAreaType";
            this.lblAreaType.Size = new Size(41, 12);
            this.lblAreaType.TabIndex = 26;
            this.lblAreaType.Text = "类型：";
            this.cbAreaType.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbAreaType.FormattingEnabled = true;
            this.cbAreaType.Items.AddRange(new object[] { "全部", "区域", "企业", "车队" });
            this.cbAreaType.Location = new Point(58, 5);
            this.cbAreaType.Name = "cbAreaType";
            this.cbAreaType.Size = new Size(121, 20);
            this.cbAreaType.TabIndex = 25;
            this.txtAreaName.Location = new Point(232, 5);
            this.txtAreaName.MaxLength = 100;
            this.txtAreaName.Name = "txtAreaName";
            this.txtAreaName.Size = new Size(100, 21);
            this.txtAreaName.TabIndex = 23;
            this.txtAreaName.Tag = "CarArea Like '%{0}%' and AreaType like '%{1}%' ";
            this.lblAreaName.AutoSize = true;
            this.lblAreaName.Location = new Point(185, 10);
            this.lblAreaName.Name = "lblAreaName";
            this.lblAreaName.Size = new Size(41, 12);
            this.lblAreaName.TabIndex = 22;
            this.lblAreaName.Text = "名称：";
            this.txtDriverName.Location = new Point(727, 5);
            this.txtDriverName.MaxLength = 20;
            this.txtDriverName.Name = "txtDriverName";
            this.txtDriverName.Size = new Size(100, 21);
            this.txtDriverName.TabIndex = 20;
            this.txtDriverName.Tag = "DriverName Like '%{0}%'";
            this.lblDriverName.AutoSize = true;
            this.lblDriverName.Location = new Point(668, 10);
            this.lblDriverName.Name = "lblDriverName";
            this.lblDriverName.Size = new Size(53, 12);
            this.lblDriverName.TabIndex = 19;
            this.lblDriverName.Text = "驾驶员：";
            this.txtSimNum.Location = new Point(562, 5);
            this.txtSimNum.MaxLength = 20;
            this.txtSimNum.Name = "txtSimNum";
            this.txtSimNum.Size = new Size(100, 21);
            this.txtSimNum.TabIndex = 18;
            this.txtSimNum.Tag = "CarTel Like '%{0}%'";
            this.lblSimNum.AutoSize = true;
            this.lblSimNum.Location = new Point(503, 10);
            this.lblSimNum.Name = "lblSimNum";
            this.lblSimNum.Size = new Size(53, 12);
            this.lblSimNum.TabIndex = 17;
            this.lblSimNum.Text = "手机号：";
            this.txtCarNum.Location = new Point(397, 5);
            this.txtCarNum.MaxLength = 20;
            this.txtCarNum.Name = "txtCarNum";
            this.txtCarNum.Size = new Size(100, 21);
            this.txtCarNum.TabIndex = 16;
            this.txtCarNum.Tag = "CarName Like '%{0}%'";
            this.lblCarNum.AutoSize = true;
            this.lblCarNum.Location = new Point(338, 10);
            this.lblCarNum.Name = "lblCarNum";
            this.lblCarNum.Size = new Size(53, 12);
            this.lblCarNum.TabIndex = 15;
            this.lblCarNum.Text = "车牌号：";
            this.cboxDriver.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
            this.cboxDriver.AutoSize = true;
            this.cboxDriver.Location = new Point(731, 34);
            this.cboxDriver.Name = "cboxDriver";
            this.cboxDriver.Size = new Size(60, 16);
            this.cboxDriver.TabIndex = 14;
            this.cboxDriver.Text = "驾驶员";
            this.cboxDriver.UseVisualStyleBackColor = true;
            this.cboxDriver.Click += new EventHandler(this.cbox_Click);
            this.cboxAccOn.AccessibleRole =  System.Windows.Forms.AccessibleRole.None;
            this.cboxAccOn.AutoSize = true;
            this.cboxAccOn.Location = new Point(665, 34);
            this.cboxAccOn.Name = "cboxAccOn";
            this.cboxAccOn.Size = new Size(66, 16);
            this.cboxAccOn.TabIndex = 13;
            this.cboxAccOn.Text = "ACC状态";
            this.cboxAccOn.UseVisualStyleBackColor = true;
            this.cboxAccOn.Click += new EventHandler(this.cbox_Click);
            this.cboxSpeed.AutoSize = true;
            this.cboxSpeed.Location = new Point(617, 34);
            this.cboxSpeed.Name = "cboxSpeed";
            this.cboxSpeed.Size = new Size(48, 16);
            this.cboxSpeed.TabIndex = 12;
            this.cboxSpeed.Text = "时速";
            this.cboxSpeed.UseVisualStyleBackColor = true;
            this.cboxSpeed.Click += new EventHandler(this.cbox_Click);
            this.cboxAddress.AutoSize = true;
            this.cboxAddress.Location = new Point(545, 34);
            this.cboxAddress.Name = "cboxAddress";
            this.cboxAddress.Size = new Size(72, 16);
            this.cboxAddress.TabIndex = 11;
            this.cboxAddress.Text = "位置信息";
            this.cboxAddress.UseVisualStyleBackColor = true;
            this.cboxAddress.Click += new EventHandler(this.cbox_Click);
            this.cboxGpsTime.AutoSize = true;
            this.cboxGpsTime.Location = new Point(473, 34);
            this.cboxGpsTime.Name = "cboxGpsTime";
            this.cboxGpsTime.Size = new Size(72, 16);
            this.cboxGpsTime.TabIndex = 10;
            this.cboxGpsTime.Text = "定位时间";
            this.cboxGpsTime.UseVisualStyleBackColor = true;
            this.cboxGpsTime.Click += new EventHandler(this.cbox_Click);
            this.cboxReceTime.AutoSize = true;
            this.cboxReceTime.Location = new Point(401, 34);
            this.cboxReceTime.Name = "cboxReceTime";
            this.cboxReceTime.Size = new Size(72, 16);
            this.cboxReceTime.TabIndex = 9;
            this.cboxReceTime.Text = "上报时间";
            this.cboxReceTime.UseVisualStyleBackColor = true;
            this.cboxReceTime.Click += new EventHandler(this.cbox_Click);
            this.cboxAllDiff.AutoSize = true;
            this.cboxAllDiff.Location = new Point(329, 34);
            this.cboxAllDiff.Name = "cboxAllDiff";
            this.cboxAllDiff.Size = new Size(72, 16);
            this.cboxAllDiff.TabIndex = 8;
            this.cboxAllDiff.Text = "累计里程";
            this.cboxAllDiff.UseVisualStyleBackColor = true;
            this.cboxAllDiff.Click += new EventHandler(this.cbox_Click);
            this.cboxLatitude.AutoSize = true;
            this.cboxLatitude.Location = new Point(281, 34);
            this.cboxLatitude.Name = "cboxLatitude";
            this.cboxLatitude.Size = new Size(48, 16);
            this.cboxLatitude.TabIndex = 7;
            this.cboxLatitude.Text = "纬度";
            this.cboxLatitude.UseVisualStyleBackColor = true;
            this.cboxLatitude.Click += new EventHandler(this.cbox_Click);
            this.cboxLongitude.AutoSize = true;
            this.cboxLongitude.Location = new Point(233, 34);
            this.cboxLongitude.Name = "cboxLongitude";
            this.cboxLongitude.Size = new Size(48, 16);
            this.cboxLongitude.TabIndex = 6;
            this.cboxLongitude.Text = "经度";
            this.cboxLongitude.UseVisualStyleBackColor = true;
            this.cboxLongitude.Click += new EventHandler(this.cbox_Click);
            this.lblDGVRowCount.AutoSize = true;
            this.lblDGVRowCount.Location = new Point(76, 36);
            this.lblDGVRowCount.Name = "lblDGVRowCount";
            this.lblDGVRowCount.Size = new Size(95, 12);
            this.lblDGVRowCount.TabIndex = 3;
            this.lblDGVRowCount.Text = "总共 {0} 条记录";
            this.btnRefresh.Location = new Point(834, 4);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Size = new Size(75, 23);
            this.btnRefresh.TabIndex = 2;
            this.btnRefresh.Text = "刷新(&R)";
            this.btnRefresh.UseVisualStyleBackColor = true;
            this.btnRefresh.Click += new EventHandler(this.btnRefresh_Click);
            this.btnExportExcel.Location = new Point(915, 4);
            this.btnExportExcel.Name = "btnExportExcel";
            this.btnExportExcel.Size = new Size(75, 23);
            this.btnExportExcel.TabIndex = 1;
            this.btnExportExcel.Text = "导出Excel";
            this.btnExportExcel.UseVisualStyleBackColor = true;
            this.btnExportExcel.Click += new EventHandler(this.btnExportExcel_Click);
            this.cboxSelectedAll.AutoSize = true;
            this.cboxSelectedAll.Location = new Point(13, 34);
            this.cboxSelectedAll.Name = "cboxSelectedAll";
            this.cboxSelectedAll.Size = new Size(48, 16);
            this.cboxSelectedAll.TabIndex = 0;
            this.cboxSelectedAll.Text = "全选";
            this.cboxSelectedAll.UseVisualStyleBackColor = true;
            this.cboxSelectedAll.CheckedChanged += new EventHandler(this.cboxSelectedAll_CheckedChanged);
            this.ctxMenuStripDgvHeader.Items.AddRange(new ToolStripItem[] { this.tsMenuItemLongitude, this.tsMenuItemLatitude, this.tsMenuItemAllDiff, this.tsMenuItemReceTime, this.tsMenuItemGpsTime, this.tsMenuItemAddress, this.tsMenuItemSpeed, this.tsMenuItemAccOn });
            this.ctxMenuStripDgvHeader.Name = "ctxMenuStripDgvHeader";
            this.ctxMenuStripDgvHeader.Size = new Size(119, 180);
            this.tsMenuItemLongitude.Checked = true;
            this.tsMenuItemLongitude.CheckState = CheckState.Checked;
            this.tsMenuItemLongitude.Name = "tsMenuItemLongitude";
            this.tsMenuItemLongitude.Size = new Size(118, 22);
            this.tsMenuItemLongitude.Text = "经度";
            this.tsMenuItemLatitude.Checked = true;
            this.tsMenuItemLatitude.CheckState = CheckState.Checked;
            this.tsMenuItemLatitude.Name = "tsMenuItemLatitude";
            this.tsMenuItemLatitude.Size = new Size(118, 22);
            this.tsMenuItemLatitude.Text = "纬度";
            this.tsMenuItemAllDiff.Checked = true;
            this.tsMenuItemAllDiff.CheckState = CheckState.Checked;
            this.tsMenuItemAllDiff.Name = "tsMenuItemAllDiff";
            this.tsMenuItemAllDiff.Size = new Size(118, 22);
            this.tsMenuItemAllDiff.Text = "累计里程";
            this.tsMenuItemReceTime.Checked = true;
            this.tsMenuItemReceTime.CheckState = CheckState.Checked;
            this.tsMenuItemReceTime.Name = "tsMenuItemReceTime";
            this.tsMenuItemReceTime.Size = new Size(118, 22);
            this.tsMenuItemReceTime.Text = "上报时间";
            this.tsMenuItemGpsTime.Checked = true;
            this.tsMenuItemGpsTime.CheckState = CheckState.Checked;
            this.tsMenuItemGpsTime.Name = "tsMenuItemGpsTime";
            this.tsMenuItemGpsTime.Size = new Size(118, 22);
            this.tsMenuItemGpsTime.Text = "定位时间";
            this.tsMenuItemAddress.Checked = true;
            this.tsMenuItemAddress.CheckState = CheckState.Checked;
            this.tsMenuItemAddress.Name = "tsMenuItemAddress";
            this.tsMenuItemAddress.Size = new Size(118, 22);
            this.tsMenuItemAddress.Text = "位置信息";
            this.tsMenuItemSpeed.Checked = true;
            this.tsMenuItemSpeed.CheckState = CheckState.Checked;
            this.tsMenuItemSpeed.Name = "tsMenuItemSpeed";
            this.tsMenuItemSpeed.Size = new Size(118, 22);
            this.tsMenuItemSpeed.Text = "时速";
            this.tsMenuItemAccOn.Checked = true;
            this.tsMenuItemAccOn.CheckState = CheckState.Checked;
            this.tsMenuItemAccOn.Name = "tsMenuItemAccOn";
            this.tsMenuItemAccOn.Size = new Size(118, 22);
            this.tsMenuItemAccOn.Text = "ACC状态";
            this.panel2.Controls.Add(this.dgvCarTextList);
            this.panel2.Dock = DockStyle.Fill;
            this.panel2.Location = new Point(0, 56);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(1035, 524);
            this.panel2.TabIndex = 2;
            this.dgvCarTextList.AllowUserToAddRows = false;
            this.dgvCarTextList.AllowUserToDeleteRows = false;
            this.dgvCarTextList.BackgroundColor = Color.White;
            style.Alignment = DataGridViewContentAlignment.MiddleCenter;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.True;
            this.dgvCarTextList.ColumnHeadersDefaultCellStyle = style;
            this.dgvCarTextList.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvCarTextList.Columns.AddRange(new DataGridViewColumn[] { this.colSelect, this.CarName, this.CarTel, this.CarArea, this.CarLongitude, this.CarLatitude, this.CarAllDiff, this.CarReceTime, this.CarGpsTime, this.CarCurrentAddress, this.CarSpeed, this.CarAcc, this.DriverName, this.CarID });
            this.dgvCarTextList.Dock = DockStyle.Fill;
            this.dgvCarTextList.Location = new Point(0, 0);
            this.dgvCarTextList.Name = "dgvCarTextList";
            this.dgvCarTextList.RowHeadersVisible = false;
            this.dgvCarTextList.RowTemplate.Height = 23;
            this.dgvCarTextList.RowTemplate.Resizable = DataGridViewTriState.False;
            this.dgvCarTextList.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvCarTextList.Size = new Size(1035, 524);
            this.dgvCarTextList.TabIndex = 1;
            this.dgvCarTextList.CellMouseDoubleClick += new DataGridViewCellMouseEventHandler(this.dgvCarTextList_CellMouseDoubleClick);
            this.dgvCarTextList.DataError += new DataGridViewDataErrorEventHandler(this.dgvCarTextList_DataError);
            this.colSelect.FalseValue = "false";
            this.colSelect.Frozen = true;
            this.colSelect.HeaderText = "选择";
            this.colSelect.Name = "colSelect";
            this.colSelect.TrueValue = "true";
            this.colSelect.Width = 40;
            this.CarName.DataPropertyName = "CarName";
            this.CarName.HeaderText = "车牌";
            this.CarName.Name = "CarName";
            this.CarName.ReadOnly = true;
            this.CarName.Width = 80;
            this.CarTel.DataPropertyName = "CarTel";
            this.CarTel.HeaderText = "手机号";
            this.CarTel.Name = "CarTel";
            this.CarTel.ReadOnly = true;
            this.CarArea.DataPropertyName = "CarArea";
            this.CarArea.FillWeight = 150f;
            this.CarArea.HeaderText = "公司及车队";
            this.CarArea.Name = "CarArea";
            this.CarArea.ReadOnly = true;
            this.CarArea.Width = 150;
            this.CarLongitude.DataPropertyName = "Longitude";
            style2.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.CarLongitude.DefaultCellStyle = style2;
            this.CarLongitude.HeaderText = "经度";
            this.CarLongitude.Name = "CarLongitude";
            this.CarLongitude.ReadOnly = true;
            this.CarLatitude.DataPropertyName = "Latitude";
            style3.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.CarLatitude.DefaultCellStyle = style3;
            this.CarLatitude.HeaderText = "纬度";
            this.CarLatitude.Name = "CarLatitude";
            this.CarLatitude.ReadOnly = true;
            this.CarAllDiff.DataPropertyName = "ALLDiff";
            style4.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.CarAllDiff.DefaultCellStyle = style4;
            this.CarAllDiff.HeaderText = "累计里程";
            this.CarAllDiff.Name = "CarAllDiff";
            this.CarAllDiff.ReadOnly = true;
            this.CarReceTime.DataPropertyName = "ReceTime";
            style5.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.CarReceTime.DefaultCellStyle = style5;
            this.CarReceTime.HeaderText = "上报时间";
            this.CarReceTime.Name = "CarReceTime";
            this.CarReceTime.ReadOnly = true;
            this.CarReceTime.Width = 120;
            this.CarGpsTime.DataPropertyName = "GpsTime";
            style6.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.CarGpsTime.DefaultCellStyle = style6;
            this.CarGpsTime.HeaderText = "定位时间";
            this.CarGpsTime.Name = "CarGpsTime";
            this.CarGpsTime.ReadOnly = true;
            this.CarGpsTime.Width = 120;
            this.CarCurrentAddress.DataPropertyName = "CurrentAddress";
            this.CarCurrentAddress.HeaderText = "所在位置";
            this.CarCurrentAddress.Name = "CarCurrentAddress";
            this.CarCurrentAddress.ReadOnly = true;
            this.CarCurrentAddress.Width = 300;
            this.CarSpeed.DataPropertyName = "Speed";
            style7.Alignment = DataGridViewContentAlignment.MiddleRight;
            this.CarSpeed.DefaultCellStyle = style7;
            this.CarSpeed.HeaderText = "时速";
            this.CarSpeed.Name = "CarSpeed";
            this.CarSpeed.ReadOnly = true;
            this.CarSpeed.Width = 60;
            this.CarAcc.DataPropertyName = "Acc";
            style8.Alignment = DataGridViewContentAlignment.MiddleCenter;
            this.CarAcc.DefaultCellStyle = style8;
            this.CarAcc.HeaderText = "ACC状态";
            this.CarAcc.Name = "CarAcc";
            this.CarAcc.ReadOnly = true;
            this.CarAcc.Width = 80;
            this.DriverName.DataPropertyName = "DriverName";
            style9.Alignment = DataGridViewContentAlignment.MiddleLeft;
            this.DriverName.DefaultCellStyle = style9;
            this.DriverName.HeaderText = "驾驶员";
            this.DriverName.Name = "DriverName";
            this.DriverName.ReadOnly = true;
            this.DriverName.Width = 80;
            this.CarID.DataPropertyName = "CarID";
            this.CarID.HeaderText = "CarID";
            this.CarID.Name = "CarID";
            this.CarID.ReadOnly = true;
            this.CarID.Visible = false;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(1035, 580);
            base.Controls.Add(this.panel2);
            base.Controls.Add(this.panel1);
            base.Name = "CarTextList";
            this.Text = "车辆信息";
            base.TopMost = true;
            base.Load += new EventHandler(this.CarTextList_Load);
            base.FormClosing += new FormClosingEventHandler(this.CarTextList_FormClosing);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ctxMenuStripDgvHeader.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            ((ISupportInitialize) this.dgvCarTextList).EndInit();
            base.ResumeLayout(false);
        }

       
        private System.ComponentModel.IContainer components;
        private bool bRefresh;
        private Button btnExportExcel;
        private Button btnRefresh;
        private DataGridViewTextBoxColumn CarAcc;
        private DataGridViewTextBoxColumn CarAllDiff;
        private DataGridViewTextBoxColumn CarArea;
        private DataGridViewTextBoxColumn CarCurrentAddress;
        private DataGridViewTextBoxColumn CarGpsTime;
        private DataGridViewTextBoxColumn CarID;
        private DataGridViewTextBoxColumn CarLatitude;
        private DataGridViewTextBoxColumn CarLongitude;
        private DataGridViewTextBoxColumn CarName;
        private DataGridViewTextBoxColumn CarReceTime;
        private DataGridViewTextBoxColumn CarSpeed;
        private DataGridViewTextBoxColumn CarTel;
        private ComboBox cbAreaType;
        private CheckBox cboxAccOn;
        private CheckBox cboxAddress;
        private CheckBox cboxAllDiff;
        private CheckBox cboxDriver;
        private CheckBox cboxGpsTime;
        private CheckBox cboxLatitude;
        private CheckBox cboxLongitude;
        private CheckBox cboxReceTime;
        private CheckBox cboxSelectedAll;
        private CheckBox cboxSpeed;
        private DataGridViewCheckBoxColumn colSelect;
        private ContextMenuStrip ctxMenuStripDgvHeader;
        private DataGridView dgvCarTextList;
        private DataGridViewTextBoxColumn DriverName;
        private DataTable dtLoad;
        private int iCurrentCnt;
        private Label lblAreaName;
        private Label lblAreaType;
        private Label lblCarNum;
        private Label lblDGVRowCount;
        private Label lblDriverName;
        private Label lblSimNum;
        private string m_sQueryCurrentGpsTime;
        private dGetTrackQueryInfo myGetTrackQueryInfo;
        private Panel panel1;
        private Panel panel2;
        private Thread tGetCarPlace;
        private System.Timers.Timer tGetQueryTrackInfo;
        private ToolStripMenuItem tsMenuItemAccOn;
        private ToolStripMenuItem tsMenuItemAddress;
        private ToolStripMenuItem tsMenuItemAllDiff;
        private ToolStripMenuItem tsMenuItemGpsTime;
        private ToolStripMenuItem tsMenuItemLatitude;
        private ToolStripMenuItem tsMenuItemLongitude;
        private ToolStripMenuItem tsMenuItemReceTime;
        private ToolStripMenuItem tsMenuItemSpeed;
        private TextBox txtAreaName;
        private TextBox txtCarNum;
        private TextBox txtDriverName;
        private TextBox txtSimNum;
    }
}