namespace Client
{
    using PublicClass;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    partial class DetailLog
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
 private void InitializeComponent()
        {
            this.grpDetail = new GroupBox();
            this.txtDescribe = new TextBox();
            this.btnDown = new Button();
            this.btnUp = new Button();
            this.lblOrderNameValue = new Label();
            this.lblCommFlagValue = new Label();
            this.lblOrderResultValue = new Label();
            this.lblOrderName = new Label();
            this.lblDescribe = new Label();
            this.lblCommFlag = new Label();
            this.lblOrderResult = new Label();
            this.lblOrderTypeValue = new Label();
            this.lblOrderType = new Label();
            this.lblCarNumValue = new Label();
            this.lblCarNum = new Label();
            this.lblOrderIdValue = new Label();
            this.lblOrderId = new Label();
            this.lblGpsTimeValue = new Label();
            this.lblGpsTime = new Label();
            this.btnClose = new Button();
            this.grpDetail.SuspendLayout();
            base.SuspendLayout();
            this.grpDetail.Controls.Add(this.txtDescribe);
            this.grpDetail.Controls.Add(this.btnDown);
            this.grpDetail.Controls.Add(this.btnUp);
            this.grpDetail.Controls.Add(this.lblOrderNameValue);
            this.grpDetail.Controls.Add(this.lblCommFlagValue);
            this.grpDetail.Controls.Add(this.lblOrderResultValue);
            this.grpDetail.Controls.Add(this.lblOrderName);
            this.grpDetail.Controls.Add(this.lblDescribe);
            this.grpDetail.Controls.Add(this.lblCommFlag);
            this.grpDetail.Controls.Add(this.lblOrderResult);
            this.grpDetail.Controls.Add(this.lblOrderTypeValue);
            this.grpDetail.Controls.Add(this.lblOrderType);
            this.grpDetail.Controls.Add(this.lblCarNumValue);
            this.grpDetail.Controls.Add(this.lblCarNum);
            this.grpDetail.Controls.Add(this.lblOrderIdValue);
            this.grpDetail.Controls.Add(this.lblOrderId);
            this.grpDetail.Controls.Add(this.lblGpsTimeValue);
            this.grpDetail.Controls.Add(this.lblGpsTime);
            this.grpDetail.Location = new Point(13, 12);
            this.grpDetail.Name = "grpDetail";
            this.grpDetail.Size = new Size(386, 318);
            this.grpDetail.TabIndex = 0;
            this.grpDetail.TabStop = false;
            this.grpDetail.Text = "日志详细信息";
            this.txtDescribe.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDescribe.Location = new Point(14, 167);
            this.txtDescribe.Multiline = true;
            this.txtDescribe.Name = "txtDescribe";
            this.txtDescribe.ReadOnly = true;
            this.txtDescribe.ScrollBars = ScrollBars.Vertical;
            this.txtDescribe.Size = new Size(364, 137);
            this.txtDescribe.TabIndex = 6;
            this.btnDown.Location = new Point(305, 53);
            this.btnDown.Name = "btnDown";
            this.btnDown.Size = new Size(75, 23);
            this.btnDown.TabIndex = 5;
            this.btnDown.Text = "下一条";
            this.btnDown.UseVisualStyleBackColor = true;
            this.btnDown.Click += new EventHandler(this.btnDown_Click);
            this.btnUp.Location = new Point(305, 25);
            this.btnUp.Name = "btnUp";
            this.btnUp.Size = new Size(75, 23);
            this.btnUp.TabIndex = 5;
            this.btnUp.Text = "上一条";
            this.btnUp.UseVisualStyleBackColor = true;
            this.btnUp.Click += new EventHandler(this.btnUp_Click);
            this.lblOrderNameValue.AutoSize = true;
            this.lblOrderNameValue.Location = new Point(217, 86);
            this.lblOrderNameValue.MaximumSize = new Size(170, 0);
            this.lblOrderNameValue.Name = "lblOrderNameValue";
            this.lblOrderNameValue.Size = new Size(125, 12);
            this.lblOrderNameValue.TabIndex = 1;
            this.lblOrderNameValue.Text = "实时定位信息提出报文";
            this.lblCommFlagValue.AutoSize = true;
            this.lblCommFlagValue.Location = new Point(217, 114);
            this.lblCommFlagValue.Name = "lblCommFlagValue";
            this.lblCommFlagValue.Size = new Size(59, 12);
            this.lblCommFlagValue.TabIndex = 1;
            this.lblCommFlagValue.Text = "GPRS/CDMA";
            this.lblOrderResultValue.AutoSize = true;
            this.lblOrderResultValue.Location = new Point(71, 114);
            this.lblOrderResultValue.Name = "lblOrderResultValue";
            this.lblOrderResultValue.Size = new Size(29, 12);
            this.lblOrderResultValue.TabIndex = 1;
            this.lblOrderResultValue.Text = "成功";
            this.lblOrderName.AutoSize = true;
            this.lblOrderName.Location = new Point(146, 86);
            this.lblOrderName.Name = "lblOrderName";
            this.lblOrderName.Size = new Size(65, 12);
            this.lblOrderName.TabIndex = 0;
            this.lblOrderName.Text = "操作类型：";
            this.lblDescribe.AutoSize = true;
            this.lblDescribe.Location = new Point(24, 142);
            this.lblDescribe.Name = "lblDescribe";
            this.lblDescribe.Size = new Size(41, 12);
            this.lblDescribe.TabIndex = 0;
            this.lblDescribe.Text = "描述：";
            this.lblCommFlag.AutoSize = true;
            this.lblCommFlag.Location = new Point(146, 114);
            this.lblCommFlag.Name = "lblCommFlag";
            this.lblCommFlag.Size = new Size(65, 12);
            this.lblCommFlag.TabIndex = 0;
            this.lblCommFlag.Text = "通讯方式：";
            this.lblOrderResult.AutoSize = true;
            this.lblOrderResult.Location = new Point(24, 114);
            this.lblOrderResult.Name = "lblOrderResult";
            this.lblOrderResult.Size = new Size(41, 12);
            this.lblOrderResult.TabIndex = 0;
            this.lblOrderResult.Text = "结果：";
            this.lblOrderTypeValue.AutoSize = true;
            this.lblOrderTypeValue.Location = new Point(71, 86);
            this.lblOrderTypeValue.Name = "lblOrderTypeValue";
            this.lblOrderTypeValue.Size = new Size(29, 12);
            this.lblOrderTypeValue.TabIndex = 1;
            this.lblOrderTypeValue.Text = "报警";
            this.lblOrderType.AutoSize = true;
            this.lblOrderType.Location = new Point(24, 86);
            this.lblOrderType.Name = "lblOrderType";
            this.lblOrderType.Size = new Size(41, 12);
            this.lblOrderType.TabIndex = 0;
            this.lblOrderType.Text = "类型：";
            this.lblCarNumValue.AutoSize = true;
            this.lblCarNumValue.Location = new Point(217, 58);
            this.lblCarNumValue.Name = "lblCarNumValue";
            this.lblCarNumValue.Size = new Size(35, 12);
            this.lblCarNumValue.TabIndex = 1;
            this.lblCarNumValue.Text = "52496";
            this.lblCarNum.AutoSize = true;
            this.lblCarNum.Location = new Point(158, 58);
            this.lblCarNum.Name = "lblCarNum";
            this.lblCarNum.Size = new Size(53, 12);
            this.lblCarNum.TabIndex = 0;
            this.lblCarNum.Text = "车牌号：";
            this.lblOrderIdValue.AutoSize = true;
            this.lblOrderIdValue.Location = new Point(71, 58);
            this.lblOrderIdValue.Name = "lblOrderIdValue";
            this.lblOrderIdValue.Size = new Size(17, 12);
            this.lblOrderIdValue.TabIndex = 1;
            this.lblOrderIdValue.Text = "15";
            this.lblOrderId.AutoSize = true;
            this.lblOrderId.Location = new Point(12, 58);
            this.lblOrderId.Name = "lblOrderId";
            this.lblOrderId.Size = new Size(53, 12);
            this.lblOrderId.TabIndex = 0;
            this.lblOrderId.Text = "流水号：";
            this.lblGpsTimeValue.AutoSize = true;
            this.lblGpsTimeValue.Location = new Point(71, 30);
            this.lblGpsTimeValue.Name = "lblGpsTimeValue";
            this.lblGpsTimeValue.Size = new Size(107, 12);
            this.lblGpsTimeValue.TabIndex = 1;
            this.lblGpsTimeValue.Text = "09-09-15 13:15:50";
            this.lblGpsTime.AutoSize = true;
            this.lblGpsTime.Location = new Point(24, 30);
            this.lblGpsTime.Name = "lblGpsTime";
            this.lblGpsTime.Size = new Size(41, 12);
            this.lblGpsTime.TabIndex = 0;
            this.lblGpsTime.Text = "时间：";
            this.btnClose.DialogResult =  System.Windows.Forms.DialogResult.Cancel;
            this.btnClose.Location = new Point(324, 336);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new Size(75, 23);
            this.btnClose.TabIndex = 5;
            this.btnClose.Text = "关闭(&C)";
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnClose.Click += new EventHandler(this.btnClose_Click);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            base.CancelButton = this.btnClose;
            base.ClientSize = new Size(416, 372);
            base.Controls.Add(this.btnClose);
            base.Controls.Add(this.grpDetail);
            base.Name = "DetailLog";
            base.Padding = new Padding(10);
            this.Text = "日志属性";
            this.grpDetail.ResumeLayout(false);
            this.grpDetail.PerformLayout();
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private System.Windows.Forms.GroupBox grpDetail;
        private Label lblCarNum;
        private Label lblCarNumValue;
        private Label lblCommFlag;
        private Label lblCommFlagValue;
        private Label lblDescribe;
        private Label lblGpsTime;
        private Label lblGpsTimeValue;
        private Label lblOrderId;
        private Label lblOrderIdValue;
        private Label lblOrderName;
        private Label lblOrderNameValue;
        private Label lblOrderResult;
        private Label lblOrderResultValue;
        private Label lblOrderType;
        private Label lblOrderTypeValue;
        private TextBox txtDescribe;
    }
}