namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;

    partial class itmCarInOutOfRangeTime
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.components = new Container();
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.grpPostalRoute = new GroupBox();
            this.dgvPostRoute = new DataGridView();
            this.PointIndex = new DataGridViewTextBoxColumn();
            this.MenuStrip = new ContextMenuStrip(this.components);
            this.插入ToolStripMenuItem = new ToolStripMenuItem();
            this.删除此行ToolStripMenuItem = new ToolStripMenuItem();
            this.PointID = new DataGridViewTextBoxColumn();
            this.PointName = new DataGridViewComboBoxColumn();
            this.StartTime = new DataGridViewTextBoxColumn();
            this.EndTime = new DataGridViewTextBoxColumn();
            this.CrossDay = new DataGridViewCheckBoxColumn();
            this.lblExplain = new Label();
            this.pnlWait = new Panel();
            this.pbPicWait = new PictureBox();
            this.lblWaitText = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpPostalRoute.SuspendLayout();
            ((ISupportInitialize) this.dgvPostRoute).BeginInit();
            this.MenuStrip.SuspendLayout();
            this.pnlWait.SuspendLayout();
            ((ISupportInitialize) this.pbPicWait).BeginInit();
            base.SuspendLayout();
            base.grpCar.Size = new Size(469, 116);
            base.pnlBtn.Controls.Add(this.pnlWait);
            base.pnlBtn.Controls.Add(this.lblExplain);
            base.pnlBtn.Location = new Point(5, 488);
            base.pnlBtn.Size = new Size(469, 28);
            base.pnlBtn.Controls.SetChildIndex(base.btnOK, 0);
            base.pnlBtn.Controls.SetChildIndex(base.btnCancel, 0);
            base.pnlBtn.Controls.SetChildIndex(this.lblExplain, 0);
            base.pnlBtn.Controls.SetChildIndex(this.pnlWait, 0);
            base.btnCancel.Location = new Point(391, 3);
            base.btnOK.Location = new Point(306, 3);
            this.grpPostalRoute.Controls.Add(this.dgvPostRoute);
            this.grpPostalRoute.Dock = DockStyle.Top;
            this.grpPostalRoute.Location = new Point(5, 121);
            this.grpPostalRoute.Name = "grpPostalRoute";
            this.grpPostalRoute.Size = new Size(469, 367);
            this.grpPostalRoute.TabIndex = 11;
            this.grpPostalRoute.TabStop = false;
            this.grpPostalRoute.Text = "邮路设置";
            this.dgvPostRoute.AllowUserToResizeColumns = false;
            this.dgvPostRoute.AllowUserToResizeRows = false;
            style.BackColor = SystemColors.ActiveCaptionText;
            this.dgvPostRoute.AlternatingRowsDefaultCellStyle = style;
            this.dgvPostRoute.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPostRoute.BackgroundColor = Color.White;
            this.dgvPostRoute.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvPostRoute.Columns.AddRange(new DataGridViewColumn[] { this.PointIndex, this.PointID, this.PointName, this.StartTime, this.EndTime, this.CrossDay });
            this.dgvPostRoute.Dock = DockStyle.Fill;
            this.dgvPostRoute.Location = new Point(3, 17);
            this.dgvPostRoute.MultiSelect = false;
            this.dgvPostRoute.Name = "dgvPostRoute";
            this.dgvPostRoute.RowHeadersVisible = false;
            this.dgvPostRoute.RowTemplate.Height = 23;
            this.dgvPostRoute.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvPostRoute.Size = new Size(463, 347);
            this.dgvPostRoute.TabIndex = 2;
            this.dgvPostRoute.Tag = "9999";
            this.dgvPostRoute.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvPostRoute_CellDoubleClick);
            this.dgvPostRoute.CellMouseDown += new DataGridViewCellMouseEventHandler(this.dgvPostRoute_CellMouseDown);
            this.dgvPostRoute.CellFormatting += new DataGridViewCellFormattingEventHandler(this.dgvPostRoute_CellFormatting);
            this.dgvPostRoute.CellEndEdit += new DataGridViewCellEventHandler(this.dgvPostRoute_CellEndEdit);
            this.dgvPostRoute.DataError += new DataGridViewDataErrorEventHandler(this.dgvPostRoute_DataError);
            this.dgvPostRoute.KeyDown += new KeyEventHandler(this.dgvPostRoute_KeyDown);
            this.dgvPostRoute.CellContentClick += new DataGridViewCellEventHandler(this.dgvPostRoute_CellContentClick);
            this.PointIndex.ContextMenuStrip = this.MenuStrip;
            this.PointIndex.DataPropertyName = "PointIndex";
            this.PointIndex.FillWeight = 30f;
            this.PointIndex.HeaderText = "序列";
            this.PointIndex.Name = "PointIndex";
            this.PointIndex.ReadOnly = true;
            this.PointIndex.Resizable = DataGridViewTriState.False;
            this.PointIndex.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.MenuStrip.Items.AddRange(new ToolStripItem[] { this.插入ToolStripMenuItem, this.删除此行ToolStripMenuItem });
            this.MenuStrip.Name = "MenuStrip";
            this.MenuStrip.Size = new Size(119, 48);
            this.MenuStrip.Opening += new CancelEventHandler(this.MenuStrip_Opening);
            this.插入ToolStripMenuItem.Name = "插入ToolStripMenuItem";
            this.插入ToolStripMenuItem.Size = new Size(118, 22);
            this.插入ToolStripMenuItem.Text = "插入新行";
            this.插入ToolStripMenuItem.Click += new EventHandler(this.插入ToolStripMenuItem_Click);
            this.删除此行ToolStripMenuItem.Name = "删除此行ToolStripMenuItem";
            this.删除此行ToolStripMenuItem.Size = new Size(118, 22);
            this.删除此行ToolStripMenuItem.Text = "删除此行";
            this.删除此行ToolStripMenuItem.Click += new EventHandler(this.删除此行ToolStripMenuItem_Click);
            this.PointID.ContextMenuStrip = this.MenuStrip;
            this.PointID.DataPropertyName = "PointID";
            this.PointID.HeaderText = "点ID";
            this.PointID.Name = "PointID";
            this.PointID.Visible = false;
            this.PointName.ContextMenuStrip = this.MenuStrip;
            this.PointName.DataPropertyName = "PointName";
            this.PointName.FillWeight = 90f;
            this.PointName.HeaderText = "站点名称";
            this.PointName.MaxDropDownItems = 20;
            this.PointName.Name = "PointName";
            this.PointName.Resizable = DataGridViewTriState.False;
            this.StartTime.ContextMenuStrip = this.MenuStrip;
            this.StartTime.DataPropertyName = "StartTime";
            this.StartTime.HeaderText = "到达时间";
            this.StartTime.Name = "StartTime";
            this.StartTime.ReadOnly = true;
            this.StartTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.EndTime.ContextMenuStrip = this.MenuStrip;
            this.EndTime.DataPropertyName = "EndTime";
            this.EndTime.HeaderText = "离开时间";
            this.EndTime.Name = "EndTime";
            this.EndTime.ReadOnly = true;
            this.EndTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.CrossDay.DataPropertyName = "CrossDay";
            this.CrossDay.FalseValue = "False";
            this.CrossDay.FillWeight = 50f;
            this.CrossDay.HeaderText = "跨天";
            this.CrossDay.Name = "CrossDay";
            this.CrossDay.ReadOnly = true;
            this.CrossDay.Resizable = DataGridViewTriState.True;
            this.CrossDay.SortMode = DataGridViewColumnSortMode.Automatic;
            this.CrossDay.TrueValue = "True";
            this.lblExplain.AutoSize = true;
            this.lblExplain.ForeColor = Color.Red;
            this.lblExplain.Location = new Point(13, 8);
            this.lblExplain.Name = "lblExplain";
            this.lblExplain.Size = new Size(89, 12);
            this.lblExplain.TabIndex = 40;
            this.lblExplain.Tag = "9999";
            this.lblExplain.Text = "*按Del键删除行";
            this.pnlWait.Controls.Add(this.pbPicWait);
            this.pnlWait.Controls.Add(this.lblWaitText);
            this.pnlWait.Location = new Point(107, 3);
            this.pnlWait.Name = "pnlWait";
            this.pnlWait.Size = new Size(129, 22);
            this.pnlWait.TabIndex = 41;
            this.pnlWait.Tag = "9999";
            this.pbPicWait.BackColor = Color.Transparent;
            this.pbPicWait.Image = Resources.loading;
            this.pbPicWait.InitialImage = null;
            this.pbPicWait.Location = new Point(3, 3);
            this.pbPicWait.Name = "pbPicWait";
            this.pbPicWait.Size = new Size(16, 16);
            this.pbPicWait.TabIndex = 11;
            this.pbPicWait.TabStop = false;
            this.pbPicWait.Tag = "9999";
            this.pbPicWait.Visible = false;
            this.lblWaitText.AutoSize = true;
            this.lblWaitText.Location = new Point(22, 5);
            this.lblWaitText.Name = "lblWaitText";
            this.lblWaitText.Size = new Size(89, 12);
            this.lblWaitText.TabIndex = 9;
            this.lblWaitText.Text = "正在执行中....";
            this.lblWaitText.Visible = false;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(479, 521);
            base.Controls.Add(this.grpPostalRoute);
            base.Name = "itmCarInOutOfRangeTime";
            this.Text = "设置车辆按时到离站";
            base.Load += new EventHandler(this.itmCarPostalRoute_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpPostalRoute, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            base.pnlBtn.PerformLayout();
            this.grpPostalRoute.ResumeLayout(false);
            ((ISupportInitialize) this.dgvPostRoute).EndInit();
            this.MenuStrip.ResumeLayout(false);
            this.pnlWait.ResumeLayout(false);
            this.pnlWait.PerformLayout();
            ((ISupportInitialize) this.pbPicWait).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private DataTable AllRegion;
        private DataGridViewCheckBoxColumn CrossDay;
        private DataGridView dgvPostRoute;
        private DataGridViewTextBoxColumn EndTime;
        private GroupBox grpPostalRoute;
        private Label lblExplain;
        private Label lblWaitText;
        private System.Windows.Forms.ContextMenuStrip MenuStrip;
        private int ParamType;
        private PictureBox pbPicWait;
        private Panel pnlWait;
        private DataGridViewTextBoxColumn PointID;
        private DataGridViewTextBoxColumn PointIndex;
        private DataGridViewComboBoxColumn PointName;
        private DataGridViewTextBoxColumn StartTime;
        private ToolStripMenuItem 插入ToolStripMenuItem;
        private ToolStripMenuItem 删除此行ToolStripMenuItem;
    }
}