namespace Client
{
    using Remoting;
    using ParamLibrary.CarEntity;
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class itmCarDetail
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(itmCarDetail));
            this.pnlAttribute = new Panel();
            this.tcAttribute = new TabControl();
            this.tpBasic = new TabPage();
            this.txtOperateTypeName = new TextBox();
            this.lblOperateTypeName = new Label();
            this.txtPlateColor = new TextBox();
            this.lblPlateColor = new Label();
            this.txtCarState = new TextBox();
            this.lblCarState = new Label();
            this.lblSimPasswordValue = new TextBox();
            this.lblSimPassword = new Label();
            this.lblSimEndTimeValue = new TextBox();
            this.lblSimEndTime = new Label();
            this.lblSimStartTimeValue = new TextBox();
            this.lblSimStartTime = new Label();
            this.lblColorValue = new TextBox();
            this.lblColor = new Label();
            this.lblRegistrationTimeValue = new TextBox();
            this.lblRegistrationTime = new Label();
            this.lblAheadDateValue = new TextBox();
            this.lblAheadDate = new Label();
            this.lblServerEndTimeValue = new TextBox();
            this.lblServerEndTime = new Label();
            this.lblServerStartTimeValue = new TextBox();
            this.lblServerStartTime = new Label();
            this.lblCarTypeValue = new TextBox();
            this.lblCarType = new Label();
            this.lblSimNumValue = new TextBox();
            this.lblSimNum = new Label();
            this.lblCarNumValue = new TextBox();
            this.lblCarNum = new Label();
            this.lblCarIdValue = new TextBox();
            this.lblCarId = new Label();
            this.lblAreaValue = new TextBox();
            this.lblArea = new Label();
            this.tpTerminal = new TabPage();
            this.txtTermSerial = new TextBox();
            this.lblTermSerial = new Label();
            this.lblSupportCdmaValue = new TextBox();
            this.lblSupportCdma = new Label();
            this.lblSupportGprsValue = new TextBox();
            this.lblSupportGprs = new Label();
            this.lblSupportMsgValue = new TextBox();
            this.lblSupportMsg = new Label();
            this.lblTerminalVersionValue = new TextBox();
            this.lblTerminalVersion = new Label();
            this.lblTerminalTypeValue = new TextBox();
            this.lblTerminalType = new Label();
            this.tpOther = new TabPage();
            this.lblDriverPhoneValue = new TextBox();
            this.lblDriverPhone = new Label();
            this.lblDriverNameValue = new TextBox();
            this.lblDriverName = new Label();
            this.lblSteelGradeValue = new TextBox();
            this.lblSteelGrade = new Label();
            this.lblSecondLinkmanTelValue = new TextBox();
            this.lblSecondLinkmanTel = new Label();
            this.lblSecondLinkmanValue = new TextBox();
            this.lblSecondLinkman = new Label();
            this.lblFirstLinkmanTelValue = new TextBox();
            this.lblCompany = new Label();
            this.lblCompanyValue = new TextBox();
            this.lblFirstLinkmanTel = new Label();
            this.lblFirstLinkmanValue = new TextBox();
            this.lblFirstLinkman = new Label();
            this.lblAddressValue = new TextBox();
            this.lblAddress = new Label();
            this.lblIdentityCardValue = new TextBox();
            this.lblIdentityCard = new Label();
            this.lblOwnerEmailValue = new TextBox();
            this.lblOwnerEmail = new Label();
            this.lblOwnerSimNumValue = new TextBox();
            this.lblOwnerSimNum = new Label();
            this.lblOwnerNameValue = new TextBox();
            this.lblOwnerName = new Label();
            this.lblCarBrandValue = new TextBox();
            this.lblCarBrand = new Label();
            this.tpRemark = new TabPage();
            this.lblRemarkValue = new TextBox();
            this.lblRemark = new Label();
            this.tpRegion = new TabPage();
            this.txtCEOContact = new TextBox();
            this.lblCEOContact = new Label();
            this.txtCEOName = new TextBox();
            this.lblCEOName = new Label();
            this.txtIssuingAgency = new TextBox();
            this.lblIssuingAgency = new Label();
            this.txtRoadTransportID = new TextBox();
            this.lblRoadTransportID = new Label();
            this.txtOperateScope = new TextBox();
            this.lblOperateScope = new Label();
            this.txtRegion = new TextBox();
            this.lblRegion = new Label();
            this.txtContactMode = new TextBox();
            this.lblContactMode = new Label();
            this.txtContactName = new TextBox();
            this.lblContactName = new Label();
            this.txtAreaName = new TextBox();
            this.lblAreaName = new Label();
            this.pnlBtn = new Panel();
            this.btnClose = new Button();
            this.pnlAttribute.SuspendLayout();
            this.tcAttribute.SuspendLayout();
            this.tpBasic.SuspendLayout();
            this.tpTerminal.SuspendLayout();
            this.tpOther.SuspendLayout();
            this.tpRemark.SuspendLayout();
            this.tpRegion.SuspendLayout();
            this.pnlBtn.SuspendLayout();
            base.SuspendLayout();
            this.pnlAttribute.Controls.Add(this.tcAttribute);
            this.pnlAttribute.Dock = DockStyle.Fill;
            this.pnlAttribute.Location = new Point(5, 5);
            this.pnlAttribute.Name = "pnlAttribute";
            this.pnlAttribute.Size = new Size(400, 503);
            this.pnlAttribute.TabIndex = 3;
            this.tcAttribute.Controls.Add(this.tpBasic);
            this.tcAttribute.Controls.Add(this.tpTerminal);
            this.tcAttribute.Controls.Add(this.tpOther);
            this.tcAttribute.Controls.Add(this.tpRemark);
            this.tcAttribute.Controls.Add(this.tpRegion);
            this.tcAttribute.Dock = DockStyle.Fill;
            this.tcAttribute.Location = new Point(0, 0);
            this.tcAttribute.Name = "tcAttribute";
            this.tcAttribute.SelectedIndex = 0;
            this.tcAttribute.Size = new Size(400, 503);
            this.tcAttribute.TabIndex = 0;
            this.tpBasic.Controls.Add(this.txtOperateTypeName);
            this.tpBasic.Controls.Add(this.lblOperateTypeName);
            this.tpBasic.Controls.Add(this.txtPlateColor);
            this.tpBasic.Controls.Add(this.lblPlateColor);
            this.tpBasic.Controls.Add(this.txtCarState);
            this.tpBasic.Controls.Add(this.lblCarState);
            this.tpBasic.Controls.Add(this.lblSimPasswordValue);
            this.tpBasic.Controls.Add(this.lblSimPassword);
            this.tpBasic.Controls.Add(this.lblSimEndTimeValue);
            this.tpBasic.Controls.Add(this.lblSimEndTime);
            this.tpBasic.Controls.Add(this.lblSimStartTimeValue);
            this.tpBasic.Controls.Add(this.lblSimStartTime);
            this.tpBasic.Controls.Add(this.lblColorValue);
            this.tpBasic.Controls.Add(this.lblColor);
            this.tpBasic.Controls.Add(this.lblRegistrationTimeValue);
            this.tpBasic.Controls.Add(this.lblRegistrationTime);
            this.tpBasic.Controls.Add(this.lblAheadDateValue);
            this.tpBasic.Controls.Add(this.lblAheadDate);
            this.tpBasic.Controls.Add(this.lblServerEndTimeValue);
            this.tpBasic.Controls.Add(this.lblServerEndTime);
            this.tpBasic.Controls.Add(this.lblServerStartTimeValue);
            this.tpBasic.Controls.Add(this.lblServerStartTime);
            this.tpBasic.Controls.Add(this.lblCarTypeValue);
            this.tpBasic.Controls.Add(this.lblCarType);
            this.tpBasic.Controls.Add(this.lblSimNumValue);
            this.tpBasic.Controls.Add(this.lblSimNum);
            this.tpBasic.Controls.Add(this.lblCarNumValue);
            this.tpBasic.Controls.Add(this.lblCarNum);
            this.tpBasic.Controls.Add(this.lblCarIdValue);
            this.tpBasic.Controls.Add(this.lblCarId);
            this.tpBasic.Controls.Add(this.lblAreaValue);
            this.tpBasic.Controls.Add(this.lblArea);
            this.tpBasic.Location = new Point(4, 21);
            this.tpBasic.Name = "tpBasic";
            this.tpBasic.Padding = new Padding(3);
            this.tpBasic.Size = new Size(392, 478);
            this.tpBasic.TabIndex = 0;
            this.tpBasic.Text = "基本信息";
            this.tpBasic.UseVisualStyleBackColor = true;
            this.txtOperateTypeName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtOperateTypeName.Location = new Point(138, 445);
            this.txtOperateTypeName.Name = "txtOperateTypeName";
            this.txtOperateTypeName.ReadOnly = true;
            this.txtOperateTypeName.Size = new Size(165, 21);
            this.txtOperateTypeName.TabIndex = 21;
            this.txtOperateTypeName.Text = " ";
            this.lblOperateTypeName.AutoSize = true;
            this.lblOperateTypeName.Location = new Point(67, 449);
            this.lblOperateTypeName.Name = "lblOperateTypeName";
            this.lblOperateTypeName.Size = new Size(65, 12);
            this.lblOperateTypeName.TabIndex = 20;
            this.lblOperateTypeName.Text = "所属行业：";
            this.txtPlateColor.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPlateColor.Location = new Point(138, 418);
            this.txtPlateColor.Name = "txtPlateColor";
            this.txtPlateColor.ReadOnly = true;
            this.txtPlateColor.Size = new Size(165, 21);
            this.txtPlateColor.TabIndex = 19;
            this.txtPlateColor.Text = " ";
            this.lblPlateColor.AutoSize = true;
            this.lblPlateColor.Location = new Point(67, 422);
            this.lblPlateColor.Name = "lblPlateColor";
            this.lblPlateColor.Size = new Size(65, 12);
            this.lblPlateColor.TabIndex = 18;
            this.lblPlateColor.Text = "车牌颜色：";
            this.txtCarState.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCarState.Location = new Point(138, 390);
            this.txtCarState.Name = "txtCarState";
            this.txtCarState.ReadOnly = true;
            this.txtCarState.Size = new Size(165, 21);
            this.txtCarState.TabIndex = 17;
            this.txtCarState.Text = " ";
            this.lblCarState.AutoSize = true;
            this.lblCarState.Location = new Point(67, 392);
            this.lblCarState.Name = "lblCarState";
            this.lblCarState.Size = new Size(65, 12);
            this.lblCarState.TabIndex = 16;
            this.lblCarState.Text = "车辆状态：";
            this.lblSimPasswordValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSimPasswordValue.Location = new Point(138, 362);
            this.lblSimPasswordValue.Name = "lblSimPasswordValue";
            this.lblSimPasswordValue.ReadOnly = true;
            this.lblSimPasswordValue.Size = new Size(165, 21);
            this.lblSimPasswordValue.TabIndex = 0;
            this.lblSimPasswordValue.Text = " ";
            this.lblSimPassword.AutoSize = true;
            this.lblSimPassword.Location = new Point(61, 366);
            this.lblSimPassword.Name = "lblSimPassword";
            this.lblSimPassword.Size = new Size(71, 12);
            this.lblSimPassword.TabIndex = 0;
            this.lblSimPassword.Text = "SIM卡密码：";
            this.lblSimEndTimeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSimEndTimeValue.Location = new Point(138, 333);
            this.lblSimEndTimeValue.Name = "lblSimEndTimeValue";
            this.lblSimEndTimeValue.ReadOnly = true;
            this.lblSimEndTimeValue.Size = new Size(165, 21);
            this.lblSimEndTimeValue.TabIndex = 0;
            this.lblSimEndTimeValue.Text = " ";
            this.lblSimEndTime.AutoSize = true;
            this.lblSimEndTime.Location = new Point(37, 337);
            this.lblSimEndTime.Name = "lblSimEndTime";
            this.lblSimEndTime.Size = new Size(95, 12);
            this.lblSimEndTime.TabIndex = 0;
            this.lblSimEndTime.Text = "SIM卡过期时间：";
            this.lblSimStartTimeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSimStartTimeValue.Location = new Point(138, 304);
            this.lblSimStartTimeValue.Name = "lblSimStartTimeValue";
            this.lblSimStartTimeValue.ReadOnly = true;
            this.lblSimStartTimeValue.Size = new Size(165, 21);
            this.lblSimStartTimeValue.TabIndex = 0;
            this.lblSimStartTimeValue.Text = " ";
            this.lblSimStartTime.AutoSize = true;
            this.lblSimStartTime.Location = new Point(37, 308);
            this.lblSimStartTime.Name = "lblSimStartTime";
            this.lblSimStartTime.Size = new Size(95, 12);
            this.lblSimStartTime.TabIndex = 0;
            this.lblSimStartTime.Text = "SIM卡开卡时间：";
            this.lblColorValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblColorValue.Location = new Point(138, 275);
            this.lblColorValue.Name = "lblColorValue";
            this.lblColorValue.ReadOnly = true;
            this.lblColorValue.Size = new Size(165, 21);
            this.lblColorValue.TabIndex = 0;
            this.lblColorValue.Text = " ";
            this.lblColor.AutoSize = true;
            this.lblColor.Location = new Point(67, 279);
            this.lblColor.Name = "lblColor";
            this.lblColor.Size = new Size(65, 12);
            this.lblColor.TabIndex = 0;
            this.lblColor.Text = "车辆颜色：";
            this.lblRegistrationTimeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblRegistrationTimeValue.Location = new Point(138, 246);
            this.lblRegistrationTimeValue.Name = "lblRegistrationTimeValue";
            this.lblRegistrationTimeValue.ReadOnly = true;
            this.lblRegistrationTimeValue.Size = new Size(165, 21);
            this.lblRegistrationTimeValue.TabIndex = 0;
            this.lblRegistrationTimeValue.Text = " ";
            this.lblRegistrationTime.AutoSize = true;
            this.lblRegistrationTime.Location = new Point(43, 250);
            this.lblRegistrationTime.Name = "lblRegistrationTime";
            this.lblRegistrationTime.Size = new Size(89, 12);
            this.lblRegistrationTime.TabIndex = 0;
            this.lblRegistrationTime.Text = "车辆注册时间：";
            this.lblAheadDateValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblAheadDateValue.Location = new Point(138, 217);
            this.lblAheadDateValue.Name = "lblAheadDateValue";
            this.lblAheadDateValue.ReadOnly = true;
            this.lblAheadDateValue.Size = new Size(165, 21);
            this.lblAheadDateValue.TabIndex = 0;
            this.lblAheadDateValue.Text = " ";
            this.lblAheadDate.AutoSize = true;
            this.lblAheadDate.Location = new Point(43, 221);
            this.lblAheadDate.Name = "lblAheadDate";
            this.lblAheadDate.Size = new Size(89, 12);
            this.lblAheadDate.TabIndex = 0;
            this.lblAheadDate.Text = "提前提醒天数：";
            this.lblServerEndTimeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblServerEndTimeValue.Location = new Point(138, 188);
            this.lblServerEndTimeValue.Name = "lblServerEndTimeValue";
            this.lblServerEndTimeValue.ReadOnly = true;
            this.lblServerEndTimeValue.Size = new Size(165, 21);
            this.lblServerEndTimeValue.TabIndex = 0;
            this.lblServerEndTimeValue.Text = " ";
            this.lblServerEndTime.AutoSize = true;
            this.lblServerEndTime.Location = new Point(43, 192);
            this.lblServerEndTime.Name = "lblServerEndTime";
            this.lblServerEndTime.Size = new Size(89, 12);
            this.lblServerEndTime.TabIndex = 0;
            this.lblServerEndTime.Text = "服务结束时间：";
            this.lblServerStartTimeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblServerStartTimeValue.Location = new Point(138, 159);
            this.lblServerStartTimeValue.Name = "lblServerStartTimeValue";
            this.lblServerStartTimeValue.ReadOnly = true;
            this.lblServerStartTimeValue.Size = new Size(165, 21);
            this.lblServerStartTimeValue.TabIndex = 0;
            this.lblServerStartTimeValue.Text = " ";
            this.lblServerStartTime.AutoSize = true;
            this.lblServerStartTime.Location = new Point(43, 163);
            this.lblServerStartTime.Name = "lblServerStartTime";
            this.lblServerStartTime.Size = new Size(89, 12);
            this.lblServerStartTime.TabIndex = 0;
            this.lblServerStartTime.Text = "服务开始时间：";
            this.lblCarTypeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblCarTypeValue.Location = new Point(138, 130);
            this.lblCarTypeValue.Name = "lblCarTypeValue";
            this.lblCarTypeValue.ReadOnly = true;
            this.lblCarTypeValue.Size = new Size(165, 21);
            this.lblCarTypeValue.TabIndex = 0;
            this.lblCarTypeValue.Text = " ";
            this.lblCarType.AutoSize = true;
            this.lblCarType.Location = new Point(67, 134);
            this.lblCarType.Name = "lblCarType";
            this.lblCarType.Size = new Size(65, 12);
            this.lblCarType.TabIndex = 0;
            this.lblCarType.Text = "车辆类型：";
            this.lblSimNumValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSimNumValue.Location = new Point(138, 101);
            this.lblSimNumValue.Name = "lblSimNumValue";
            this.lblSimNumValue.ReadOnly = true;
            this.lblSimNumValue.Size = new Size(165, 21);
            this.lblSimNumValue.TabIndex = 0;
            this.lblSimNumValue.Text = " ";
            this.lblSimNum.AutoSize = true;
            this.lblSimNum.Location = new Point(67, 105);
            this.lblSimNum.Name = "lblSimNum";
            this.lblSimNum.Size = new Size(65, 12);
            this.lblSimNum.TabIndex = 0;
            this.lblSimNum.Text = "车载电话：";
            this.lblCarNumValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblCarNumValue.Location = new Point(138, 72);
            this.lblCarNumValue.Name = "lblCarNumValue";
            this.lblCarNumValue.ReadOnly = true;
            this.lblCarNumValue.Size = new Size(165, 21);
            this.lblCarNumValue.TabIndex = 0;
            this.lblCarNumValue.Text = " ";
            this.lblCarNum.AutoSize = true;
            this.lblCarNum.Location = new Point(67, 76);
            this.lblCarNum.Name = "lblCarNum";
            this.lblCarNum.Size = new Size(65, 12);
            this.lblCarNum.TabIndex = 0;
            this.lblCarNum.Text = "车牌号码：";
            this.lblCarIdValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblCarIdValue.Location = new Point(138, 43);
            this.lblCarIdValue.Name = "lblCarIdValue";
            this.lblCarIdValue.ReadOnly = true;
            this.lblCarIdValue.Size = new Size(165, 21);
            this.lblCarIdValue.TabIndex = 0;
            this.lblCarIdValue.Text = " ";
            this.lblCarId.AutoSize = true;
            this.lblCarId.Location = new Point(67, 47);
            this.lblCarId.Name = "lblCarId";
            this.lblCarId.Size = new Size(65, 12);
            this.lblCarId.TabIndex = 0;
            this.lblCarId.Text = "车辆编号：";
            this.lblAreaValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblAreaValue.Location = new Point(138, 14);
            this.lblAreaValue.Name = "lblAreaValue";
            this.lblAreaValue.ReadOnly = true;
            this.lblAreaValue.Size = new Size(165, 21);
            this.lblAreaValue.TabIndex = 0;
            this.lblAreaValue.Text = " ";
            this.lblArea.AutoSize = true;
            this.lblArea.Location = new Point(67, 18);
            this.lblArea.Name = "lblArea";
            this.lblArea.Size = new Size(65, 12);
            this.lblArea.TabIndex = 0;
            this.lblArea.Text = "所属业户：";
            this.tpTerminal.Controls.Add(this.txtTermSerial);
            this.tpTerminal.Controls.Add(this.lblTermSerial);
            this.tpTerminal.Controls.Add(this.lblSupportCdmaValue);
            this.tpTerminal.Controls.Add(this.lblSupportCdma);
            this.tpTerminal.Controls.Add(this.lblSupportGprsValue);
            this.tpTerminal.Controls.Add(this.lblSupportGprs);
            this.tpTerminal.Controls.Add(this.lblSupportMsgValue);
            this.tpTerminal.Controls.Add(this.lblSupportMsg);
            this.tpTerminal.Controls.Add(this.lblTerminalVersionValue);
            this.tpTerminal.Controls.Add(this.lblTerminalVersion);
            this.tpTerminal.Controls.Add(this.lblTerminalTypeValue);
            this.tpTerminal.Controls.Add(this.lblTerminalType);
            this.tpTerminal.Location = new Point(4, 21);
            this.tpTerminal.Name = "tpTerminal";
            this.tpTerminal.Padding = new Padding(3);
            this.tpTerminal.Size = new Size(392, 478);
            this.tpTerminal.TabIndex = 1;
            this.tpTerminal.Text = "车载终端信息";
            this.tpTerminal.UseVisualStyleBackColor = true;
            this.txtTermSerial.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTermSerial.Location = new Point(138, 159);
            this.txtTermSerial.Name = "txtTermSerial";
            this.txtTermSerial.ReadOnly = true;
            this.txtTermSerial.Size = new Size(165, 21);
            this.txtTermSerial.TabIndex = 10;
            this.txtTermSerial.Text = " ";
            this.lblTermSerial.AutoSize = true;
            this.lblTermSerial.Location = new Point(55, 163);
            this.lblTermSerial.Name = "lblTermSerial";
            this.lblTermSerial.Size = new Size(77, 12);
            this.lblTermSerial.TabIndex = 9;
            this.lblTermSerial.Text = "车载终端ID：";
            this.lblSupportCdmaValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSupportCdmaValue.Location = new Point(138, 131);
            this.lblSupportCdmaValue.Name = "lblSupportCdmaValue";
            this.lblSupportCdmaValue.ReadOnly = true;
            this.lblSupportCdmaValue.Size = new Size(165, 21);
            this.lblSupportCdmaValue.TabIndex = 6;
            this.lblSupportCdmaValue.Text = " ";
            this.lblSupportCdma.AutoSize = true;
            this.lblSupportCdma.Location = new Point(43, 135);
            this.lblSupportCdma.Name = "lblSupportCdma";
            this.lblSupportCdma.Size = new Size(89, 12);
            this.lblSupportCdma.TabIndex = 5;
            this.lblSupportCdma.Text = "是否支持CDMA：";
            this.lblSupportGprsValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSupportGprsValue.Location = new Point(138, 101);
            this.lblSupportGprsValue.Name = "lblSupportGprsValue";
            this.lblSupportGprsValue.ReadOnly = true;
            this.lblSupportGprsValue.Size = new Size(165, 21);
            this.lblSupportGprsValue.TabIndex = 6;
            this.lblSupportGprsValue.Text = " ";
            this.lblSupportGprs.AutoSize = true;
            this.lblSupportGprs.Location = new Point(43, 105);
            this.lblSupportGprs.Name = "lblSupportGprs";
            this.lblSupportGprs.Size = new Size(89, 12);
            this.lblSupportGprs.TabIndex = 5;
            this.lblSupportGprs.Text = "是否支持GPRS：";
            this.lblSupportMsgValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSupportMsgValue.Location = new Point(138, 72);
            this.lblSupportMsgValue.Name = "lblSupportMsgValue";
            this.lblSupportMsgValue.ReadOnly = true;
            this.lblSupportMsgValue.Size = new Size(165, 21);
            this.lblSupportMsgValue.TabIndex = 8;
            this.lblSupportMsgValue.Text = " ";
            this.lblSupportMsg.AutoSize = true;
            this.lblSupportMsg.Location = new Point(43, 76);
            this.lblSupportMsg.Name = "lblSupportMsg";
            this.lblSupportMsg.Size = new Size(89, 12);
            this.lblSupportMsg.TabIndex = 7;
            this.lblSupportMsg.Text = "是否支持短信：";
            this.lblTerminalVersionValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTerminalVersionValue.Location = new Point(138, 43);
            this.lblTerminalVersionValue.Name = "lblTerminalVersionValue";
            this.lblTerminalVersionValue.ReadOnly = true;
            this.lblTerminalVersionValue.Size = new Size(165, 21);
            this.lblTerminalVersionValue.TabIndex = 2;
            this.lblTerminalVersionValue.Text = " ";
            this.lblTerminalVersion.AutoSize = true;
            this.lblTerminalVersion.Location = new Point(19, 47);
            this.lblTerminalVersion.Name = "lblTerminalVersion";
            this.lblTerminalVersion.Size = new Size(113, 12);
            this.lblTerminalVersion.TabIndex = 1;
            this.lblTerminalVersion.Text = "车载终端软件版本：";
            this.lblTerminalTypeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblTerminalTypeValue.Location = new Point(138, 14);
            this.lblTerminalTypeValue.Name = "lblTerminalTypeValue";
            this.lblTerminalTypeValue.ReadOnly = true;
            this.lblTerminalTypeValue.Size = new Size(165, 21);
            this.lblTerminalTypeValue.TabIndex = 4;
            this.lblTerminalTypeValue.Text = " ";
            this.lblTerminalType.AutoSize = true;
            this.lblTerminalType.Location = new Point(43, 18);
            this.lblTerminalType.Name = "lblTerminalType";
            this.lblTerminalType.Size = new Size(89, 12);
            this.lblTerminalType.TabIndex = 3;
            this.lblTerminalType.Text = "车载终端类型：";
            this.tpOther.Controls.Add(this.lblDriverPhoneValue);
            this.tpOther.Controls.Add(this.lblDriverPhone);
            this.tpOther.Controls.Add(this.lblDriverNameValue);
            this.tpOther.Controls.Add(this.lblDriverName);
            this.tpOther.Controls.Add(this.lblSteelGradeValue);
            this.tpOther.Controls.Add(this.lblSteelGrade);
            this.tpOther.Controls.Add(this.lblSecondLinkmanTelValue);
            this.tpOther.Controls.Add(this.lblSecondLinkmanTel);
            this.tpOther.Controls.Add(this.lblSecondLinkmanValue);
            this.tpOther.Controls.Add(this.lblSecondLinkman);
            this.tpOther.Controls.Add(this.lblFirstLinkmanTelValue);
            this.tpOther.Controls.Add(this.lblCompany);
            this.tpOther.Controls.Add(this.lblCompanyValue);
            this.tpOther.Controls.Add(this.lblFirstLinkmanTel);
            this.tpOther.Controls.Add(this.lblFirstLinkmanValue);
            this.tpOther.Controls.Add(this.lblFirstLinkman);
            this.tpOther.Controls.Add(this.lblAddressValue);
            this.tpOther.Controls.Add(this.lblAddress);
            this.tpOther.Controls.Add(this.lblIdentityCardValue);
            this.tpOther.Controls.Add(this.lblIdentityCard);
            this.tpOther.Controls.Add(this.lblOwnerEmailValue);
            this.tpOther.Controls.Add(this.lblOwnerEmail);
            this.tpOther.Controls.Add(this.lblOwnerSimNumValue);
            this.tpOther.Controls.Add(this.lblOwnerSimNum);
            this.tpOther.Controls.Add(this.lblOwnerNameValue);
            this.tpOther.Controls.Add(this.lblOwnerName);
            this.tpOther.Controls.Add(this.lblCarBrandValue);
            this.tpOther.Controls.Add(this.lblCarBrand);
            this.tpOther.Location = new Point(4, 21);
            this.tpOther.Name = "tpOther";
            this.tpOther.Padding = new Padding(3);
            this.tpOther.Size = new Size(392, 478);
            this.tpOther.TabIndex = 2;
            this.tpOther.Text = "其它信息";
            this.tpOther.UseVisualStyleBackColor = true;
            this.lblDriverPhoneValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDriverPhoneValue.Location = new Point(138, 383);
            this.lblDriverPhoneValue.Name = "lblDriverPhoneValue";
            this.lblDriverPhoneValue.ReadOnly = true;
            this.lblDriverPhoneValue.Size = new Size(165, 21);
            this.lblDriverPhoneValue.TabIndex = 27;
            this.lblDriverPhoneValue.Text = " ";
            this.lblDriverPhoneValue.Visible = false;
            this.lblDriverPhone.AutoSize = true;
            this.lblDriverPhone.Location = new Point(31, 385);
            this.lblDriverPhone.Name = "lblDriverPhone";
            this.lblDriverPhone.Size = new Size(101, 12);
            this.lblDriverPhone.TabIndex = 28;
            this.lblDriverPhone.Text = "驾驶员联系方式：";
            this.lblDriverPhone.Visible = false;
            this.lblDriverNameValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDriverNameValue.Location = new Point(138, 68);
            this.lblDriverNameValue.Name = "lblDriverNameValue";
            this.lblDriverNameValue.ReadOnly = true;
            this.lblDriverNameValue.Size = new Size(165, 21);
            this.lblDriverNameValue.TabIndex = 25;
            this.lblDriverNameValue.Text = " ";
            this.lblDriverName.AutoSize = true;
            this.lblDriverName.Location = new Point(79, 73);
            this.lblDriverName.Name = "lblDriverName";
            this.lblDriverName.Size = new Size(53, 12);
            this.lblDriverName.TabIndex = 26;
            this.lblDriverName.Text = "驾驶员：";
            this.lblSteelGradeValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSteelGradeValue.Location = new Point(138, 410);
            this.lblSteelGradeValue.Name = "lblSteelGradeValue";
            this.lblSteelGradeValue.ReadOnly = true;
            this.lblSteelGradeValue.Size = new Size(165, 21);
            this.lblSteelGradeValue.TabIndex = 23;
            this.lblSteelGradeValue.Text = " ";
            this.lblSteelGradeValue.Visible = false;
            this.lblSteelGrade.AutoSize = true;
            this.lblSteelGrade.Location = new Point(67, 414);
            this.lblSteelGrade.Name = "lblSteelGrade";
            this.lblSteelGrade.Size = new Size(65, 12);
            this.lblSteelGrade.TabIndex = 24;
            this.lblSteelGrade.Text = "厂牌型号：";
            this.lblSteelGrade.Visible = false;
            this.lblSecondLinkmanTelValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSecondLinkmanTelValue.Location = new Point(138, 329);
            this.lblSecondLinkmanTelValue.Name = "lblSecondLinkmanTelValue";
            this.lblSecondLinkmanTelValue.ReadOnly = true;
            this.lblSecondLinkmanTelValue.Size = new Size(165, 21);
            this.lblSecondLinkmanTelValue.TabIndex = 15;
            this.lblSecondLinkmanTelValue.Text = " ";
            this.lblSecondLinkmanTelValue.Visible = false;
            this.lblSecondLinkmanTel.AutoSize = true;
            this.lblSecondLinkmanTel.Location = new Point(31, 333);
            this.lblSecondLinkmanTel.Name = "lblSecondLinkmanTel";
            this.lblSecondLinkmanTel.Size = new Size(101, 12);
            this.lblSecondLinkmanTel.TabIndex = 16;
            this.lblSecondLinkmanTel.Text = "第二联系人电话：";
            this.lblSecondLinkmanTel.Visible = false;
            this.lblSecondLinkmanValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSecondLinkmanValue.Location = new Point(138, 300);
            this.lblSecondLinkmanValue.Name = "lblSecondLinkmanValue";
            this.lblSecondLinkmanValue.ReadOnly = true;
            this.lblSecondLinkmanValue.Size = new Size(165, 21);
            this.lblSecondLinkmanValue.TabIndex = 14;
            this.lblSecondLinkmanValue.Text = " ";
            this.lblSecondLinkmanValue.Visible = false;
            this.lblSecondLinkman.AutoSize = true;
            this.lblSecondLinkman.Location = new Point(55, 304);
            this.lblSecondLinkman.Name = "lblSecondLinkman";
            this.lblSecondLinkman.Size = new Size(77, 12);
            this.lblSecondLinkman.TabIndex = 12;
            this.lblSecondLinkman.Text = "第二联系人：";
            this.lblSecondLinkman.Visible = false;
            this.lblFirstLinkmanTelValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblFirstLinkmanTelValue.Location = new Point(138, 271);
            this.lblFirstLinkmanTelValue.Name = "lblFirstLinkmanTelValue";
            this.lblFirstLinkmanTelValue.ReadOnly = true;
            this.lblFirstLinkmanTelValue.Size = new Size(165, 21);
            this.lblFirstLinkmanTelValue.TabIndex = 13;
            this.lblFirstLinkmanTelValue.Text = " ";
            this.lblFirstLinkmanTelValue.Visible = false;
            this.lblCompany.AutoSize = true;
            this.lblCompany.Location = new Point(67, 217);
            this.lblCompany.Name = "lblCompany";
            this.lblCompany.Size = new Size(65, 12);
            this.lblCompany.TabIndex = 17;
            this.lblCompany.Text = "工作单位：";
            this.lblCompany.Visible = false;
            this.lblCompanyValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblCompanyValue.Location = new Point(138, 213);
            this.lblCompanyValue.Name = "lblCompanyValue";
            this.lblCompanyValue.ReadOnly = true;
            this.lblCompanyValue.Size = new Size(165, 21);
            this.lblCompanyValue.TabIndex = 21;
            this.lblCompanyValue.Text = " ";
            this.lblCompanyValue.Visible = false;
            this.lblFirstLinkmanTel.AutoSize = true;
            this.lblFirstLinkmanTel.Location = new Point(31, 275);
            this.lblFirstLinkmanTel.Name = "lblFirstLinkmanTel";
            this.lblFirstLinkmanTel.Size = new Size(101, 12);
            this.lblFirstLinkmanTel.TabIndex = 22;
            this.lblFirstLinkmanTel.Text = "第一联系人电话：";
            this.lblFirstLinkmanTel.Visible = false;
            this.lblFirstLinkmanValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblFirstLinkmanValue.Location = new Point(138, 242);
            this.lblFirstLinkmanValue.Name = "lblFirstLinkmanValue";
            this.lblFirstLinkmanValue.ReadOnly = true;
            this.lblFirstLinkmanValue.Size = new Size(165, 21);
            this.lblFirstLinkmanValue.TabIndex = 20;
            this.lblFirstLinkmanValue.Text = " ";
            this.lblFirstLinkmanValue.Visible = false;
            this.lblFirstLinkman.AutoSize = true;
            this.lblFirstLinkman.Location = new Point(55, 246);
            this.lblFirstLinkman.Name = "lblFirstLinkman";
            this.lblFirstLinkman.Size = new Size(77, 12);
            this.lblFirstLinkman.TabIndex = 18;
            this.lblFirstLinkman.Text = "第一联系人：";
            this.lblFirstLinkman.Visible = false;
            this.lblAddressValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblAddressValue.Location = new Point(138, 184);
            this.lblAddressValue.Name = "lblAddressValue";
            this.lblAddressValue.ReadOnly = true;
            this.lblAddressValue.Size = new Size(165, 21);
            this.lblAddressValue.TabIndex = 19;
            this.lblAddressValue.Text = " ";
            this.lblAddressValue.Visible = false;
            this.lblAddress.AutoSize = true;
            this.lblAddress.Location = new Point(67, 188);
            this.lblAddress.Name = "lblAddress";
            this.lblAddress.Size = new Size(65, 12);
            this.lblAddress.TabIndex = 4;
            this.lblAddress.Text = "家庭住址：";
            this.lblAddress.Visible = false;
            this.lblIdentityCardValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblIdentityCardValue.Location = new Point(138, 155);
            this.lblIdentityCardValue.Name = "lblIdentityCardValue";
            this.lblIdentityCardValue.ReadOnly = true;
            this.lblIdentityCardValue.Size = new Size(165, 21);
            this.lblIdentityCardValue.TabIndex = 5;
            this.lblIdentityCardValue.Text = " ";
            this.lblIdentityCardValue.Visible = false;
            this.lblIdentityCard.AutoSize = true;
            this.lblIdentityCard.Location = new Point(55, 159);
            this.lblIdentityCard.Name = "lblIdentityCard";
            this.lblIdentityCard.Size = new Size(77, 12);
            this.lblIdentityCard.TabIndex = 3;
            this.lblIdentityCard.Text = "身份证号码：";
            this.lblIdentityCard.Visible = false;
            this.lblOwnerEmailValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblOwnerEmailValue.Location = new Point(138, 126);
            this.lblOwnerEmailValue.Name = "lblOwnerEmailValue";
            this.lblOwnerEmailValue.ReadOnly = true;
            this.lblOwnerEmailValue.Size = new Size(165, 21);
            this.lblOwnerEmailValue.TabIndex = 1;
            this.lblOwnerEmailValue.Text = " ";
            this.lblOwnerEmailValue.Visible = false;
            this.lblOwnerEmail.AutoSize = true;
            this.lblOwnerEmail.Location = new Point(61, 130);
            this.lblOwnerEmail.Name = "lblOwnerEmail";
            this.lblOwnerEmail.Size = new Size(71, 12);
            this.lblOwnerEmail.TabIndex = 2;
            this.lblOwnerEmail.Text = "车主EMAIL：";
            this.lblOwnerEmail.Visible = false;
            this.lblOwnerSimNumValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblOwnerSimNumValue.Location = new Point(138, 97);
            this.lblOwnerSimNumValue.Name = "lblOwnerSimNumValue";
            this.lblOwnerSimNumValue.ReadOnly = true;
            this.lblOwnerSimNumValue.Size = new Size(165, 21);
            this.lblOwnerSimNumValue.TabIndex = 6;
            this.lblOwnerSimNumValue.Text = " ";
            this.lblOwnerSimNum.AutoSize = true;
            this.lblOwnerSimNum.Location = new Point(43, 101);
            this.lblOwnerSimNum.Name = "lblOwnerSimNum";
            this.lblOwnerSimNum.Size = new Size(89, 12);
            this.lblOwnerSimNum.TabIndex = 10;
            this.lblOwnerSimNum.Text = "车主联系电话：";
            this.lblOwnerNameValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblOwnerNameValue.Location = new Point(138, 41);
            this.lblOwnerNameValue.Name = "lblOwnerNameValue";
            this.lblOwnerNameValue.ReadOnly = true;
            this.lblOwnerNameValue.Size = new Size(165, 21);
            this.lblOwnerNameValue.TabIndex = 11;
            this.lblOwnerNameValue.Text = " ";
            this.lblOwnerName.AutoSize = true;
            this.lblOwnerName.Location = new Point(67, 45);
            this.lblOwnerName.Name = "lblOwnerName";
            this.lblOwnerName.Size = new Size(65, 12);
            this.lblOwnerName.TabIndex = 9;
            this.lblOwnerName.Text = "车主姓名：";
            this.lblCarBrandValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblCarBrandValue.Location = new Point(138, 14);
            this.lblCarBrandValue.Name = "lblCarBrandValue";
            this.lblCarBrandValue.ReadOnly = true;
            this.lblCarBrandValue.Size = new Size(165, 21);
            this.lblCarBrandValue.TabIndex = 7;
            this.lblCarBrandValue.Text = " ";
            this.lblCarBrand.AutoSize = true;
            this.lblCarBrand.Location = new Point(67, 18);
            this.lblCarBrand.Name = "lblCarBrand";
            this.lblCarBrand.Size = new Size(65, 12);
            this.lblCarBrand.TabIndex = 8;
            this.lblCarBrand.Text = "车辆品牌：";
            this.tpRemark.Controls.Add(this.lblRemarkValue);
            this.tpRemark.Controls.Add(this.lblRemark);
            this.tpRemark.Location = new Point(4, 21);
            this.tpRemark.Name = "tpRemark";
            this.tpRemark.Padding = new Padding(3);
            this.tpRemark.Size = new Size(392, 478);
            this.tpRemark.TabIndex = 3;
            this.tpRemark.Text = "备注信息";
            this.tpRemark.UseVisualStyleBackColor = true;
            this.lblRemarkValue.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblRemarkValue.Location = new Point(138, 14);
            this.lblRemarkValue.Multiline = true;
            this.lblRemarkValue.Name = "lblRemarkValue";
            this.lblRemarkValue.ReadOnly = true;
            this.lblRemarkValue.Size = new Size(248, 70);
            this.lblRemarkValue.TabIndex = 12;
            this.lblRemarkValue.Text = " ";
            this.lblRemark.AutoSize = true;
            this.lblRemark.Location = new Point(67, 18);
            this.lblRemark.Name = "lblRemark";
            this.lblRemark.Size = new Size(65, 12);
            this.lblRemark.TabIndex = 13;
            this.lblRemark.Text = "备注信息：";
            this.tpRegion.Controls.Add(this.txtCEOContact);
            this.tpRegion.Controls.Add(this.lblCEOContact);
            this.tpRegion.Controls.Add(this.txtCEOName);
            this.tpRegion.Controls.Add(this.lblCEOName);
            this.tpRegion.Controls.Add(this.txtIssuingAgency);
            this.tpRegion.Controls.Add(this.lblIssuingAgency);
            this.tpRegion.Controls.Add(this.txtRoadTransportID);
            this.tpRegion.Controls.Add(this.lblRoadTransportID);
            this.tpRegion.Controls.Add(this.txtOperateScope);
            this.tpRegion.Controls.Add(this.lblOperateScope);
            this.tpRegion.Controls.Add(this.txtRegion);
            this.tpRegion.Controls.Add(this.lblRegion);
            this.tpRegion.Controls.Add(this.txtContactMode);
            this.tpRegion.Controls.Add(this.lblContactMode);
            this.tpRegion.Controls.Add(this.txtContactName);
            this.tpRegion.Controls.Add(this.lblContactName);
            this.tpRegion.Controls.Add(this.txtAreaName);
            this.tpRegion.Controls.Add(this.lblAreaName);
            this.tpRegion.Location = new Point(4, 21);
            this.tpRegion.Name = "tpRegion";
            this.tpRegion.Size = new Size(392, 478);
            this.tpRegion.TabIndex = 4;
            this.tpRegion.Text = "基本信息";
            this.tpRegion.UseVisualStyleBackColor = true;
            this.txtCEOContact.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCEOContact.Location = new Point(164, 242);
            this.txtCEOContact.Name = "txtCEOContact";
            this.txtCEOContact.ReadOnly = true;
            this.txtCEOContact.Size = new Size(165, 21);
            this.txtCEOContact.TabIndex = 38;
            this.txtCEOContact.Tag = "CEOContact";
            this.txtCEOContact.Text = " ";
            this.lblCEOContact.AutoSize = true;
            this.lblCEOContact.Location = new Point(45, 245);
            this.lblCEOContact.Name = "lblCEOContact";
            this.lblCEOContact.Size = new Size(113, 12);
            this.lblCEOContact.TabIndex = 39;
            this.lblCEOContact.Text = "法人代表联系方式：";
            this.txtCEOName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCEOName.Location = new Point(164, 213);
            this.txtCEOName.Name = "txtCEOName";
            this.txtCEOName.ReadOnly = true;
            this.txtCEOName.Size = new Size(165, 21);
            this.txtCEOName.TabIndex = 40;
            this.txtCEOName.Tag = "CEOName";
            this.txtCEOName.Text = " ";
            this.lblCEOName.AutoSize = true;
            this.lblCEOName.Location = new Point(57, 215);
            this.lblCEOName.Name = "lblCEOName";
            this.lblCEOName.Size = new Size(101, 12);
            this.lblCEOName.TabIndex = 35;
            this.lblCEOName.Text = "法定代表人名称：";
            this.txtIssuingAgency.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtIssuingAgency.Location = new Point(164, 184);
            this.txtIssuingAgency.Name = "txtIssuingAgency";
            this.txtIssuingAgency.ReadOnly = true;
            this.txtIssuingAgency.Size = new Size(165, 21);
            this.txtIssuingAgency.TabIndex = 21;
            this.txtIssuingAgency.Tag = "IssuingAgency";
            this.txtIssuingAgency.Text = " ";
            this.lblIssuingAgency.AutoSize = true;
            this.lblIssuingAgency.Location = new Point(93, 186);
            this.lblIssuingAgency.Name = "lblIssuingAgency";
            this.lblIssuingAgency.Size = new Size(65, 12);
            this.lblIssuingAgency.TabIndex = 22;
            this.lblIssuingAgency.Text = "核发机构：";
            this.txtRoadTransportID.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRoadTransportID.Location = new Point(164, 155);
            this.txtRoadTransportID.Name = "txtRoadTransportID";
            this.txtRoadTransportID.ReadOnly = true;
            this.txtRoadTransportID.Size = new Size(165, 21);
            this.txtRoadTransportID.TabIndex = 23;
            this.txtRoadTransportID.Tag = "RoadTransportID";
            this.txtRoadTransportID.Text = " ";
            this.lblRoadTransportID.AutoSize = true;
            this.lblRoadTransportID.Location = new Point(45, 157);
            this.lblRoadTransportID.Name = "lblRoadTransportID";
            this.lblRoadTransportID.Size = new Size(113, 12);
            this.lblRoadTransportID.TabIndex = 18;
            this.lblRoadTransportID.Text = "道路运输许可证号：";
            this.txtOperateScope.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtOperateScope.Location = new Point(164, 126);
            this.txtOperateScope.Name = "txtOperateScope";
            this.txtOperateScope.ReadOnly = true;
            this.txtOperateScope.Size = new Size(165, 21);
            this.txtOperateScope.TabIndex = 19;
            this.txtOperateScope.Tag = "OperateScope";
            this.txtOperateScope.Text = " ";
            this.lblOperateScope.AutoSize = true;
            this.lblOperateScope.Location = new Point(93, 130);
            this.lblOperateScope.Name = "lblOperateScope";
            this.lblOperateScope.Size = new Size(65, 12);
            this.lblOperateScope.TabIndex = 20;
            this.lblOperateScope.Text = "经营范围：";
            this.txtRegion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRegion.Location = new Point(164, 97);
            this.txtRegion.Name = "txtRegion";
            this.txtRegion.ReadOnly = true;
            this.txtRegion.Size = new Size(165, 21);
            this.txtRegion.TabIndex = 24;
            this.txtRegion.Tag = "Region";
            this.txtRegion.Text = " ";
            this.lblRegion.AutoSize = true;
            this.lblRegion.Location = new Point(93, 101);
            this.lblRegion.Name = "lblRegion";
            this.lblRegion.Size = new Size(65, 12);
            this.lblRegion.TabIndex = 28;
            this.lblRegion.Text = "所属地域：";
            this.txtContactMode.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtContactMode.Location = new Point(164, 68);
            this.txtContactMode.Name = "txtContactMode";
            this.txtContactMode.ReadOnly = true;
            this.txtContactMode.Size = new Size(165, 21);
            this.txtContactMode.TabIndex = 29;
            this.txtContactMode.Tag = "ContactMode";
            this.txtContactMode.Text = " ";
            this.lblContactMode.AutoSize = true;
            this.lblContactMode.Location = new Point(93, 72);
            this.lblContactMode.Name = "lblContactMode";
            this.lblContactMode.Size = new Size(65, 12);
            this.lblContactMode.TabIndex = 30;
            this.lblContactMode.Text = "联系方式：";
            this.txtContactName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtContactName.Location = new Point(164, 39);
            this.txtContactName.Name = "txtContactName";
            this.txtContactName.ReadOnly = true;
            this.txtContactName.Size = new Size(165, 21);
            this.txtContactName.TabIndex = 25;
            this.txtContactName.Tag = "ContactName";
            this.txtContactName.Text = " ";
            this.lblContactName.AutoSize = true;
            this.lblContactName.Location = new Point(93, 43);
            this.lblContactName.Name = "lblContactName";
            this.lblContactName.Size = new Size(59, 12);
            this.lblContactName.TabIndex = 26;
            this.lblContactName.Text = " 联系人：";
            this.txtAreaName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtAreaName.Location = new Point(164, 10);
            this.txtAreaName.Name = "txtAreaName";
            this.txtAreaName.ReadOnly = true;
            this.txtAreaName.Size = new Size(165, 21);
            this.txtAreaName.TabIndex = 27;
            this.txtAreaName.Tag = "AreaName";
            this.txtAreaName.Text = " ";
            this.lblAreaName.AutoSize = true;
            this.lblAreaName.Location = new Point(93, 14);
            this.lblAreaName.Name = "lblAreaName";
            this.lblAreaName.Size = new Size(65, 12);
            this.lblAreaName.TabIndex = 31;
            this.lblAreaName.Text = "区域名称：";
            this.pnlBtn.Controls.Add(this.btnClose);
            this.pnlBtn.Dock = DockStyle.Bottom;
            this.pnlBtn.Location = new Point(5, 508);
            this.pnlBtn.Name = "pnlBtn";
            this.pnlBtn.Size = new Size(400, 30);
            this.pnlBtn.TabIndex = 1;
            this.btnClose.DialogResult =  System.Windows.Forms.DialogResult.Cancel;
            this.btnClose.Location = new Point(325, 5);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new Size(75, 23);
            this.btnClose.TabIndex = 5;
            this.btnClose.Text = "关闭(&C)";
            this.btnClose.UseVisualStyleBackColor = true;
            this.btnClose.Click += new EventHandler(this.btnClose_Click);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            base.CancelButton = this.btnClose;
            base.ClientSize = new Size(410, 543);
            base.Controls.Add(this.pnlAttribute);
            base.Controls.Add(this.pnlBtn);
            base.Icon = (Icon)resources.GetObject("$this.Icon");
            base.Name = "itmCarDetail";
            base.Padding = new Padding(5);
            base.StartPosition = FormStartPosition.CenterParent;
            this.Text = "车辆详细信息";
            base.Load += new EventHandler(this.itmCarDetail_Load);
            this.pnlAttribute.ResumeLayout(false);
            this.tcAttribute.ResumeLayout(false);
            this.tpBasic.ResumeLayout(false);
            this.tpBasic.PerformLayout();
            this.tpTerminal.ResumeLayout(false);
            this.tpTerminal.PerformLayout();
            this.tpOther.ResumeLayout(false);
            this.tpOther.PerformLayout();
            this.tpRemark.ResumeLayout(false);
            this.tpRemark.PerformLayout();
            this.tpRegion.ResumeLayout(false);
            this.tpRegion.PerformLayout();
            this.pnlBtn.ResumeLayout(false);
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private Label lblAddress;
        private TextBox lblAddressValue;
        private Label lblAheadDate;
        private TextBox lblAheadDateValue;
        private Label lblArea;
        private Label lblAreaName;
        private TextBox lblAreaValue;
        private Label lblCarBrand;
        private TextBox lblCarBrandValue;
        private Label lblCarId;
        private TextBox lblCarIdValue;
        private Label lblCarNum;
        private TextBox lblCarNumValue;
        private Label lblCarState;
        private Label lblCarType;
        private TextBox lblCarTypeValue;
        private Label lblCEOContact;
        private Label lblCEOName;
        private Label lblColor;
        private TextBox lblColorValue;
        private Label lblCompany;
        private TextBox lblCompanyValue;
        private Label lblContactMode;
        private Label lblContactName;
        private Label lblDriverName;
        private TextBox lblDriverNameValue;
        private Label lblDriverPhone;
        private TextBox lblDriverPhoneValue;
        private Label lblFirstLinkman;
        private Label lblFirstLinkmanTel;
        private TextBox lblFirstLinkmanTelValue;
        private TextBox lblFirstLinkmanValue;
        private Label lblIdentityCard;
        private TextBox lblIdentityCardValue;
        private Label lblIssuingAgency;
        private Label lblOperateScope;
        private Label lblOperateTypeName;
        private Label lblOwnerEmail;
        private TextBox lblOwnerEmailValue;
        private Label lblOwnerName;
        private TextBox lblOwnerNameValue;
        private Label lblOwnerSimNum;
        private TextBox lblOwnerSimNumValue;
        private Label lblPlateColor;
        private Label lblRegion;
        private Label lblRegistrationTime;
        private TextBox lblRegistrationTimeValue;
        private Label lblRemark;
        private TextBox lblRemarkValue;
        private Label lblRoadTransportID;
        private Label lblSecondLinkman;
        private Label lblSecondLinkmanTel;
        private TextBox lblSecondLinkmanTelValue;
        private TextBox lblSecondLinkmanValue;
        private Label lblServerEndTime;
        private TextBox lblServerEndTimeValue;
        private Label lblServerStartTime;
        private TextBox lblServerStartTimeValue;
        private Label lblSimEndTime;
        private TextBox lblSimEndTimeValue;
        private Label lblSimNum;
        private TextBox lblSimNumValue;
        private Label lblSimPassword;
        private TextBox lblSimPasswordValue;
        private Label lblSimStartTime;
        private TextBox lblSimStartTimeValue;
        private Label lblSteelGrade;
        private TextBox lblSteelGradeValue;
        private Label lblSupportCdma;
        private TextBox lblSupportCdmaValue;
        private Label lblSupportGprs;
        private TextBox lblSupportGprsValue;
        private Label lblSupportMsg;
        private TextBox lblSupportMsgValue;
        private Label lblTerminalType;
        private TextBox lblTerminalTypeValue;
        private Label lblTerminalVersion;
        private TextBox lblTerminalVersionValue;
        private Label lblTermSerial;
        private Panel pnlAttribute;
        private Panel pnlBtn;
        private TabControl tcAttribute;
        private TabPage tpBasic;
        private TabPage tpOther;
        private TabPage tpRegion;
        private TabPage tpRemark;
        private TabPage tpTerminal;
        private TextBox txtAreaName;
        private TextBox txtCarState;
        private TextBox txtCEOContact;
        private TextBox txtCEOName;
        private TextBox txtContactMode;
        private TextBox txtContactName;
        private TextBox txtIssuingAgency;
        private TextBox txtOperateScope;
        private TextBox txtOperateTypeName;
        private TextBox txtPlateColor;
        private TextBox txtRegion;
        private TextBox txtRoadTransportID;
        private TextBox txtTermSerial;
    }
}