namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class itmCarBeBackTime
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(itmCarBeBackTime));
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.grpArea = new GroupBox();
            this.dgvArea = new DataGridViewEx();
            this.regionName = new DataGridViewTextBoxColumn();
            this.Choose = new DataGridViewCheckBoxColumn();
            this.beginTime = new DataGridViewTextBoxColumn();
            this.endTime = new DataGridViewTextBoxColumn();
            this.regionId = new DataGridViewTextBoxColumn();
            this.regionDot = new DataGridViewTextBoxColumn();
            this.pnlFilter = new Panel();
            this.comboBoxLines = new ComboBox();
            this.toolStrip1 = new ToolStrip();
            this.tsBtnFilter = new ToolStripButton();
            this.lbLine = new Label();
            this.pnlWait = new Panel();
            this.pbPicWait = new PictureBox();
            this.lblWaitText = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpArea.SuspendLayout();
            ((ISupportInitialize) this.dgvArea).BeginInit();
            this.pnlFilter.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.pnlWait.SuspendLayout();
            ((ISupportInitialize) this.pbPicWait).BeginInit();
            base.SuspendLayout();
            base.grpCar.Size = new Size(366, 116);
            base.pnlBtn.Controls.Add(this.pnlWait);
            base.pnlBtn.Location = new Point(5, 323);
            base.pnlBtn.Size = new Size(366, 28);
            base.pnlBtn.Controls.SetChildIndex(base.btnOK, 0);
            base.pnlBtn.Controls.SetChildIndex(base.btnCancel, 0);
            base.pnlBtn.Controls.SetChildIndex(this.pnlWait, 0);
            this.grpArea.Controls.Add(this.dgvArea);
            this.grpArea.Controls.Add(this.pnlFilter);
            this.grpArea.Dock = DockStyle.Top;
            this.grpArea.Location = new Point(5, 121);
            this.grpArea.Name = "grpArea";
            this.grpArea.Size = new Size(366, 202);
            this.grpArea.TabIndex = 11;
            this.grpArea.TabStop = false;
            this.grpArea.Text = "预设区域";
            this.dgvArea.AllowUserToAddRows = false;
            this.dgvArea.AllowUserToDeleteRows = false;
            this.dgvArea.AllowUserToResizeColumns = false;
            this.dgvArea.AllowUserToResizeRows = false;
            this.dgvArea.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
            this.dgvArea.BackgroundColor = SystemColors.ControlLightLight;
            this.dgvArea.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvArea.Columns.AddRange(new DataGridViewColumn[] { this.regionName, this.Choose, this.beginTime, this.endTime, this.regionId, this.regionDot });
            this.dgvArea.Dock = DockStyle.Fill;
            this.dgvArea.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.dgvArea.Location = new Point(3, 43);
            this.dgvArea.Name = "dgvArea";
            this.dgvArea.NotMultiSelectedColumnName = (List<string>)resources.GetObject("dgvArea.NotMultiSelectedColumnName");
            this.dgvArea.RowHeadersVisible = false;
            this.dgvArea.RowTemplate.Height = 20;
            this.dgvArea.SelectionMode = DataGridViewSelectionMode.CellSelect;
            this.dgvArea.Size = new Size(360, 156);
            this.dgvArea.TabIndex = 0;
            this.dgvArea.CellValueChanged += new DataGridViewCellEventHandler(this.dgvArea_CellValueChanged);
            this.dgvArea.CellMouseUp += new DataGridViewCellMouseEventHandler(this.dgvArea_CellMouseUp);
            this.dgvArea.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvArea_CellDoubleClick);
            this.regionName.DataPropertyName = "regionName";
            style.BackColor = Color.FromArgb(192, 192, 255);
            this.regionName.DefaultCellStyle = style;
            this.regionName.Frozen = true;
            this.regionName.HeaderText = "区域名称";
            this.regionName.MinimumWidth = 60;
            this.regionName.Name = "regionName";
            this.regionName.ReadOnly = true;
            this.regionName.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.regionName.Width = 60;
            this.Choose.DataPropertyName = "Choose";
            this.Choose.FalseValue = "False";
            this.Choose.HeaderText = "选择";
            this.Choose.MinimumWidth = 45;
            this.Choose.Name = "Choose";
            this.Choose.TrueValue = "True";
            this.Choose.Width = 45;
            this.beginTime.DataPropertyName = "beginTime";
            this.beginTime.HeaderText = "起始时间";
            this.beginTime.MaxInputLength = 19;
            this.beginTime.MinimumWidth = 60;
            this.beginTime.Name = "beginTime";
            this.beginTime.ReadOnly = true;
            this.beginTime.Resizable = DataGridViewTriState.False;
            this.beginTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.beginTime.Width = 60;
            this.endTime.DataPropertyName = "endTime";
            this.endTime.HeaderText = "终止时间";
            this.endTime.MaxInputLength = 19;
            this.endTime.MinimumWidth = 60;
            this.endTime.Name = "endTime";
            this.endTime.ReadOnly = true;
            this.endTime.Resizable = DataGridViewTriState.False;
            this.endTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.endTime.Width = 60;
            this.regionId.DataPropertyName = "regionId";
            this.regionId.HeaderText = "区域ID";
            this.regionId.Name = "regionId";
            this.regionId.Visible = false;
            this.regionId.Width = 66;
            this.regionDot.DataPropertyName = "regionDot";
            this.regionDot.HeaderText = "区域点坐标集";
            this.regionDot.Name = "regionDot";
            this.regionDot.Visible = false;
            this.regionDot.Width = 102;
            this.pnlFilter.Controls.Add(this.comboBoxLines);
            this.pnlFilter.Controls.Add(this.toolStrip1);
            this.pnlFilter.Controls.Add(this.lbLine);
            this.pnlFilter.Dock = DockStyle.Top;
            this.pnlFilter.Location = new Point(3, 17);
            this.pnlFilter.Name = "pnlFilter";
            this.pnlFilter.Size = new Size(360, 26);
            this.pnlFilter.TabIndex = 3;
            this.comboBoxLines.DisplayMember = "PathgroupName";
            this.comboBoxLines.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBoxLines.FormattingEnabled = true;
            this.comboBoxLines.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.comboBoxLines.Location = new Point(123, 3);
            this.comboBoxLines.Name = "comboBoxLines";
            this.comboBoxLines.Size = new Size(157, 20);
            this.comboBoxLines.TabIndex = 3;
            this.comboBoxLines.Tag = "999";
            this.comboBoxLines.ValueMember = "PathgroupID";
            this.toolStrip1.Dock = DockStyle.None;
            this.toolStrip1.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStrip1.Items.AddRange(new ToolStripItem[] { this.tsBtnFilter });
            this.toolStrip1.Location = new Point(285, 1);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new Size(26, 25);
            this.toolStrip1.TabIndex = 2;
            this.toolStrip1.Text = "toolStrip1";
            this.tsBtnFilter.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.tsBtnFilter.Image = Resources.find;
            this.tsBtnFilter.ImageTransparentColor = Color.Magenta;
            this.tsBtnFilter.Name = "tsBtnFilter";
            this.tsBtnFilter.Size = new Size(23, 22);
            this.tsBtnFilter.Text = "搜索 ";
            this.tsBtnFilter.Click += new EventHandler(this.tsBtnFilter_Click);
            this.lbLine.AutoSize = true;
            this.lbLine.Location = new Point(23, 7);
            this.lbLine.Name = "lbLine";
            this.lbLine.Size = new Size(89, 12);
            this.lbLine.TabIndex = 1;
            this.lbLine.Tag = "999";
            this.lbLine.Text = "区域分组名称：";
            this.pnlWait.Controls.Add(this.pbPicWait);
            this.pnlWait.Controls.Add(this.lblWaitText);
            this.pnlWait.Location = new Point(5, 4);
            this.pnlWait.Name = "pnlWait";
            this.pnlWait.Size = new Size(129, 22);
            this.pnlWait.TabIndex = 42;
            this.pnlWait.Tag = "9999";
            this.pbPicWait.BackColor = Color.Transparent;
            this.pbPicWait.Image = Resources.loading;
            this.pbPicWait.InitialImage = null;
            this.pbPicWait.Location = new Point(3, 3);
            this.pbPicWait.Name = "pbPicWait";
            this.pbPicWait.Size = new Size(16, 16);
            this.pbPicWait.TabIndex = 11;
            this.pbPicWait.TabStop = false;
            this.pbPicWait.Tag = "9999";
            this.pbPicWait.Visible = false;
            this.lblWaitText.AutoSize = true;
            this.lblWaitText.Location = new Point(22, 5);
            this.lblWaitText.Name = "lblWaitText";
            this.lblWaitText.Size = new Size(89, 12);
            this.lblWaitText.TabIndex = 9;
            this.lblWaitText.Text = "正在执行中....";
            this.lblWaitText.Visible = false;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(376, 356);
            base.Controls.Add(this.grpArea);
            base.Name = "itmCarBeBackTime";
            this.Text = "设置集中停放车辆";
            base.Load += new EventHandler(this.itmCarBeBackTime_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpArea, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpArea.ResumeLayout(false);
            ((ISupportInitialize) this.dgvArea).EndInit();
            this.pnlFilter.ResumeLayout(false);
            this.pnlFilter.PerformLayout();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.pnlWait.ResumeLayout(false);
            this.pnlWait.PerformLayout();
            ((ISupportInitialize) this.pbPicWait).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private DataGridViewTextBoxColumn beginTime;
        private DataGridViewCheckBoxColumn Choose;
        private ComboBox comboBoxLines;
        private DataGridViewEx dgvArea;
        private DataGridViewTextBoxColumn endTime;
        private GroupBox grpArea;
        private Label lbLine;
        private Label lblWaitText;
        private int ParamType;
        private PictureBox pbPicWait;
        private Panel pnlFilter;
        private Panel pnlWait;
        private DataGridViewTextBoxColumn regionDot;
        private DataGridViewTextBoxColumn regionId;
        private DataGridViewTextBoxColumn regionName;
        private ToolStrip toolStrip1;
        private ToolStripButton tsBtnFilter;
    }
}