namespace Client
{
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;

    partial class itmCarLBSParam
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            DataGridViewCellStyle style3 = new DataGridViewCellStyle();
            DataGridViewCellStyle style4 = new DataGridViewCellStyle();
            DataGridViewCellStyle style5 = new DataGridViewCellStyle();
            DataGridViewCellStyle style6 = new DataGridViewCellStyle();
            DataGridViewCellStyle style7 = new DataGridViewCellStyle();
            DataGridViewCellStyle style8 = new DataGridViewCellStyle();
            DataGridViewCellStyle style9 = new DataGridViewCellStyle();
            DataGridViewCellStyle style10 = new DataGridViewCellStyle();
            DataGridViewCellStyle style11 = new DataGridViewCellStyle();
            DataGridViewCellStyle style12 = new DataGridViewCellStyle();
            DataGridViewCellStyle style13 = new DataGridViewCellStyle();
            DataGridViewCellStyle style14 = new DataGridViewCellStyle();
            DataGridViewCellStyle style15 = new DataGridViewCellStyle();
            DataGridViewCellStyle style16 = new DataGridViewCellStyle();
            DataGridViewCellStyle style17 = new DataGridViewCellStyle();
            DataGridViewCellStyle style18 = new DataGridViewCellStyle();
            this.grpParam = new GroupBox();
            this.lblUnit = new Label();
            this.label1 = new Label();
            this.m_dgvTimeValue = new DataGridView();
            this.Column1 = new DataGridViewTextBoxColumn();
            this.Column2 = new DataGridViewTextBoxColumn();
            this.Column3 = new DataGridViewTextBoxColumn();
            this.Column4 = new DataGridViewTextBoxColumn();
            this.Column5 = new DataGridViewTextBoxColumn();
            this.Column6 = new DataGridViewTextBoxColumn();
            this.Column7 = new DataGridViewTextBoxColumn();
            this.Column8 = new DataGridViewTextBoxColumn();
            this.Column9 = new DataGridViewTextBoxColumn();
            this.Column10 = new DataGridViewTextBoxColumn();
            this.Column11 = new DataGridViewTextBoxColumn();
            this.Column12 = new DataGridViewTextBoxColumn();
            this.Column13 = new DataGridViewTextBoxColumn();
            this.Column14 = new DataGridViewTextBoxColumn();
            this.Column15 = new DataGridViewTextBoxColumn();
            this.m_dgvUnit = new DataGridView();
            this.Column16 = new DataGridViewTextBoxColumn();
            this.lblMonday = new Label();
            this.lblTuesday = new Label();
            this.lblWednesday = new Label();
            this.lblThursday = new Label();
            this.lblFriday = new Label();
            this.lblSaturday = new Label();
            this.lblSunday = new Label();
            this.lblColor = new Label();
            this.lblText = new Label();
            this.lblStartTime = new Label();
            this.dtpStartTime = new DateTimePicker();
            this.lblEndTime = new Label();
            this.dtpEndTime = new DateTimePicker();
            this.btnClear = new Button();
            this.btnResume = new Button();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpParam.SuspendLayout();
            ((ISupportInitialize) this.m_dgvTimeValue).BeginInit();
            ((ISupportInitialize) this.m_dgvUnit).BeginInit();
            base.SuspendLayout();
            base.grpCar.Size = new Size(596, 116);
            base.pnlBtn.Controls.Add(this.btnResume);
            base.pnlBtn.Controls.Add(this.btnClear);
            base.pnlBtn.Location = new Point(5, 621);
            base.pnlBtn.Size = new Size(596, 28);
            base.pnlBtn.Controls.SetChildIndex(this.btnClear, 0);
            base.pnlBtn.Controls.SetChildIndex(this.btnResume, 0);
            base.pnlBtn.Controls.SetChildIndex(base.btnOK, 0);
            base.pnlBtn.Controls.SetChildIndex(base.btnCancel, 0);
            base.btnCancel.Location = new Point(391, 5);
            base.btnOK.Location = new Point(304, 5);
            this.grpParam.Controls.Add(this.lblUnit);
            this.grpParam.Controls.Add(this.label1);
            this.grpParam.Controls.Add(this.m_dgvTimeValue);
            this.grpParam.Controls.Add(this.m_dgvUnit);
            this.grpParam.Controls.Add(this.lblMonday);
            this.grpParam.Controls.Add(this.lblTuesday);
            this.grpParam.Controls.Add(this.lblWednesday);
            this.grpParam.Controls.Add(this.lblThursday);
            this.grpParam.Controls.Add(this.lblFriday);
            this.grpParam.Controls.Add(this.lblSaturday);
            this.grpParam.Controls.Add(this.lblSunday);
            this.grpParam.Controls.Add(this.lblColor);
            this.grpParam.Controls.Add(this.lblText);
            this.grpParam.Controls.Add(this.lblStartTime);
            this.grpParam.Controls.Add(this.dtpStartTime);
            this.grpParam.Controls.Add(this.lblEndTime);
            this.grpParam.Controls.Add(this.dtpEndTime);
            this.grpParam.Dock = DockStyle.Top;
            this.grpParam.Location = new Point(5, 121);
            this.grpParam.Name = "grpParam";
            this.grpParam.Size = new Size(596, 500);
            this.grpParam.TabIndex = 11;
            this.grpParam.TabStop = false;
            this.grpParam.Text = "LBS参数";
            this.lblUnit.AutoSize = true;
            this.lblUnit.Location = new Point(-117, -175);
            this.lblUnit.Name = "lblUnit";
            this.lblUnit.Size = new Size(65, 12);
            this.lblUnit.TabIndex = 25;
            this.lblUnit.Text = "单位(小时)";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(20, 14);
            this.label1.Name = "label1";
            this.label1.Size = new Size(65, 12);
            this.label1.TabIndex = 28;
            this.label1.Text = "单位(小时)";
            this.m_dgvTimeValue.AllowUserToAddRows = false;
            this.m_dgvTimeValue.AllowUserToDeleteRows = false;
            this.m_dgvTimeValue.AllowUserToResizeColumns = false;
            this.m_dgvTimeValue.AllowUserToResizeRows = false;
            this.m_dgvTimeValue.BackgroundColor = Color.White;
            this.m_dgvTimeValue.CellBorderStyle = DataGridViewCellBorderStyle.None;
            this.m_dgvTimeValue.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.m_dgvTimeValue.ColumnHeadersVisible = false;
            this.m_dgvTimeValue.Columns.AddRange(new DataGridViewColumn[] { this.Column1, this.Column2, this.Column3, this.Column4, this.Column5, this.Column6, this.Column7, this.Column8, this.Column9, this.Column10, this.Column11, this.Column12, this.Column13, this.Column14, this.Column15 });
            this.m_dgvTimeValue.Location = new Point(52, 29);
            this.m_dgvTimeValue.Name = "m_dgvTimeValue";
            this.m_dgvTimeValue.ReadOnly = true;
            this.m_dgvTimeValue.RowHeadersVisible = false;
            this.m_dgvTimeValue.RowHeadersWidth = 20;
            this.m_dgvTimeValue.RowTemplate.Height = 4;
            this.m_dgvTimeValue.RowTemplate.ReadOnly = true;
            this.m_dgvTimeValue.RowTemplate.Resizable = DataGridViewTriState.False;
            this.m_dgvTimeValue.ScrollBars = ScrollBars.None;
            this.m_dgvTimeValue.Size = new Size(509, 389);
            this.m_dgvTimeValue.TabIndex = 26;
            this.m_dgvTimeValue.CellMouseUp += new DataGridViewCellMouseEventHandler(this.m_dgvTimeValue_CellMouseUp);
            this.m_dgvTimeValue.CellMouseDown += new DataGridViewCellMouseEventHandler(this.m_dgvTimeValue_CellMouseDown);
            this.m_dgvTimeValue.CellMouseMove += new DataGridViewCellMouseEventHandler(this.m_dgvTimeValue_CellMouseMove);
            this.m_dgvTimeValue.MouseUp += new MouseEventHandler(this.m_dgvTimeValue_MouseUp);
            this.m_dgvTimeValue.CellMouseEnter += new DataGridViewCellEventHandler(this.m_dgvTimeValue_CellMouseEnter);
            this.m_dgvTimeValue.CellClick += new DataGridViewCellEventHandler(this.m_dgvTimeValue_CellClick);
            this.m_dgvTimeValue.CellEnter += new DataGridViewCellEventHandler(this.m_dgvTimeValue_CellMouseEnter);
            this.Column1.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column1.DataPropertyName = "Column1";
            style.Alignment = DataGridViewContentAlignment.TopRight;
            style.BackColor = Color.White;
            style.SelectionBackColor = Color.White;
            this.Column1.DefaultCellStyle = style;
            this.Column1.FillWeight = 36.0159f;
            this.Column1.HeaderText = "1";
            this.Column1.Name = "Column1";
            this.Column1.ReadOnly = true;
            this.Column1.Resizable = DataGridViewTriState.False;
            this.Column1.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column2.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column2.DataPropertyName = "Column2";
            style2.BackColor = Color.Lime;
            style2.SelectionBackColor = Color.Lime;
            this.Column2.DefaultCellStyle = style2;
            this.Column2.FillWeight = 36.0159f;
            this.Column2.HeaderText = "2";
            this.Column2.Name = "Column2";
            this.Column2.ReadOnly = true;
            this.Column2.Resizable = DataGridViewTriState.False;
            this.Column2.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column3.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column3.DataPropertyName = "Column3";
            style3.BackColor = Color.White;
            style3.SelectionBackColor = Color.White;
            this.Column3.DefaultCellStyle = style3;
            this.Column3.FillWeight = 36.0159f;
            this.Column3.HeaderText = "3";
            this.Column3.Name = "Column3";
            this.Column3.ReadOnly = true;
            this.Column3.Resizable = DataGridViewTriState.False;
            this.Column3.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column4.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column4.DataPropertyName = "Column4";
            style4.BackColor = Color.Lime;
            style4.SelectionBackColor = Color.Lime;
            this.Column4.DefaultCellStyle = style4;
            this.Column4.FillWeight = 36.0159f;
            this.Column4.HeaderText = "4";
            this.Column4.Name = "Column4";
            this.Column4.ReadOnly = true;
            this.Column4.Resizable = DataGridViewTriState.False;
            this.Column4.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column5.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column5.DataPropertyName = "Column5";
            style5.BackColor = Color.White;
            style5.SelectionBackColor = Color.White;
            this.Column5.DefaultCellStyle = style5;
            this.Column5.FillWeight = 36.0159f;
            this.Column5.HeaderText = "5";
            this.Column5.Name = "Column5";
            this.Column5.ReadOnly = true;
            this.Column5.Resizable = DataGridViewTriState.False;
            this.Column5.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column6.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column6.DataPropertyName = "Column6";
            style6.BackColor = Color.Lime;
            style6.SelectionBackColor = Color.Lime;
            this.Column6.DefaultCellStyle = style6;
            this.Column6.FillWeight = 36.0159f;
            this.Column6.HeaderText = "6";
            this.Column6.Name = "Column6";
            this.Column6.ReadOnly = true;
            this.Column6.Resizable = DataGridViewTriState.False;
            this.Column6.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column7.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column7.DataPropertyName = "Column7";
            style7.BackColor = Color.White;
            style7.SelectionBackColor = Color.White;
            this.Column7.DefaultCellStyle = style7;
            this.Column7.FillWeight = 36.0159f;
            this.Column7.HeaderText = "7";
            this.Column7.Name = "Column7";
            this.Column7.ReadOnly = true;
            this.Column7.Resizable = DataGridViewTriState.False;
            this.Column7.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column8.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column8.DataPropertyName = "Column8";
            style8.BackColor = Color.Lime;
            style8.SelectionBackColor = Color.Lime;
            this.Column8.DefaultCellStyle = style8;
            this.Column8.FillWeight = 36.0159f;
            this.Column8.HeaderText = "8";
            this.Column8.Name = "Column8";
            this.Column8.ReadOnly = true;
            this.Column8.Resizable = DataGridViewTriState.False;
            this.Column8.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column9.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column9.DataPropertyName = "Column9";
            style9.BackColor = Color.White;
            style9.SelectionBackColor = Color.White;
            this.Column9.DefaultCellStyle = style9;
            this.Column9.FillWeight = 36.0159f;
            this.Column9.HeaderText = "9";
            this.Column9.Name = "Column9";
            this.Column9.ReadOnly = true;
            this.Column9.Resizable = DataGridViewTriState.False;
            this.Column9.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column10.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column10.DataPropertyName = "Column10";
            style10.BackColor = Color.Lime;
            style10.SelectionBackColor = Color.Lime;
            this.Column10.DefaultCellStyle = style10;
            this.Column10.FillWeight = 36.0159f;
            this.Column10.HeaderText = "10";
            this.Column10.Name = "Column10";
            this.Column10.ReadOnly = true;
            this.Column10.Resizable = DataGridViewTriState.False;
            this.Column10.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column11.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column11.DataPropertyName = "Column11";
            style11.BackColor = Color.White;
            style11.SelectionBackColor = Color.White;
            this.Column11.DefaultCellStyle = style11;
            this.Column11.FillWeight = 36.0159f;
            this.Column11.HeaderText = "11";
            this.Column11.Name = "Column11";
            this.Column11.ReadOnly = true;
            this.Column11.Resizable = DataGridViewTriState.False;
            this.Column11.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column12.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column12.DataPropertyName = "Column12";
            style12.BackColor = Color.Lime;
            style12.SelectionBackColor = Color.Lime;
            this.Column12.DefaultCellStyle = style12;
            this.Column12.FillWeight = 36.0159f;
            this.Column12.HeaderText = "12";
            this.Column12.Name = "Column12";
            this.Column12.ReadOnly = true;
            this.Column12.Resizable = DataGridViewTriState.False;
            this.Column12.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column13.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column13.DataPropertyName = "Column13";
            style13.BackColor = Color.White;
            style13.SelectionBackColor = Color.White;
            this.Column13.DefaultCellStyle = style13;
            this.Column13.FillWeight = 36.0159f;
            this.Column13.HeaderText = "13";
            this.Column13.Name = "Column13";
            this.Column13.ReadOnly = true;
            this.Column13.Resizable = DataGridViewTriState.False;
            this.Column13.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column14.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column14.DataPropertyName = "Column14";
            style14.BackColor = Color.Lime;
            style14.SelectionBackColor = Color.Lime;
            this.Column14.DefaultCellStyle = style14;
            this.Column14.FillWeight = 36.0159f;
            this.Column14.HeaderText = "14";
            this.Column14.Name = "Column14";
            this.Column14.ReadOnly = true;
            this.Column14.Resizable = DataGridViewTriState.False;
            this.Column14.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column15.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            this.Column15.DataPropertyName = "Column15";
            style15.BackColor = Color.White;
            style15.SelectionBackColor = Color.White;
            this.Column15.DefaultCellStyle = style15;
            this.Column15.FillWeight = 36.0159f;
            this.Column15.HeaderText = "15";
            this.Column15.Name = "Column15";
            this.Column15.ReadOnly = true;
            this.Column15.Resizable = DataGridViewTriState.False;
            this.Column15.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.m_dgvUnit.AllowUserToAddRows = false;
            this.m_dgvUnit.AllowUserToDeleteRows = false;
            this.m_dgvUnit.AllowUserToResizeColumns = false;
            this.m_dgvUnit.AllowUserToResizeRows = false;
            this.m_dgvUnit.BackgroundColor = SystemColors.Control;
            this.m_dgvUnit.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.m_dgvUnit.CellBorderStyle = DataGridViewCellBorderStyle.None;
            style16.BackColor = SystemColors.Control;
            style16.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
            style16.ForeColor = SystemColors.WindowText;
            style16.SelectionBackColor = SystemColors.Highlight;
            style16.SelectionForeColor = SystemColors.HighlightText;
            this.m_dgvUnit.ColumnHeadersDefaultCellStyle = style16;
            this.m_dgvUnit.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.m_dgvUnit.ColumnHeadersVisible = false;
            this.m_dgvUnit.Columns.AddRange(new DataGridViewColumn[] { this.Column16 });
            style17.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style17.BackColor = SystemColors.Control;
            style17.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 134);
            style17.ForeColor = Color.Black;
            style17.SelectionBackColor = SystemColors.Control;
            style17.SelectionForeColor = Color.Black;
            style17.WrapMode = DataGridViewTriState.False;
            this.m_dgvUnit.DefaultCellStyle = style17;
            this.m_dgvUnit.Enabled = false;
            this.m_dgvUnit.Location = new Point(13, 27);
            this.m_dgvUnit.Name = "m_dgvUnit";
            this.m_dgvUnit.RowHeadersVisible = false;
            this.m_dgvUnit.RowTemplate.DefaultCellStyle.BackColor = SystemColors.Control;
            this.m_dgvUnit.RowTemplate.DefaultCellStyle.ForeColor = Color.Black;
            this.m_dgvUnit.RowTemplate.DefaultCellStyle.SelectionBackColor = SystemColors.Control;
            this.m_dgvUnit.RowTemplate.DefaultCellStyle.SelectionForeColor = Color.Black;
            this.m_dgvUnit.RowTemplate.Height = 32;
            this.m_dgvUnit.RowTemplate.ReadOnly = true;
            this.m_dgvUnit.ScrollBars = ScrollBars.None;
            this.m_dgvUnit.Size = new Size(44, 400);
            this.m_dgvUnit.TabIndex = 27;
            this.Column16.DataPropertyName = "Column16";
            style18.Alignment = DataGridViewContentAlignment.TopCenter;
            style18.BackColor = Color.White;
            style18.ForeColor = Color.Black;
            style18.SelectionBackColor = Color.White;
            style18.SelectionForeColor = Color.Black;
            this.Column16.DefaultCellStyle = style18;
            this.Column16.FillWeight = 60f;
            this.Column16.HeaderText = "0";
            this.Column16.Name = "Column16";
            this.Column16.ReadOnly = true;
            this.Column16.Resizable = DataGridViewTriState.False;
            this.Column16.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.Column16.Width = 60;
            this.lblMonday.AutoSize = true;
            this.lblMonday.Location = new Point(84, 425);
            this.lblMonday.Name = "lblMonday";
            this.lblMonday.Size = new Size(41, 12);
            this.lblMonday.TabIndex = 29;
            this.lblMonday.Text = "星期一";
            this.lblTuesday.AutoSize = true;
            this.lblTuesday.Location = new Point(151, 425);
            this.lblTuesday.Name = "lblTuesday";
            this.lblTuesday.Size = new Size(41, 12);
            this.lblTuesday.TabIndex = 30;
            this.lblTuesday.Text = "星期二";
            this.lblWednesday.AutoSize = true;
            this.lblWednesday.Location = new Point(221, 425);
            this.lblWednesday.Name = "lblWednesday";
            this.lblWednesday.Size = new Size(41, 12);
            this.lblWednesday.TabIndex = 31;
            this.lblWednesday.Text = "星期三";
            this.lblThursday.AutoSize = true;
            this.lblThursday.Location = new Point(288, 425);
            this.lblThursday.Name = "lblThursday";
            this.lblThursday.Size = new Size(41, 12);
            this.lblThursday.TabIndex = 32;
            this.lblThursday.Text = "星期四";
            this.lblFriday.AutoSize = true;
            this.lblFriday.Location = new Point(356, 425);
            this.lblFriday.Name = "lblFriday";
            this.lblFriday.Size = new Size(41, 12);
            this.lblFriday.TabIndex = 33;
            this.lblFriday.Text = "星期五";
            this.lblSaturday.AutoSize = true;
            this.lblSaturday.Location = new Point(423, 425);
            this.lblSaturday.Name = "lblSaturday";
            this.lblSaturday.Size = new Size(41, 12);
            this.lblSaturday.TabIndex = 34;
            this.lblSaturday.Text = "星期六";
            this.lblSunday.AutoSize = true;
            this.lblSunday.Location = new Point(490, 425);
            this.lblSunday.Name = "lblSunday";
            this.lblSunday.Size = new Size(41, 12);
            this.lblSunday.TabIndex = 35;
            this.lblSunday.Text = "星期天";
            this.lblColor.BackColor = Color.Blue;
            this.lblColor.Location = new Point(37, 453);
            this.lblColor.Name = "lblColor";
            this.lblColor.Size = new Size(23, 5);
            this.lblColor.TabIndex = 41;
            this.lblColor.Text = "   ";
            this.lblText.AutoSize = true;
            this.lblText.Location = new Point(66, 449);
            this.lblText.Name = "lblText";
            this.lblText.Size = new Size(197, 12);
            this.lblText.TabIndex = 40;
            this.lblText.Text = "一次定时定位最小时间间隔为15分钟";
            this.lblStartTime.AutoSize = true;
            this.lblStartTime.Location = new Point(102, 475);
            this.lblStartTime.Name = "lblStartTime";
            this.lblStartTime.Size = new Size(59, 12);
            this.lblStartTime.TabIndex = 37;
            this.lblStartTime.Text = "开始时间:";
            this.dtpStartTime.Format = DateTimePickerFormat.Custom;
            this.dtpStartTime.Location = new Point(164, 471);
            this.dtpStartTime.Name = "dtpStartTime";
            this.dtpStartTime.Size = new Size(129, 21);
            this.dtpStartTime.TabIndex = 36;
            this.lblEndTime.AutoSize = true;
            this.lblEndTime.Location = new Point(304, 475);
            this.lblEndTime.Name = "lblEndTime";
            this.lblEndTime.Size = new Size(59, 12);
            this.lblEndTime.TabIndex = 38;
            this.lblEndTime.Text = "结束时间:";
            this.dtpEndTime.Format = DateTimePickerFormat.Custom;
            this.dtpEndTime.Location = new Point(366, 471);
            this.dtpEndTime.Name = "dtpEndTime";
            this.dtpEndTime.Size = new Size(129, 21);
            this.dtpEndTime.TabIndex = 39;
            this.btnClear.Location = new Point(130, 5);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new Size(75, 23);
            this.btnClear.TabIndex = 45;
            this.btnClear.Text = "清空";
            this.btnClear.UseVisualStyleBackColor = true;
            this.btnClear.Click += new EventHandler(this.btnClear_Click);
            this.btnResume.Location = new Point(217, 5);
            this.btnResume.Name = "btnResume";
            this.btnResume.Size = new Size(75, 23);
            this.btnResume.TabIndex = 44;
            this.btnResume.Text = "恢复";
            this.btnResume.UseVisualStyleBackColor = true;
            this.btnResume.Click += new EventHandler(this.btnResume_Click);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(606, 654);
            base.Controls.Add(this.grpParam);
            base.Name = "itmCarLBSParam";
            this.Text = "位置查询";
            base.Load += new EventHandler(this.itmCarLBSParam_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpParam, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpParam.ResumeLayout(false);
            this.grpParam.PerformLayout();
            ((ISupportInitialize) this.m_dgvTimeValue).EndInit();
            ((ISupportInitialize) this.m_dgvUnit).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private bool bDTUChanged;
        private bool bIsDown;
        private bool bIsMove;
        private bool bMove;
        private Button btnClear;
        private Button btnResume;
        private bool bUTDChanged;
        private DataGridViewTextBoxColumn Column1;
        private DataGridViewTextBoxColumn Column10;
        private DataGridViewTextBoxColumn Column11;
        private DataGridViewTextBoxColumn Column12;
        private DataGridViewTextBoxColumn Column13;
        private DataGridViewTextBoxColumn Column14;
        private DataGridViewTextBoxColumn Column15;
        private DataGridViewTextBoxColumn Column16;
        private DataGridViewTextBoxColumn Column2;
        private DataGridViewTextBoxColumn Column3;
        private DataGridViewTextBoxColumn Column4;
        private DataGridViewTextBoxColumn Column5;
        private DataGridViewTextBoxColumn Column6;
        private DataGridViewTextBoxColumn Column7;
        private DataGridViewTextBoxColumn Column8;
        private DataGridViewTextBoxColumn Column9;
        private DataTable dtLCSParam;
        private DateTimePicker dtpEndTime;
        private DateTimePicker dtpStartTime;
        private GroupBox grpParam;
        private Label label1;
        private Label lblColor;
        private Label lblEndTime;
        private Label lblFriday;
        private Label lblMonday;
        private Label lblSaturday;
        private Label lblStartTime;
        private Label lblSunday;
        private Label lblText;
        private Label lblThursday;
        private Label lblTuesday;
        private Label lblUnit;
        private Label lblWednesday;
        private DataGridView m_dgvTimeValue;
        private DataGridView m_dgvUnit;
        private string strEndTime;
        private string strStartTime;
    }
}