namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class itmPreSetPath
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
 private void InitializeComponent()
        {
            this.components = new Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(itmPreSetPath));
            this.btnDisplay = new Button();
            this.btnTool = new Button();
            this.pnlRegion = new Panel();
            this.panel1 = new Panel();
            this.lblPath = new Label();
            this.txtSearch = new TextBox();
            this.tabPath = new TabControl();
            this.tabPage1 = new TabPage();
            this.cmbPath = new ComboBox();
            this.tabPage2 = new TabPage();
            this.cmbPathSegments = new ComboBox();
            this.pnlbtnContainer = new Panel();
            this.btnModifyPath = new Button();
            this.btnDelPath = new Button();
            this.btnZoonOut = new Button();
            this.btnZoomIn = new Button();
            this.btnMove = new Button();
            this.btnSet = new Button();
            this.pnlSetRegion = new Panel();
            this.pnlBtn = new Panel();
            this.pnlHandle = new Panel();
            this.btnDelPoint = new Button();
            this.btnDistance = new Button();
            this.btnRefresh = new Button();
            this.btnPreviewDel = new Button();
            this.btnSetPathSTD = new Button();
            this.btnSetPath = new Button();
            this.picLoadMap = new PictureBox();
            this.mapMenu = new ContextMenuStrip(this.components);
            this.MenuItem撤销路线 = new ToolStripMenuItem();
            this.MenuItem添加路段 = new ToolStripMenuItem();
            this.pnlMap = new Panel();
            this.grpSegment = new GroupBox();
            this.btnCancelAddSegment = new Button();
            this.btnAddSegment = new Button();
            this.lblSegment = new Label();
            this.txtSegment = new TextBox();
            this.wbMap = new GisMap();
            this.splitContainer1 = new SplitContainer();
            this.pnlRegion.SuspendLayout();
            this.panel1.SuspendLayout();
            this.tabPath.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.pnlbtnContainer.SuspendLayout();
            this.pnlSetRegion.SuspendLayout();
            this.pnlBtn.SuspendLayout();
            this.pnlHandle.SuspendLayout();
            ((ISupportInitialize) this.picLoadMap).BeginInit();
            this.mapMenu.SuspendLayout();
            this.pnlMap.SuspendLayout();
            this.grpSegment.SuspendLayout();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            base.SuspendLayout();
            this.btnDisplay.Dock = DockStyle.Bottom;
            this.btnDisplay.Location = new Point(0, 341);
            this.btnDisplay.Name = "btnDisplay";
            this.btnDisplay.Size = new Size(150, 23);
            this.btnDisplay.TabIndex = 1;
            this.btnDisplay.Text = "显示";
            this.btnDisplay.UseVisualStyleBackColor = true;
            this.btnDisplay.Click += new EventHandler(this.btnDisplay_Click);
            this.btnTool.Dock = DockStyle.Bottom;
            this.btnTool.Location = new Point(0, 364);
            this.btnTool.Name = "btnTool";
            this.btnTool.Size = new Size(150, 23);
            this.btnTool.TabIndex = 2;
            this.btnTool.Text = "地图工具";
            this.btnTool.UseVisualStyleBackColor = true;
            this.btnTool.Click += new EventHandler(this.btnTool_Click);
            this.pnlRegion.Controls.Add(this.panel1);
            this.pnlRegion.Controls.Add(this.tabPath);
            this.pnlRegion.Controls.Add(this.pnlbtnContainer);
            this.pnlRegion.Dock = DockStyle.Bottom;
            this.pnlRegion.Location = new Point(0, 387);
            this.pnlRegion.Name = "pnlRegion";
            this.pnlRegion.Size = new Size(150, 130);
            this.pnlRegion.TabIndex = 4;
            this.pnlRegion.Visible = false;
            this.panel1.Controls.Add(this.lblPath);
            this.panel1.Controls.Add(this.txtSearch);
            this.panel1.Dock = DockStyle.Bottom;
            this.panel1.Location = new Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(150, 48);
            this.panel1.TabIndex = 6;
            this.lblPath.AutoSize = true;
            this.lblPath.Location = new Point(1, 5);
            this.lblPath.Name = "lblPath";
            this.lblPath.Size = new Size(149, 12);
            this.lblPath.TabIndex = 0;
            this.lblPath.Text = "路线查找(按回车继续查找)";
            this.txtSearch.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.txtSearch.Location = new Point(3, 20);
            this.txtSearch.Name = "txtSearch";
            this.txtSearch.Size = new Size(142, 21);
            this.txtSearch.TabIndex = 3;
            this.txtSearch.TextChanged += new EventHandler(this.txtSearch_TextChanged);
            this.txtSearch.PreviewKeyDown += new PreviewKeyDownEventHandler(this.txtSearch_PreviewKeyDown);
            this.tabPath.Controls.Add(this.tabPage1);
            this.tabPath.Controls.Add(this.tabPage2);
            this.tabPath.Dock = DockStyle.Bottom;
            this.tabPath.Location = new Point(0, 48);
            this.tabPath.Name = "tabPath";
            this.tabPath.SelectedIndex = 0;
            this.tabPath.Size = new Size(150, 54);
            this.tabPath.TabIndex = 7;
            this.tabPage1.Controls.Add(this.cmbPath);
            this.tabPage1.Location = new Point(4, 21);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new Padding(3);
            this.tabPage1.Size = new Size(142, 29);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "路线";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.cmbPath.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.cmbPath.DisplayMember = "PathName";
            this.cmbPath.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbPath.FlatStyle = FlatStyle.Flat;
            this.cmbPath.FormattingEnabled = true;
            this.cmbPath.Items.AddRange(new object[] { "(无)" });
            this.cmbPath.Location = new Point(1, 5);
            this.cmbPath.Name = "cmbPath";
            this.cmbPath.Size = new Size(142, 20);
            this.cmbPath.TabIndex = 0;
            this.cmbPath.ValueMember = "AlarmPathDot";
            this.cmbPath.SelectedIndexChanged += new EventHandler(this.cmbPath_SelectedIndexChanged);
            this.tabPage2.Controls.Add(this.cmbPathSegments);
            this.tabPage2.Location = new Point(4, 21);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new Padding(3);
            this.tabPage2.Size = new Size(142, 29);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "所属路段";
            this.tabPage2.UseVisualStyleBackColor = true;
            this.cmbPathSegments.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.cmbPathSegments.DisplayMember = "PathSegmentName";
            this.cmbPathSegments.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbPathSegments.FlatStyle = FlatStyle.Flat;
            this.cmbPathSegments.FormattingEnabled = true;
            this.cmbPathSegments.Location = new Point(0, 4);
            this.cmbPathSegments.Name = "cmbPathSegments";
            this.cmbPathSegments.Size = new Size(142, 20);
            this.cmbPathSegments.TabIndex = 1;
            this.cmbPathSegments.ValueMember = "alarmSegmentDot";
            this.pnlbtnContainer.Controls.Add(this.btnModifyPath);
            this.pnlbtnContainer.Controls.Add(this.btnDelPath);
            this.pnlbtnContainer.Dock = DockStyle.Bottom;
            this.pnlbtnContainer.Location = new Point(0, 102);
            this.pnlbtnContainer.Name = "pnlbtnContainer";
            this.pnlbtnContainer.Size = new Size(150, 28);
            this.pnlbtnContainer.TabIndex = 4;
            this.btnModifyPath.Location = new Point(-2, 3);
            this.btnModifyPath.Name = "btnModifyPath";
            this.btnModifyPath.Size = new Size(75, 23);
            this.btnModifyPath.TabIndex = 2;
            this.btnModifyPath.Text = "修改路线";
            this.btnModifyPath.UseVisualStyleBackColor = true;
            this.btnModifyPath.Click += new EventHandler(this.btnModifyPath_Click);
            this.btnDelPath.Location = new Point(73, 3);
            this.btnDelPath.Name = "btnDelPath";
            this.btnDelPath.Size = new Size(75, 23);
            this.btnDelPath.TabIndex = 1;
            this.btnDelPath.Text = "删除路线";
            this.btnDelPath.UseVisualStyleBackColor = true;
            this.btnDelPath.Click += new EventHandler(this.btnDelPath_Click);
            this.btnZoonOut.Dock = DockStyle.Top;
            this.btnZoonOut.FlatStyle = FlatStyle.Popup;
            this.btnZoonOut.Image = (Image)resources.GetObject("btnZoonOut.Image");
            this.btnZoonOut.ImageAlign = ContentAlignment.TopCenter;
            this.btnZoonOut.Location = new Point(0, 260);
            this.btnZoonOut.Name = "btnZoonOut";
            this.btnZoonOut.Padding = new Padding(5);
            this.btnZoonOut.Size = new Size(150, 52);
            this.btnZoonOut.TabIndex = 4;
            this.btnZoonOut.Tag = "9999";
            this.btnZoonOut.Text = "缩小";
            this.btnZoonOut.TextAlign = ContentAlignment.BottomCenter;
            this.btnZoonOut.UseVisualStyleBackColor = true;
            this.btnZoonOut.Visible = false;
            this.btnZoonOut.Click += new EventHandler(this.btnZoonOut_Click);
            this.btnZoomIn.Dock = DockStyle.Top;
            this.btnZoomIn.FlatStyle = FlatStyle.Popup;
            this.btnZoomIn.Image = (Image)resources.GetObject("btnZoomIn.Image");
            this.btnZoomIn.ImageAlign = ContentAlignment.TopCenter;
            this.btnZoomIn.Location = new Point(0, 208);
            this.btnZoomIn.Name = "btnZoomIn";
            this.btnZoomIn.Padding = new Padding(5);
            this.btnZoomIn.Size = new Size(150, 52);
            this.btnZoomIn.TabIndex = 3;
            this.btnZoomIn.Tag = "9999";
            this.btnZoomIn.Text = "放大";
            this.btnZoomIn.TextAlign = ContentAlignment.BottomCenter;
            this.btnZoomIn.UseVisualStyleBackColor = true;
            this.btnZoomIn.Visible = false;
            this.btnZoomIn.Click += new EventHandler(this.btnZoomIn_Click);
            this.btnMove.Dock = DockStyle.Top;
            this.btnMove.FlatStyle = FlatStyle.Popup;
            this.btnMove.Image = (Image)resources.GetObject("btnMove.Image");
            this.btnMove.ImageAlign = ContentAlignment.TopCenter;
            this.btnMove.Location = new Point(0, 156);
            this.btnMove.Name = "btnMove";
            this.btnMove.Padding = new Padding(5);
            this.btnMove.Size = new Size(150, 52);
            this.btnMove.TabIndex = 2;
            this.btnMove.Tag = "9999";
            this.btnMove.Text = "移动";
            this.btnMove.TextAlign = ContentAlignment.BottomCenter;
            this.btnMove.UseVisualStyleBackColor = true;
            this.btnMove.Visible = false;
            this.btnMove.Click += new EventHandler(this.btnMove_Click);
            this.btnSet.Dock = DockStyle.Top;
            this.btnSet.Location = new Point(0, 0);
            this.btnSet.Name = "btnSet";
            this.btnSet.Size = new Size(150, 23);
            this.btnSet.TabIndex = 0;
            this.btnSet.Text = "设置";
            this.btnSet.UseVisualStyleBackColor = true;
            this.btnSet.Click += new EventHandler(this.btnSet_Click);
            this.pnlSetRegion.Controls.Add(this.pnlBtn);
            this.pnlSetRegion.Controls.Add(this.pnlRegion);
            this.pnlSetRegion.Dock = DockStyle.Fill;
            this.pnlSetRegion.Location = new Point(0, 0);
            this.pnlSetRegion.Name = "pnlSetRegion";
            this.pnlSetRegion.Size = new Size(150, 517);
            this.pnlSetRegion.TabIndex = 0;
            this.pnlBtn.Controls.Add(this.pnlHandle);
            this.pnlBtn.Controls.Add(this.btnSet);
            this.pnlBtn.Controls.Add(this.btnDisplay);
            this.pnlBtn.Controls.Add(this.btnTool);
            this.pnlBtn.Dock = DockStyle.Fill;
            this.pnlBtn.Location = new Point(0, 0);
            this.pnlBtn.Name = "pnlBtn";
            this.pnlBtn.Size = new Size(150, 387);
            this.pnlBtn.TabIndex = 3;
            this.pnlHandle.Controls.Add(this.btnDelPoint);
            this.pnlHandle.Controls.Add(this.btnDistance);
            this.pnlHandle.Controls.Add(this.btnRefresh);
            this.pnlHandle.Controls.Add(this.btnZoonOut);
            this.pnlHandle.Controls.Add(this.btnZoomIn);
            this.pnlHandle.Controls.Add(this.btnMove);
            this.pnlHandle.Controls.Add(this.btnPreviewDel);
            this.pnlHandle.Controls.Add(this.btnSetPathSTD);
            this.pnlHandle.Controls.Add(this.btnSetPath);
            this.pnlHandle.Dock = DockStyle.Fill;
            this.pnlHandle.Location = new Point(0, 23);
            this.pnlHandle.Name = "pnlHandle";
            this.pnlHandle.Size = new Size(150, 318);
            this.pnlHandle.TabIndex = 4;
            this.btnDelPoint.Dock = DockStyle.Top;
            this.btnDelPoint.FlatStyle = FlatStyle.Popup;
            this.btnDelPoint.Image = Resources.delete;
            this.btnDelPoint.ImageAlign = ContentAlignment.TopCenter;
            this.btnDelPoint.Location = new Point(0, 416);
            this.btnDelPoint.Name = "btnDelPoint";
            this.btnDelPoint.Padding = new Padding(5);
            this.btnDelPoint.Size = new Size(150, 52);
            this.btnDelPoint.TabIndex = 8;
            this.btnDelPoint.Tag = "9999";
            this.btnDelPoint.Text = "删除";
            this.btnDelPoint.TextAlign = ContentAlignment.BottomCenter;
            this.btnDelPoint.UseVisualStyleBackColor = true;
            this.btnDelPoint.Visible = false;
            this.btnDelPoint.Click += new EventHandler(this.btnDelPoint_Click);
            this.btnDistance.Dock = DockStyle.Top;
            this.btnDistance.FlatStyle = FlatStyle.Popup;
            this.btnDistance.Image = Resources.ruler;
            this.btnDistance.ImageAlign = ContentAlignment.TopCenter;
            this.btnDistance.Location = new Point(0, 364);
            this.btnDistance.Name = "btnDistance";
            this.btnDistance.Padding = new Padding(5);
            this.btnDistance.Size = new Size(150, 52);
            this.btnDistance.TabIndex = 7;
            this.btnDistance.Tag = "9999";
            this.btnDistance.Text = "测距";
            this.btnDistance.TextAlign = ContentAlignment.BottomCenter;
            this.btnDistance.UseVisualStyleBackColor = true;
            this.btnDistance.Visible = false;
            this.btnDistance.Click += new EventHandler(this.btnDistance_Click);
            this.btnRefresh.Dock = DockStyle.Top;
            this.btnRefresh.FlatStyle = FlatStyle.Popup;
            this.btnRefresh.Image = (Image)resources.GetObject("btnRefresh.Image");
            this.btnRefresh.ImageAlign = ContentAlignment.TopCenter;
            this.btnRefresh.Location = new Point(0, 312);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Padding = new Padding(5);
            this.btnRefresh.Size = new Size(150, 52);
            this.btnRefresh.TabIndex = 5;
            this.btnRefresh.Tag = "9999";
            this.btnRefresh.Text = "刷新";
            this.btnRefresh.TextAlign = ContentAlignment.BottomCenter;
            this.btnRefresh.UseVisualStyleBackColor = true;
            this.btnRefresh.Visible = false;
            this.btnRefresh.Click += new EventHandler(this.btnRefresh_Click);
            this.btnPreviewDel.Dock = DockStyle.Top;
            this.btnPreviewDel.FlatStyle = FlatStyle.Popup;
            this.btnPreviewDel.Location = new Point(0, 104);
            this.btnPreviewDel.Name = "btnPreviewDel";
            this.btnPreviewDel.Size = new Size(150, 52);
            this.btnPreviewDel.TabIndex = 1;
            this.btnPreviewDel.Tag = "9999";
            this.btnPreviewDel.Text = "预览/删除路线";
            this.btnPreviewDel.UseVisualStyleBackColor = true;
            this.btnPreviewDel.Visible = false;
            this.btnPreviewDel.Click += new EventHandler(this.btnPreviewDel_Click);
            this.btnSetPathSTD.Dock = DockStyle.Top;
            this.btnSetPathSTD.FlatStyle = FlatStyle.Popup;
            this.btnSetPathSTD.Location = new Point(0, 52);
            this.btnSetPathSTD.Name = "btnSetPathSTD";
            this.btnSetPathSTD.Size = new Size(150, 52);
            this.btnSetPathSTD.TabIndex = 6;
            this.btnSetPathSTD.Tag = "9999";
            this.btnSetPathSTD.Text = "设置路线(导航)";
            this.btnSetPathSTD.UseVisualStyleBackColor = true;
            this.btnSetPathSTD.Click += new EventHandler(this.btnSetPathSTD_Click);
            this.btnSetPath.Dock = DockStyle.Top;
            this.btnSetPath.FlatStyle = FlatStyle.Popup;
            this.btnSetPath.Location = new Point(0, 0);
            this.btnSetPath.Name = "btnSetPath";
            this.btnSetPath.Size = new Size(150, 52);
            this.btnSetPath.TabIndex = 0;
            this.btnSetPath.Tag = "9999";
            this.btnSetPath.Text = "设置路线";
            this.btnSetPath.UseVisualStyleBackColor = true;
            this.btnSetPath.Click += new EventHandler(this.btnSetPath_Click);
            this.picLoadMap.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.picLoadMap.BackgroundImage = (Image)resources.GetObject("picLoadMap.BackgroundImage");
            this.picLoadMap.Location = new Point(185, 242);
            this.picLoadMap.Name = "picLoadMap";
            this.picLoadMap.Size = new Size(167, 33);
            this.picLoadMap.TabIndex = 6;
            this.picLoadMap.TabStop = false;
            this.picLoadMap.Visible = false;
            this.mapMenu.Items.AddRange(new ToolStripItem[] { this.MenuItem撤销路线, this.MenuItem添加路段 });
            this.mapMenu.Name = "mapMenu";
            this.mapMenu.Size = new Size(119, 48);
            this.MenuItem撤销路线.Name = "MenuItem撤销路线";
            this.MenuItem撤销路线.Size = new Size(118, 22);
            this.MenuItem撤销路线.Text = "撤销路线";
            this.MenuItem撤销路线.ToolTipText = "撤销最近一次添加的线段";
            this.MenuItem撤销路线.Click += new EventHandler(this.MenuItem撤销路线_Click);
            this.MenuItem添加路段.Name = "MenuItem添加路段";
            this.MenuItem添加路段.Size = new Size(118, 22);
            this.MenuItem添加路段.Text = "添加路段";
            this.MenuItem添加路段.Click += new EventHandler(this.MenuItem添加路段_Click);
            this.pnlMap.Controls.Add(this.grpSegment);
            this.pnlMap.Controls.Add(this.picLoadMap);
            this.pnlMap.Controls.Add(this.wbMap);
            this.pnlMap.Dock = DockStyle.Fill;
            this.pnlMap.Location = new Point(0, 0);
            this.pnlMap.Name = "pnlMap";
            this.pnlMap.Size = new Size(533, 517);
            this.pnlMap.TabIndex = 7;
            this.grpSegment.Controls.Add(this.btnCancelAddSegment);
            this.grpSegment.Controls.Add(this.btnAddSegment);
            this.grpSegment.Controls.Add(this.lblSegment);
            this.grpSegment.Controls.Add(this.txtSegment);
            this.grpSegment.Location = new Point(142, 195);
            this.grpSegment.Name = "grpSegment";
            this.grpSegment.Size = new Size(210, 88);
            this.grpSegment.TabIndex = 7;
            this.grpSegment.TabStop = false;
            this.grpSegment.Text = "添加路段";
            this.grpSegment.Visible = false;
            this.btnCancelAddSegment.Location = new Point(125, 57);
            this.btnCancelAddSegment.Name = "btnCancelAddSegment";
            this.btnCancelAddSegment.Size = new Size(75, 23);
            this.btnCancelAddSegment.TabIndex = 3;
            this.btnCancelAddSegment.Text = "取消";
            this.btnCancelAddSegment.UseVisualStyleBackColor = true;
            this.btnCancelAddSegment.Click += new EventHandler(this.btnCancelAddSegment_Click);
            this.btnAddSegment.Location = new Point(26, 57);
            this.btnAddSegment.Name = "btnAddSegment";
            this.btnAddSegment.Size = new Size(75, 23);
            this.btnAddSegment.TabIndex = 2;
            this.btnAddSegment.Text = "添加";
            this.btnAddSegment.UseVisualStyleBackColor = true;
            this.btnAddSegment.Click += new EventHandler(this.btnAddSegment_Click);
            this.lblSegment.AutoSize = true;
            this.lblSegment.Location = new Point(6, 24);
            this.lblSegment.Name = "lblSegment";
            this.lblSegment.Size = new Size(65, 12);
            this.lblSegment.TabIndex = 1;
            this.lblSegment.Text = "路段名称：";
            this.txtSegment.Location = new Point(72, 20);
            this.txtSegment.Name = "txtSegment";
            this.txtSegment.Size = new Size(128, 21);
            this.txtSegment.TabIndex = 0;
            this.wbMap.Dock = DockStyle.Fill;
            this.wbMap.IsWebBrowserContextMenuEnabled = false;
            this.wbMap.Location = new Point(0, 0);
            this.wbMap.MinimumSize = new Size(20, 20);
            this.wbMap.Name = "wbMap";
            this.wbMap.Size = new Size(533, 517);
            this.wbMap.TabIndex = 1;
            this.wbMap.WebBrowserShortcutsEnabled = false;
            this.wbMap.MapDirectionEvent += new HtmlElementEventHandler(this.wbMap_MapDirectionEvent);
            this.wbMap.DocumentCompleted += new WebBrowserDocumentCompletedEventHandler(this.wbMap_DocumentCompleted);
            this.wbMap.MapDoubleClick += new HtmlElementEventHandler(this.wbMap_DoubleClick);
            this.splitContainer1.Dock = DockStyle.Fill;
            this.splitContainer1.Location = new Point(5, 5);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Panel1.Controls.Add(this.pnlSetRegion);
            this.splitContainer1.Panel2.Controls.Add(this.pnlMap);
            this.splitContainer1.Size = new Size(687, 517);
            this.splitContainer1.SplitterDistance = 150;
            this.splitContainer1.TabIndex = 8;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(697, 527);
            base.Controls.Add(this.splitContainer1);
            base.Icon = (Icon)resources.GetObject("$this.Icon");
            base.Name = "itmPreSetPath";
            base.Padding = new Padding(5);
            this.Text = "预设报警路线";
            base.Load += new EventHandler(this.itmPreSetPath_Load);
            base.FormClosing += new FormClosingEventHandler(this.itmPreSetPath_FormClosing);
            this.pnlRegion.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.tabPath.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.pnlbtnContainer.ResumeLayout(false);
            this.pnlSetRegion.ResumeLayout(false);
            this.pnlBtn.ResumeLayout(false);
            this.pnlHandle.ResumeLayout(false);
            ((ISupportInitialize) this.picLoadMap).EndInit();
            this.mapMenu.ResumeLayout(false);
            this.pnlMap.ResumeLayout(false);
            this.grpSegment.ResumeLayout(false);
            this.grpSegment.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.ResumeLayout(false);
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private Button btnAddSegment;
        private Button btnCancelAddSegment;
        private Button btnDelPath;
        private Button btnDelPoint;
        private Button btnDisplay;
        private Button btnDistance;
        private Button btnModifyPath;
        private Button btnMove;
        private Button btnPreviewDel;
        private Button btnRefresh;
        private Button btnSet;
        private Button btnSetPath;
        private Button btnSetPathSTD;
        private Button btnTool;
        private Button btnZoomIn;
        private Button btnZoonOut;
        private ComboBox cmbPath;
        private ComboBox cmbPathSegments;
        private GroupBox grpSegment;
        private bool isUpdate;
        private Label lblPath;
        private Label lblSegment;
        private DataTable m_segmentsDt;
        private ContextMenuStrip mapMenu;
        private ToolStripMenuItem MenuItem撤销路线;
        private ToolStripMenuItem MenuItem添加路段;
        private Panel panel1;
        private PictureBox picLoadMap;
        private Panel pnlBtn;
        private Panel pnlbtnContainer;
        private Panel pnlHandle;
        private Panel pnlMap;
        private Panel pnlRegion;
        private Panel pnlSetRegion;
        private PreType preType;
        private SplitContainer splitContainer1;
        private TabPage tabPage1;
        private TabPage tabPage2;
        private TabControl tabPath;
        private TextBox txtSearch;
        private TextBox txtSegment;
        private GisMap wbMap;
    }
}