namespace Client
{
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class itmRealTimeReport
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            new ComponentResourceManager(typeof(itmRealTimeReport));
            this.grpWatchProperty = new GroupBox();
            this.lblWatchType = new Label();
            this.cmbWatchType = new ComBox();
            this.chkContinuWatch = new CheckBox();
            this.chkShowContrail = new CheckBox();
            this.chkNoReport = new CheckBox();
            this.lblRepair = new Label();
            this.numRepair = new NumericUpDown();
            this.lblAngle = new Label();
            this.lblTime = new Label();
            this.numTime = new NumericUpDown();
            this.cmbTime = new ComBox();
            this.lblDegree = new Label();
            this.lblInterval = new Label();
            this.numInterval = new NumericUpDown();
            this.lblSecond = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpWatchProperty.SuspendLayout();
            this.numRepair.BeginInit();
            this.numTime.BeginInit();
            this.numInterval.BeginInit();
            base.SuspendLayout();
            base.grpCar.TabIndex = 0;
            base.cmbType.TabIndex = 1;
            base.txtPassword.TabIndex = 5;
            base.txtCarNo.TabIndex = 3;
            base.lblPassword.TabIndex = 4;
            base.lblValue.TabIndex = 2;
            base.lblType.TabIndex = 0;
            base.pnlBtn.Location = new System.Drawing.Point(5, 263);
            base.pnlBtn.TabIndex = 2;
            base.btnCancel.TabIndex = 1;
            base.btnOK.TabIndex = 0;
            this.grpWatchProperty.Controls.Add(this.lblWatchType);
            this.grpWatchProperty.Controls.Add(this.cmbWatchType);
            this.grpWatchProperty.Controls.Add(this.chkContinuWatch);
            this.grpWatchProperty.Controls.Add(this.chkShowContrail);
            this.grpWatchProperty.Controls.Add(this.chkNoReport);
            this.grpWatchProperty.Controls.Add(this.lblRepair);
            this.grpWatchProperty.Controls.Add(this.numRepair);
            this.grpWatchProperty.Controls.Add(this.lblAngle);
            this.grpWatchProperty.Controls.Add(this.lblTime);
            this.grpWatchProperty.Controls.Add(this.numTime);
            this.grpWatchProperty.Controls.Add(this.cmbTime);
            this.grpWatchProperty.Controls.Add(this.lblDegree);
            this.grpWatchProperty.Controls.Add(this.lblInterval);
            this.grpWatchProperty.Controls.Add(this.numInterval);
            this.grpWatchProperty.Controls.Add(this.lblSecond);
            this.grpWatchProperty.Dock = DockStyle.Top;
            this.grpWatchProperty.Location = new System.Drawing.Point(5, 121);
            this.grpWatchProperty.Name = "grpWatchProperty";
            this.grpWatchProperty.Size = new Size(363, 142);
            this.grpWatchProperty.TabIndex = 1;
            this.grpWatchProperty.TabStop = false;
            this.grpWatchProperty.Text = "监控属性";
            this.lblWatchType.AutoSize = true;
            this.lblWatchType.Location = new System.Drawing.Point(50, 25);
            this.lblWatchType.Name = "lblWatchType";
            this.lblWatchType.Size = new Size(65, 12);
            this.lblWatchType.TabIndex = 0;
            this.lblWatchType.Text = "监控方式：";
            this.cmbWatchType.DisplayMember = "Display";
            this.cmbWatchType.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbWatchType.FlatStyle = FlatStyle.Flat;
            this.cmbWatchType.FormattingEnabled = true;
            this.cmbWatchType.Location = new System.Drawing.Point(122, 22);
            this.cmbWatchType.Name = "cmbWatchType";
            this.cmbWatchType.Size = new Size(161, 20);
            this.cmbWatchType.TabIndex = 1;
            this.cmbWatchType.Tag = "；";
            this.cmbWatchType.ValueMember = "Value";
            this.cmbWatchType.SelectedValueChanged += new EventHandler(this.cmbWatchType_SelectedValueChanged);
            this.chkContinuWatch.AutoSize = true;
            this.chkContinuWatch.Location = new System.Drawing.Point(52, 58);
            this.chkContinuWatch.Name = "chkContinuWatch";
            this.chkContinuWatch.Size = new Size(72, 16);
            this.chkContinuWatch.TabIndex = 2;
            this.chkContinuWatch.Text = "持续监控";
            this.chkContinuWatch.UseVisualStyleBackColor = true;
            this.chkContinuWatch.CheckedChanged += new EventHandler(this.chkContinuWatch_CheckedChanged);
            this.chkShowContrail.AutoSize = true;
            this.chkShowContrail.Location = new System.Drawing.Point(216, 58);
            this.chkShowContrail.Name = "chkShowContrail";
            this.chkShowContrail.Size = new Size(96, 16);
            this.chkShowContrail.TabIndex = 3;
            this.chkShowContrail.Text = "显示车辆轨迹";
            this.chkShowContrail.UseVisualStyleBackColor = true;
            this.chkShowContrail.Visible = false;
            this.chkNoReport.AutoSize = true;
            this.chkNoReport.Location = new System.Drawing.Point(52, 82);
            this.chkNoReport.Name = "chkNoReport";
            this.chkNoReport.Size = new Size(84, 16);
            this.chkNoReport.TabIndex = 4;
            this.chkNoReport.Text = "停车不汇报";
            this.chkNoReport.UseVisualStyleBackColor = true;
            this.lblRepair.AutoSize = true;
            this.lblRepair.Location = new System.Drawing.Point(214, 84);
            this.lblRepair.Name = "lblRepair";
            this.lblRepair.Size = new Size(65, 12);
            this.lblRepair.TabIndex = 5;
            this.lblRepair.Text = "拐点补偿：";
            this.numRepair.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numRepair.Location = new System.Drawing.Point(281, 80);
            int[] bits = new int[4];
            bits[0] = 180;
            this.numRepair.Maximum = new decimal(bits);
            this.numRepair.Name = "numRepair";
            this.numRepair.Size = new Size(54, 21);
            this.numRepair.TabIndex = 6;
            this.lblAngle.AutoSize = true;
            this.lblAngle.Location = new System.Drawing.Point(336, 84);
            this.lblAngle.Name = "lblAngle";
            this.lblAngle.Size = new Size(17, 12);
            this.lblAngle.TabIndex = 7;
            this.lblAngle.Tag = "；";
            this.lblAngle.Text = "度";
            this.lblTime.AutoSize = true;
            this.lblTime.Location = new System.Drawing.Point(37, 111);
            this.lblTime.Name = "lblTime";
            this.lblTime.Size = new Size(65, 12);
            this.lblTime.TabIndex = 8;
            this.lblTime.Text = "回传次数：";
            this.numTime.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numTime.Location = new System.Drawing.Point(103, 107);
            int[] numArray2 = new int[4];
            numArray2[0] = 65535;
            this.numTime.Maximum = new decimal(numArray2);
            int[] numArray3 = new int[4];
            numArray3[0] = 1;
            this.numTime.Minimum = new decimal(numArray3);
            this.numTime.Name = "numTime";
            this.numTime.Size = new Size(54, 21);
            this.numTime.TabIndex = 9;
            int[] numArray4 = new int[4];
            numArray4[0] = 1;
            this.numTime.Value = new decimal(numArray4);
            this.cmbTime.DisplayMember = "Display";
            this.cmbTime.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbTime.FlatStyle = FlatStyle.Flat;
            this.cmbTime.FormattingEnabled = true;
            this.cmbTime.Location = new System.Drawing.Point(159, 108);
            this.cmbTime.Name = "cmbTime";
            this.cmbTime.Size = new Size(50, 20);
            this.cmbTime.TabIndex = 10;
            this.cmbTime.Tag = "；";
            this.cmbTime.ValueMember = "Value";
            this.cmbTime.Visible = false;
            this.lblDegree.AutoSize = true;
            this.lblDegree.Location = new System.Drawing.Point(162, 111);
            this.lblDegree.Name = "lblDegree";
            this.lblDegree.Size = new Size(17, 12);
            this.lblDegree.TabIndex = 8;
            this.lblDegree.Tag = "；";
            this.lblDegree.Text = "次";
            this.lblInterval.AutoSize = true;
            this.lblInterval.Location = new System.Drawing.Point(214, 111);
            this.lblInterval.Name = "lblInterval";
            this.lblInterval.Size = new Size(65, 12);
            this.lblInterval.TabIndex = 11;
            this.lblInterval.Text = "间隔时间：";
            this.numInterval.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numInterval.Location = new System.Drawing.Point(281, 107);
            int[] numArray5 = new int[4];
            numArray5[0] = 65535;
            this.numInterval.Maximum = new decimal(numArray5);
            this.numInterval.Name = "numInterval";
            this.numInterval.Size = new Size(54, 21);
            this.numInterval.TabIndex = 12;
            int[] numArray6 = new int[4];
            numArray6[0] = 60;
            this.numInterval.Value = new decimal(numArray6);
            this.lblSecond.AutoSize = true;
            this.lblSecond.Location = new System.Drawing.Point(336, 111);
            this.lblSecond.Name = "lblSecond";
            this.lblSecond.Size = new Size(17, 12);
            this.lblSecond.TabIndex = 13;
            this.lblSecond.Tag = "；";
            this.lblSecond.Text = "秒";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            this.AutoSize = true;
            base.ClientSize = new Size(373, 296);
            base.Controls.Add(this.grpWatchProperty);
            base.Name = "itmRealTimeReport";
            this.Text = "位置查询";
            base.Load += new EventHandler(this.itmRealTimeReport_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpWatchProperty, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpWatchProperty.ResumeLayout(false);
            this.grpWatchProperty.PerformLayout();
            this.numRepair.EndInit();
            this.numTime.EndInit();
            this.numInterval.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private CheckBox chkContinuWatch;
        private CheckBox chkNoReport;
        private CheckBox chkShowContrail;
        private ComBox cmbTime;
        private ComBox cmbWatchType;
        private GroupBox grpWatchProperty;
        private CmdParam.IsCompressed isCompressed;
        private Label lblAngle;
        private Label lblDegree;
        private Label lblInterval;
        private Label lblRepair;
        private Label lblSecond;
        private Label lblTime;
        private Label lblWatchType;
        private NumericUpDown numInterval;
        private NumericUpDown numRepair;
        private NumericUpDown numTime;
    }
}