namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using ParamLibrary.Entity;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;

    partial class itmSetRegionAlarmEx
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.grpRegion = new GroupBox();
            this.lbEndPoint = new ListBox();
            this.lbStartPoint = new ListBox();
            this.txtEndPoint = new TextBox();
            this.txtStartPoint = new TextBox();
            this.lblEndPoint = new Label();
            this.lblStartPoint = new Label();
            this.grpCar = new GroupBox();
            this.btnAllSelect = new Button();
            this.btnAllUnSelect = new Button();
            this.btnUnSelect = new Button();
            this.btnSelect = new Button();
            this.lbAllCar = new ListBox();
            this.grpSelectCar = new GroupBox();
            this.lbSelectCar = new ListBox();
            this.txtAllCar = new TextBox();
            this.lblAllCar = new Label();
            this.pnlBtn = new Panel();
            this.pnlWait = new Panel();
            this.pbPicWait = new PictureBox();
            this.lblWaitText = new Label();
            this.btnOK = new Button();
            this.btnCancel = new Button();
            this.grpRegion.SuspendLayout();
            this.grpCar.SuspendLayout();
            this.grpSelectCar.SuspendLayout();
            this.pnlBtn.SuspendLayout();
            this.pnlWait.SuspendLayout();
            ((ISupportInitialize) this.pbPicWait).BeginInit();
            base.SuspendLayout();
            this.grpRegion.Controls.Add(this.lbEndPoint);
            this.grpRegion.Controls.Add(this.lbStartPoint);
            this.grpRegion.Controls.Add(this.txtEndPoint);
            this.grpRegion.Controls.Add(this.txtStartPoint);
            this.grpRegion.Controls.Add(this.lblEndPoint);
            this.grpRegion.Controls.Add(this.lblStartPoint);
            this.grpRegion.Dock = DockStyle.Left;
            this.grpRegion.Location = new System.Drawing.Point(0, 0);
            this.grpRegion.Name = "grpRegion";
            this.grpRegion.Size = new Size(362, 410);
            this.grpRegion.TabIndex = 0;
            this.grpRegion.TabStop = false;
            this.grpRegion.Text = "区域选择";
            this.lbEndPoint.FormattingEnabled = true;
            this.lbEndPoint.ItemHeight = 12;
            this.lbEndPoint.Location = new System.Drawing.Point(196, 47);
            this.lbEndPoint.Name = "lbEndPoint";
            this.lbEndPoint.Size = new Size(160, 352);
            this.lbEndPoint.TabIndex = 5;
            this.lbStartPoint.FormattingEnabled = true;
            this.lbStartPoint.ItemHeight = 12;
            this.lbStartPoint.Location = new System.Drawing.Point(8, 47);
            this.lbStartPoint.Name = "lbStartPoint";
            this.lbStartPoint.Size = new Size(160, 352);
            this.lbStartPoint.TabIndex = 4;
            this.txtEndPoint.Location = new System.Drawing.Point(241, 20);
            this.txtEndPoint.Name = "txtEndPoint";
            this.txtEndPoint.Size = new Size(115, 21);
            this.txtEndPoint.TabIndex = 3;
            this.txtEndPoint.TextChanged += new EventHandler(this.txtEndPoint_TextChanged);
            this.txtStartPoint.Location = new System.Drawing.Point(53, 18);
            this.txtStartPoint.Name = "txtStartPoint";
            this.txtStartPoint.Size = new Size(115, 21);
            this.txtStartPoint.TabIndex = 2;
            this.txtStartPoint.TextChanged += new EventHandler(this.txtStartPoint_TextChanged);
            this.lblEndPoint.AutoSize = true;
            this.lblEndPoint.Location = new System.Drawing.Point(194, 23);
            this.lblEndPoint.Name = "lblEndPoint";
            this.lblEndPoint.Size = new Size(41, 12);
            this.lblEndPoint.TabIndex = 1;
            this.lblEndPoint.Text = "终点：";
            this.lblStartPoint.AutoSize = true;
            this.lblStartPoint.Location = new System.Drawing.Point(6, 21);
            this.lblStartPoint.Name = "lblStartPoint";
            this.lblStartPoint.Size = new Size(41, 12);
            this.lblStartPoint.TabIndex = 0;
            this.lblStartPoint.Text = "起点：";
            this.grpCar.Controls.Add(this.btnAllSelect);
            this.grpCar.Controls.Add(this.btnAllUnSelect);
            this.grpCar.Controls.Add(this.btnUnSelect);
            this.grpCar.Controls.Add(this.btnSelect);
            this.grpCar.Controls.Add(this.lbAllCar);
            this.grpCar.Controls.Add(this.grpSelectCar);
            this.grpCar.Controls.Add(this.txtAllCar);
            this.grpCar.Controls.Add(this.lblAllCar);
            this.grpCar.Dock = DockStyle.Fill;
            this.grpCar.Location = new System.Drawing.Point(362, 0);
            this.grpCar.Name = "grpCar";
            this.grpCar.Size = new Size(396, 410);
            this.grpCar.TabIndex = 1;
            this.grpCar.TabStop = false;
            this.grpCar.Text = "车辆选择";
            this.btnAllSelect.Location = new System.Drawing.Point(176, 325);
            this.btnAllSelect.Name = "btnAllSelect";
            this.btnAllSelect.Size = new Size(40, 23);
            this.btnAllSelect.TabIndex = 12;
            this.btnAllSelect.Text = ">>";
            this.btnAllSelect.UseVisualStyleBackColor = true;
            this.btnAllSelect.Visible = false;
            this.btnAllSelect.Click += new EventHandler(this.btnAllSelect_Click);
            this.btnAllUnSelect.Location = new System.Drawing.Point(176, 274);
            this.btnAllUnSelect.Name = "btnAllUnSelect";
            this.btnAllUnSelect.Size = new Size(40, 23);
            this.btnAllUnSelect.TabIndex = 11;
            this.btnAllUnSelect.Text = "<<";
            this.btnAllUnSelect.UseVisualStyleBackColor = true;
            this.btnAllUnSelect.Visible = false;
            this.btnAllUnSelect.Click += new EventHandler(this.btnAllUnSelect_Click);
            this.btnUnSelect.Location = new System.Drawing.Point(176, 223);
            this.btnUnSelect.Name = "btnUnSelect";
            this.btnUnSelect.Size = new Size(40, 23);
            this.btnUnSelect.TabIndex = 10;
            this.btnUnSelect.Text = "<";
            this.btnUnSelect.UseVisualStyleBackColor = true;
            this.btnUnSelect.Click += new EventHandler(this.btnUnSelect_Click);
            this.btnSelect.Location = new System.Drawing.Point(176, 172);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new Size(40, 23);
            this.btnSelect.TabIndex = 9;
            this.btnSelect.Text = ">";
            this.btnSelect.UseVisualStyleBackColor = true;
            this.btnSelect.Click += new EventHandler(this.btnSelect_Click);
            this.lbAllCar.FormattingEnabled = true;
            this.lbAllCar.ItemHeight = 12;
            this.lbAllCar.Location = new System.Drawing.Point(8, 50);
            this.lbAllCar.Name = "lbAllCar";
            this.lbAllCar.SelectionMode = SelectionMode.MultiExtended;
            this.lbAllCar.Size = new Size(161, 352);
            this.lbAllCar.TabIndex = 7;
            this.lbAllCar.MouseDoubleClick += new MouseEventHandler(this.lbAllCar_MouseDoubleClick);
            this.grpSelectCar.Controls.Add(this.lbSelectCar);
            this.grpSelectCar.Dock = DockStyle.Right;
            this.grpSelectCar.Location = new System.Drawing.Point(219, 17);
            this.grpSelectCar.Name = "grpSelectCar";
            this.grpSelectCar.Size = new Size(174, 390);
            this.grpSelectCar.TabIndex = 8;
            this.grpSelectCar.TabStop = false;
            this.grpSelectCar.Text = "选中车辆";
            this.lbSelectCar.Dock = DockStyle.Fill;
            this.lbSelectCar.FormattingEnabled = true;
            this.lbSelectCar.ItemHeight = 12;
            this.lbSelectCar.Location = new System.Drawing.Point(3, 17);
            this.lbSelectCar.Name = "lbSelectCar";
            this.lbSelectCar.SelectionMode = SelectionMode.MultiExtended;
            this.lbSelectCar.Size = new Size(168, 364);
            this.lbSelectCar.TabIndex = 8;
            this.lbSelectCar.MouseDoubleClick += new MouseEventHandler(this.lbSelectCar_MouseDoubleClick);
            this.txtAllCar.Location = new System.Drawing.Point(76, 18);
            this.txtAllCar.Name = "txtAllCar";
            this.txtAllCar.Size = new Size(93, 21);
            this.txtAllCar.TabIndex = 6;
            this.txtAllCar.TextChanged += new EventHandler(this.txtAllCar_TextChanged);
            this.txtAllCar.KeyDown += new KeyEventHandler(this.txtAllCar_KeyDown);
            this.lblAllCar.AutoSize = true;
            this.lblAllCar.Location = new System.Drawing.Point(6, 24);
            this.lblAllCar.Name = "lblAllCar";
            this.lblAllCar.Size = new Size(65, 12);
            this.lblAllCar.TabIndex = 5;
            this.lblAllCar.Text = "车辆列表：";
            this.pnlBtn.Controls.Add(this.pnlWait);
            this.pnlBtn.Controls.Add(this.btnOK);
            this.pnlBtn.Controls.Add(this.btnCancel);
            this.pnlBtn.Dock = DockStyle.Bottom;
            this.pnlBtn.Location = new System.Drawing.Point(0, 410);
            this.pnlBtn.Name = "pnlBtn";
            this.pnlBtn.Size = new Size(758, 28);
            this.pnlBtn.TabIndex = 2;
            this.pnlWait.Controls.Add(this.pbPicWait);
            this.pnlWait.Controls.Add(this.lblWaitText);
            this.pnlWait.Location = new System.Drawing.Point(584, 3);
            this.pnlWait.Name = "pnlWait";
            this.pnlWait.Size = new Size(129, 22);
            this.pnlWait.TabIndex = 14;
            this.pnlWait.Tag = "9999";
            this.pbPicWait.BackColor = Color.Transparent;
            this.pbPicWait.Image = Resources.loading;
            this.pbPicWait.InitialImage = null;
            this.pbPicWait.Location = new System.Drawing.Point(3, 3);
            this.pbPicWait.Name = "pbPicWait";
            this.pbPicWait.Size = new Size(16, 16);
            this.pbPicWait.TabIndex = 11;
            this.pbPicWait.TabStop = false;
            this.pbPicWait.Tag = "9999";
            this.pbPicWait.Visible = false;
            this.lblWaitText.AutoSize = true;
            this.lblWaitText.Location = new System.Drawing.Point(22, 5);
            this.lblWaitText.Name = "lblWaitText";
            this.lblWaitText.Size = new Size(89, 12);
            this.lblWaitText.TabIndex = 9;
            this.lblWaitText.Text = "正在执行中....";
            this.lblWaitText.Visible = false;
            this.btnOK.Location = new System.Drawing.Point(241, 4);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(75, 23);
            this.btnOK.TabIndex = 1;
            this.btnOK.Text = "确定";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.DialogResult =  System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new System.Drawing.Point(354, 4);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(75, 23);
            this.btnCancel.TabIndex = 0;
            this.btnCancel.Text = "取消";
            this.btnCancel.UseVisualStyleBackColor = true;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(758, 438);
            base.Controls.Add(this.grpCar);
            base.Controls.Add(this.grpRegion);
            base.Controls.Add(this.pnlBtn);
            base.Name = "itmSetRegionAlarmEx";
            this.Text = "itmSetRegionAlarmEx";
            this.grpRegion.ResumeLayout(false);
            this.grpRegion.PerformLayout();
            this.grpCar.ResumeLayout(false);
            this.grpCar.PerformLayout();
            this.grpSelectCar.ResumeLayout(false);
            this.pnlBtn.ResumeLayout(false);
            this.pnlWait.ResumeLayout(false);
            this.pnlWait.PerformLayout();
            ((ISupportInitialize) this.pbPicWait).EndInit();
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private DataTable _selectdt;
        private Button btnAllSelect;
        private Button btnAllUnSelect;
        private Button btnCancel;
        private Button btnOK;
        private Button btnSelect;
        private Button btnUnSelect;
        private GroupBox grpCar;
        private System.Windows.Forms.GroupBox grpRegion;
        private GroupBox grpSelectCar;
        private ListBox lbAllCar;
        private ListBox lbEndPoint;
        private Label lblAllCar;
        private Label lblEndPoint;
        private Label lblStartPoint;
        private Label lblWaitText;
        private ListBox lbSelectCar;
        private ListBox lbStartPoint;
        private ParamLibrary.Application.CmdParam.OrderCode OrderCode;
        private PictureBox pbPicWait;
        private Panel pnlBtn;
        private Panel pnlWait;
        private TextBox txtAllCar;
        private TextBox txtEndPoint;
        private TextBox txtStartPoint;
    }
}