namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    partial class itmSetPass
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
 private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(itmSetPass));
            this.grpPassword = new GroupBox();
            this.pnlPassword = new Panel();
            this.pnlColor3 = new Panel();
            this.pnlColor2 = new Panel();
            this.pnlNG = new Panel();
            this.pnlOK = new Panel();
            this.pnlColor1 = new Panel();
            this.lblOldPassword = new Label();
            this.txtConfirmPassword = new TextBox();
            this.txtOldPassword = new TextBox();
            this.lblValidatePassword = new Label();
            this.lblNewPassword = new Label();
            this.txtNewPassword = new TextBox();
            this.pnlUserId = new Panel();
            this.lblUserId = new Label();
            this.txtUserId = new TextBox();
            this.btnOK = new Button();
            this.btnCancel = new Button();
            this.grpPassword.SuspendLayout();
            this.pnlPassword.SuspendLayout();
            this.pnlUserId.SuspendLayout();
            base.SuspendLayout();
            this.grpPassword.Controls.Add(this.pnlPassword);
            this.grpPassword.Controls.Add(this.pnlUserId);
            this.grpPassword.Location = new Point(13, 12);
            this.grpPassword.Name = "grpPassword";
            this.grpPassword.Size = new Size(396, 168);
            this.grpPassword.TabIndex = 0;
            this.grpPassword.TabStop = false;
            this.pnlPassword.BackColor = Color.Transparent;
            this.pnlPassword.Controls.Add(this.pnlColor3);
            this.pnlPassword.Controls.Add(this.pnlColor2);
            this.pnlPassword.Controls.Add(this.pnlNG);
            this.pnlPassword.Controls.Add(this.pnlOK);
            this.pnlPassword.Controls.Add(this.pnlColor1);
            this.pnlPassword.Controls.Add(this.lblOldPassword);
            this.pnlPassword.Controls.Add(this.txtConfirmPassword);
            this.pnlPassword.Controls.Add(this.txtOldPassword);
            this.pnlPassword.Controls.Add(this.lblValidatePassword);
            this.pnlPassword.Controls.Add(this.lblNewPassword);
            this.pnlPassword.Controls.Add(this.txtNewPassword);
            this.pnlPassword.Dock = DockStyle.Top;
            this.pnlPassword.Location = new Point(3, 51);
            this.pnlPassword.Name = "pnlPassword";
            this.pnlPassword.Size = new Size(390, 117);
            this.pnlPassword.TabIndex = 2;
            this.pnlColor3.BackColor = Color.Transparent;
            this.pnlColor3.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlColor3.Location = new Point(335, 44);
            this.pnlColor3.Name = "pnlColor3";
            this.pnlColor3.Size = new Size(16, 16);
            this.pnlColor3.TabIndex = 3;
            this.pnlColor3.Tag = "9999";
            this.pnlColor2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlColor2.Location = new Point(318, 44);
            this.pnlColor2.Name = "pnlColor2";
            this.pnlColor2.Size = new Size(16, 16);
            this.pnlColor2.TabIndex = 3;
            this.pnlColor2.Tag = "9999";
            this.pnlNG.BackgroundImage = Resources.mAlarm;
            this.pnlNG.Location = new Point(301, 77);
            this.pnlNG.Name = "pnlNG";
            this.pnlNG.Size = new Size(16, 16);
            this.pnlNG.TabIndex = 3;
            this.pnlNG.Tag = "9999";
            this.pnlNG.Visible = false;
            this.pnlOK.Location = new Point(301, 77);
            this.pnlOK.Name = "pnlOK";
            this.pnlOK.Size = new Size(16, 16);
            this.pnlOK.TabIndex = 3;
            this.pnlOK.Tag = "9999";
            this.pnlColor1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlColor1.Location = new Point(301, 44);
            this.pnlColor1.Name = "pnlColor1";
            this.pnlColor1.Size = new Size(16, 16);
            this.pnlColor1.TabIndex = 3;
            this.pnlColor1.Tag = "9999";
            this.lblOldPassword.AutoSize = true;
            this.lblOldPassword.Location = new Point(71, 11);
            this.lblOldPassword.Name = "lblOldPassword";
            this.lblOldPassword.Size = new Size(53, 12);
            this.lblOldPassword.TabIndex = 0;
            this.lblOldPassword.Text = "原密码：";
            this.txtConfirmPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtConfirmPassword.Location = new Point(130, 76);
            this.txtConfirmPassword.MaxLength = 32;
            this.txtConfirmPassword.Name = "txtConfirmPassword";
            this.txtConfirmPassword.PasswordChar = '*';
            this.txtConfirmPassword.Size = new Size(161, 21);
            this.txtConfirmPassword.TabIndex = 2;
            this.txtConfirmPassword.TextChanged += new EventHandler(this.txtNewPassword_TextChanged);
            this.txtOldPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtOldPassword.Location = new Point(130, 8);
            this.txtOldPassword.MaxLength = 32;
            this.txtOldPassword.Name = "txtOldPassword";
            this.txtOldPassword.PasswordChar = '*';
            this.txtOldPassword.Size = new Size(161, 21);
            this.txtOldPassword.TabIndex = 0;
            this.lblValidatePassword.AutoSize = true;
            this.lblValidatePassword.Location = new Point(59, 81);
            this.lblValidatePassword.Name = "lblValidatePassword";
            this.lblValidatePassword.Size = new Size(65, 12);
            this.lblValidatePassword.TabIndex = 0;
            this.lblValidatePassword.Text = "确认密码：";
            this.lblNewPassword.AutoSize = true;
            this.lblNewPassword.Location = new Point(71, 48);
            this.lblNewPassword.Name = "lblNewPassword";
            this.lblNewPassword.Size = new Size(53, 12);
            this.lblNewPassword.TabIndex = 0;
            this.lblNewPassword.Text = "新密码：";
            this.txtNewPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNewPassword.Location = new Point(130, 42);
            this.txtNewPassword.MaxLength = 32;
            this.txtNewPassword.Name = "txtNewPassword";
            this.txtNewPassword.PasswordChar = '*';
            this.txtNewPassword.Size = new Size(161, 21);
            this.txtNewPassword.TabIndex = 1;
            this.txtNewPassword.TextChanged += new EventHandler(this.txtNewPassword_TextChanged);
            this.pnlUserId.Controls.Add(this.lblUserId);
            this.pnlUserId.Controls.Add(this.txtUserId);
            this.pnlUserId.Dock = DockStyle.Top;
            this.pnlUserId.Location = new Point(3, 17);
            this.pnlUserId.Name = "pnlUserId";
            this.pnlUserId.Size = new Size(390, 34);
            this.pnlUserId.TabIndex = 1;
            this.lblUserId.AutoSize = true;
            this.lblUserId.Location = new Point(71, 10);
            this.lblUserId.Name = "lblUserId";
            this.lblUserId.Size = new Size(53, 12);
            this.lblUserId.TabIndex = 0;
            this.lblUserId.Text = "用户名：";
            this.txtUserId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtUserId.Location = new Point(130, 7);
            this.txtUserId.MaxLength = 20;
            this.txtUserId.Name = "txtUserId";
            this.txtUserId.Size = new Size(161, 21);
            this.txtUserId.TabIndex = 0;
            this.btnOK.Location = new Point(253, 186);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(75, 23);
            this.btnOK.TabIndex = 0;
            this.btnOK.Text = "确定";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.DialogResult =  System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new Point(331, 186);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(75, 23);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "取消";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new EventHandler(this.btnCancel_Click);
            base.AcceptButton = this.btnOK;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            base.CancelButton = this.btnCancel;
            base.ClientSize = new Size(422, 222);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.btnOK);
            base.Controls.Add(this.grpPassword);
            base.FormBorderStyle =  System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.Icon = (Icon)resources.GetObject("$this.Icon");
            base.Name = "itmSetPass";
            base.Padding = new Padding(10);
            this.Text = "修改密码";
            this.grpPassword.ResumeLayout(false);
            this.pnlPassword.ResumeLayout(false);
            this.pnlPassword.PerformLayout();
            this.pnlUserId.ResumeLayout(false);
            this.pnlUserId.PerformLayout();
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private bool bLoginForm;
        private GroupBox grpPassword;
        private Label lblNewPassword;
        private Label lblOldPassword;
        private Label lblUserId;
        private Label lblValidatePassword;
        private Panel pnlColor1;
        private Panel pnlColor2;
        private Panel pnlColor3;
        private Panel pnlNG;
        private Panel pnlOK;
        private Panel pnlPassword;
        private Panel pnlUserId;
        private TextBox txtConfirmPassword;
        private TextBox txtNewPassword;
        private TextBox txtOldPassword;
        private TextBox txtUserId;
    }
}