namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class itmSetRegionAlarm
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(itmSetRegionAlarm));
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.grpArea = new GroupBox();
            this.dgvArea = new DataGridViewEx();
            this.regionName = new DataGridViewTextBoxColumn();
            this.InRegion = new DataGridViewCheckBoxColumn();
            this.OutRegion = new DataGridViewCheckBoxColumn();
            this.MainRegion = new DataGridViewCheckBoxColumn();
            this.InOutRegion = new DataGridViewCheckBoxColumn();
            this.ColseGSm = new DataGridViewCheckBoxColumn();
            this.ColseData = new DataGridViewCheckBoxColumn();
            this.StartPoint = new DataGridViewCheckBoxColumn();
            this.PassPoint = new DataGridViewCheckBoxColumn();
            this.EndPoint = new DataGridViewCheckBoxColumn();
            this.distanceToBegin = new DataGridViewTextBoxColumn();
            this.distanceToEnd = new DataGridViewTextBoxColumn();
            this.planUpBeginTime = new DataGridViewTextBoxColumn();
            this.planDownBeginTime = new DataGridViewTextBoxColumn();
            this.StopPoint = new DataGridViewCheckBoxColumn();
            this.beginTime = new DataGridViewTextBoxColumn();
            this.endTime = new DataGridViewTextBoxColumn();
            this.AlarmCondition = new DataGridViewTextBoxColumn();
            this.regionId = new DataGridViewTextBoxColumn();
            this.regionDot = new DataGridViewTextBoxColumn();
            this.pnlFilter = new Panel();
            this.comboBoxLines = new ComboBox();
            this.toolStrip1 = new ToolStrip();
            this.tsBtnFilter = new ToolStripButton();
            this.lbLine = new Label();
            this.panel1 = new Panel();
            this.lblExplain = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpArea.SuspendLayout();
            ((ISupportInitialize) this.dgvArea).BeginInit();
            this.pnlFilter.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            base.grpCar.Size = new Size(650, 116);
            base.grpCar.TabIndex = 0;
            base.pnlBtn.Dock = DockStyle.Bottom;
            base.pnlBtn.Location = new System.Drawing.Point(5, 404);
            base.pnlBtn.Size = new Size(650, 28);
            base.pnlBtn.TabIndex = 2;
            base.btnCancel.Location = new System.Drawing.Point(312, 0);
            base.btnCancel.TabIndex = 1;
            base.btnOK.Location = new System.Drawing.Point(231, 0);
            base.btnOK.TabIndex = 0;
            this.grpArea.Controls.Add(this.dgvArea);
            this.grpArea.Controls.Add(this.pnlFilter);
            this.grpArea.Controls.Add(this.panel1);
            this.grpArea.Dock = DockStyle.Fill;
            this.grpArea.Location = new System.Drawing.Point(5, 121);
            this.grpArea.Name = "grpArea";
            this.grpArea.Size = new Size(650, 283);
            this.grpArea.TabIndex = 1;
            this.grpArea.TabStop = false;
            this.grpArea.Text = "预设区域";
            this.dgvArea.AllowUserToAddRows = false;
            this.dgvArea.AllowUserToResizeRows = false;
            this.dgvArea.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
            this.dgvArea.BackgroundColor = SystemColors.ControlLightLight;
            this.dgvArea.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvArea.Columns.AddRange(new DataGridViewColumn[] { 
                this.regionName, this.InRegion, this.OutRegion, this.MainRegion, this.InOutRegion, this.ColseGSm, this.ColseData, this.StartPoint, this.PassPoint, this.EndPoint, this.distanceToBegin, this.distanceToEnd, this.planUpBeginTime, this.planDownBeginTime, this.StopPoint, this.beginTime, 
                this.endTime, this.AlarmCondition, this.regionId, this.regionDot
             });
            this.dgvArea.Dock = DockStyle.Fill;
            this.dgvArea.ImeMode =  System.Windows.Forms.ImeMode.Disable;
            this.dgvArea.Location = new System.Drawing.Point(3, 43);
            this.dgvArea.Name = "dgvArea";
            this.dgvArea.NotMultiSelectedColumnName = (List<string>)resources.GetObject("dgvArea.NotMultiSelectedColumnName");
            this.dgvArea.RowHeadersVisible = false;
            this.dgvArea.RowTemplate.Height = 20;
            this.dgvArea.SelectionMode = DataGridViewSelectionMode.CellSelect;
            this.dgvArea.Size = new Size(644, 205);
            this.dgvArea.TabIndex = 0;
            this.dgvArea.CellValueChanged += new DataGridViewCellEventHandler(this.dgvArea_CellValueChanged);
            this.dgvArea.CellMouseUp += new DataGridViewCellMouseEventHandler(this.dgvArea_CellMouseUp);
            this.dgvArea.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvArea_CellDoubleClick);
            this.dgvArea.CellClick += new DataGridViewCellEventHandler(this.dgvArea_CellClick);
            this.dgvArea.KeyPress += new KeyPressEventHandler(this.dgvArea_KeyPress);
            this.regionName.DataPropertyName = "regionName";
            style.BackColor = Color.FromArgb(192, 192, 255);
            this.regionName.DefaultCellStyle = style;
            this.regionName.Frozen = true;
            this.regionName.HeaderText = "区域名称";
            this.regionName.MinimumWidth = 60;
            this.regionName.Name = "regionName";
            this.regionName.ReadOnly = true;
            this.regionName.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.regionName.Width = 60;
            this.InRegion.DataPropertyName = "InRegion";
            this.InRegion.FalseValue = "False";
            this.InRegion.HeaderText = "进入";
            this.InRegion.MinimumWidth = 45;
            this.InRegion.Name = "InRegion";
            this.InRegion.TrueValue = "True";
            this.InRegion.Width = 45;
            this.OutRegion.DataPropertyName = "OutRegion";
            this.OutRegion.FalseValue = "False";
            this.OutRegion.HeaderText = "越出";
            this.OutRegion.MinimumWidth = 45;
            this.OutRegion.Name = "OutRegion";
            this.OutRegion.TrueValue = "True";
            this.OutRegion.Width = 45;
            this.MainRegion.DataPropertyName = "MainRegion";
            this.MainRegion.FalseValue = "False";
            this.MainRegion.HeaderText = "主区域";
            this.MainRegion.MinimumWidth = 60;
            this.MainRegion.Name = "MainRegion";
            this.MainRegion.TrueValue = "True";
            this.MainRegion.Width = 60;
            this.InOutRegion.DataPropertyName = "InOutRegion";
            this.InOutRegion.FalseValue = "False";
            this.InOutRegion.HeaderText = "进入/越出";
            this.InOutRegion.MinimumWidth = 75;
            this.InOutRegion.Name = "InOutRegion";
            this.InOutRegion.TrueValue = "True";
            this.InOutRegion.Width = 75;
            this.ColseGSm.DataPropertyName = "ColseGSm";
            this.ColseGSm.FalseValue = "False";
            this.ColseGSm.HeaderText = "关闭GSM模块";
            this.ColseGSm.MinimumWidth = 90;
            this.ColseGSm.Name = "ColseGSm";
            this.ColseGSm.ReadOnly = true;
            this.ColseGSm.Resizable = DataGridViewTriState.False;
            this.ColseGSm.TrueValue = "True";
            this.ColseGSm.Width = 90;
            this.ColseData.DataPropertyName = "ColseData";
            this.ColseData.FalseValue = "False";
            this.ColseData.HeaderText = "关闭数据拨号";
            this.ColseData.MinimumWidth = 90;
            this.ColseData.Name = "ColseData";
            this.ColseData.ReadOnly = true;
            this.ColseData.Resizable = DataGridViewTriState.False;
            this.ColseData.TrueValue = "True";
            this.ColseData.Width = 90;
            this.StartPoint.DataPropertyName = "StartPoint";
            this.StartPoint.FalseValue = "False";
            this.StartPoint.HeaderText = "起点站";
            this.StartPoint.MinimumWidth = 60;
            this.StartPoint.Name = "StartPoint";
            this.StartPoint.TrueValue = "True";
            this.StartPoint.Width = 60;
            this.PassPoint.DataPropertyName = "PassPoint";
            this.PassPoint.FalseValue = "False";
            this.PassPoint.HeaderText = "经停站";
            this.PassPoint.MinimumWidth = 60;
            this.PassPoint.Name = "PassPoint";
            this.PassPoint.TrueValue = "True";
            this.PassPoint.Width = 60;
            this.EndPoint.DataPropertyName = "EndPoint";
            this.EndPoint.FalseValue = "False";
            this.EndPoint.HeaderText = "终点站";
            this.EndPoint.MinimumWidth = 60;
            this.EndPoint.Name = "EndPoint";
            this.EndPoint.TrueValue = "True";
            this.EndPoint.Width = 60;
            this.distanceToBegin.DataPropertyName = "distanceToBegin";
            this.distanceToBegin.HeaderText = "去程车程时长(小时)";
            this.distanceToBegin.MinimumWidth = 120;
            this.distanceToBegin.Name = "distanceToBegin";
            this.distanceToBegin.ReadOnly = true;
            this.distanceToBegin.Resizable = DataGridViewTriState.False;
            this.distanceToBegin.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.distanceToBegin.Width = 120;
            this.distanceToEnd.DataPropertyName = "distanceToEnd";
            this.distanceToEnd.HeaderText = "返程车程时长(小时)";
            this.distanceToEnd.MinimumWidth = 120;
            this.distanceToEnd.Name = "distanceToEnd";
            this.distanceToEnd.ReadOnly = true;
            this.distanceToEnd.Resizable = DataGridViewTriState.False;
            this.distanceToEnd.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.distanceToEnd.Width = 120;
            this.planUpBeginTime.DataPropertyName = "planUpBeginTime";
            this.planUpBeginTime.HeaderText = "去程规定始发时间";
            this.planUpBeginTime.MinimumWidth = 120;
            this.planUpBeginTime.Name = "planUpBeginTime";
            this.planUpBeginTime.ReadOnly = true;
            this.planUpBeginTime.Resizable = DataGridViewTriState.False;
            this.planUpBeginTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.planUpBeginTime.Width = 120;
            this.planDownBeginTime.DataPropertyName = "planDownBeginTime";
            this.planDownBeginTime.HeaderText = "返程规定始发时间";
            this.planDownBeginTime.MinimumWidth = 120;
            this.planDownBeginTime.Name = "planDownBeginTime";
            this.planDownBeginTime.ReadOnly = true;
            this.planDownBeginTime.Resizable = DataGridViewTriState.False;
            this.planDownBeginTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.planDownBeginTime.Width = 120;
            this.StopPoint.DataPropertyName = "StopPoint";
            this.StopPoint.FalseValue = "False";
            this.StopPoint.HeaderText = "停车点";
            this.StopPoint.MinimumWidth = 60;
            this.StopPoint.Name = "StopPoint";
            this.StopPoint.Resizable = DataGridViewTriState.False;
            this.StopPoint.TrueValue = "True";
            this.StopPoint.Width = 60;
            this.beginTime.DataPropertyName = "beginTime";
            this.beginTime.HeaderText = "起始时间";
            this.beginTime.MaxInputLength = 19;
            this.beginTime.MinimumWidth = 60;
            this.beginTime.Name = "beginTime";
            this.beginTime.ReadOnly = true;
            this.beginTime.Resizable = DataGridViewTriState.False;
            this.beginTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.beginTime.Width = 60;
            this.endTime.DataPropertyName = "endTime";
            this.endTime.HeaderText = "终止时间";
            this.endTime.MaxInputLength = 19;
            this.endTime.MinimumWidth = 60;
            this.endTime.Name = "endTime";
            this.endTime.ReadOnly = true;
            this.endTime.Resizable = DataGridViewTriState.False;
            this.endTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.endTime.Width = 60;
            this.AlarmCondition.DataPropertyName = "AlarmCondition";
            this.AlarmCondition.HeaderText = "允许报警条件";
            this.AlarmCondition.MinimumWidth = 100;
            this.AlarmCondition.Name = "AlarmCondition";
            this.AlarmCondition.ReadOnly = true;
            this.AlarmCondition.Resizable = DataGridViewTriState.False;
            this.AlarmCondition.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.regionId.DataPropertyName = "regionId";
            this.regionId.HeaderText = "区域ID";
            this.regionId.Name = "regionId";
            this.regionId.Visible = false;
            this.regionId.Width = 66;
            this.regionDot.DataPropertyName = "regionDot";
            this.regionDot.HeaderText = "区域点坐标集";
            this.regionDot.Name = "regionDot";
            this.regionDot.Visible = false;
            this.regionDot.Width = 102;
            this.pnlFilter.Controls.Add(this.comboBoxLines);
            this.pnlFilter.Controls.Add(this.toolStrip1);
            this.pnlFilter.Controls.Add(this.lbLine);
            this.pnlFilter.Dock = DockStyle.Top;
            this.pnlFilter.Location = new System.Drawing.Point(3, 17);
            this.pnlFilter.Name = "pnlFilter";
            this.pnlFilter.Size = new Size(644, 26);
            this.pnlFilter.TabIndex = 3;
            this.comboBoxLines.DisplayMember = "PathgroupName";
            this.comboBoxLines.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBoxLines.FormattingEnabled = true;
            this.comboBoxLines.ImeMode =  System.Windows.Forms.ImeMode.NoControl;
            this.comboBoxLines.Location = new System.Drawing.Point(123, 3);
            this.comboBoxLines.Name = "comboBoxLines";
            this.comboBoxLines.Size = new Size(157, 20);
            this.comboBoxLines.TabIndex = 3;
            this.comboBoxLines.Tag = "999";
            this.comboBoxLines.ValueMember = "PathgroupID";
            this.toolStrip1.Dock = DockStyle.None;
            this.toolStrip1.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStrip1.Items.AddRange(new ToolStripItem[] { this.tsBtnFilter });
            this.toolStrip1.Location = new System.Drawing.Point(285, 1);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new Size(26, 25);
            this.toolStrip1.TabIndex = 2;
            this.toolStrip1.Text = "toolStrip1";
            this.tsBtnFilter.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.tsBtnFilter.Image = Resources.find;
            this.tsBtnFilter.ImageTransparentColor = Color.Magenta;
            this.tsBtnFilter.Name = "tsBtnFilter";
            this.tsBtnFilter.Size = new Size(23, 22);
            this.tsBtnFilter.Text = "搜索 ";
            this.tsBtnFilter.Click += new EventHandler(this.tsBtnFilter_Click);
            this.lbLine.AutoSize = true;
            this.lbLine.Location = new System.Drawing.Point(23, 7);
            this.lbLine.Name = "lbLine";
            this.lbLine.Size = new Size(89, 12);
            this.lbLine.TabIndex = 1;
            this.lbLine.Tag = "999";
            this.lbLine.Text = "路线分组名称：";
            this.panel1.Controls.Add(this.lblExplain);
            this.panel1.Dock = DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(3, 248);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(644, 32);
            this.panel1.TabIndex = 2;
            this.lblExplain.AutoSize = true;
            this.lblExplain.ForeColor = Color.Red;
            this.lblExplain.Location = new System.Drawing.Point(26, 7);
            this.lblExplain.Name = "lblExplain";
            this.lblExplain.Size = new Size(269, 12);
            this.lblExplain.TabIndex = 2;
            this.lblExplain.Tag = "9999";
            this.lblExplain.Text = "如果要使用停车点数据，请使用进入越出区域报警";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            base.ClientSize = new Size(660, 437);
            base.Controls.Add(this.grpArea);
            base.FormBorderStyle =  System.Windows.Forms.FormBorderStyle.Sizable;
            base.MaximizeBox = true;
            base.Name = "itmSetRegionAlarm";
            this.Text = "SetAreaAlarm";
            base.Load += new EventHandler(this.SetAreaAlarm_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.Controls.SetChildIndex(this.grpArea, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpArea.ResumeLayout(false);
            ((ISupportInitialize) this.dgvArea).EndInit();
            this.pnlFilter.ResumeLayout(false);
            this.pnlFilter.PerformLayout();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private DataGridViewTextBoxColumn AlarmCondition;
        private DataGridViewTextBoxColumn beginTime;
        private DataGridViewCheckBoxColumn ColseData;
        private DataGridViewCheckBoxColumn ColseGSm;
        private ComboBox comboBoxLines;
        private DataGridViewEx dgvArea;
        private DataGridViewTextBoxColumn distanceToBegin;
        private DataGridViewTextBoxColumn distanceToEnd;
        private DataGridViewCheckBoxColumn EndPoint;
        private DataGridViewTextBoxColumn endTime;
        private GroupBox grpArea;
        private DataGridViewCheckBoxColumn InOutRegion;
        private DataGridViewCheckBoxColumn InRegion;
        private Label lblExplain;
        private Label lbLine;
        private string m_sCustName;
        private DataGridViewCheckBoxColumn MainRegion;
        private DataGridViewCheckBoxColumn OutRegion;
        private Panel panel1;
        private DataGridViewCheckBoxColumn PassPoint;
        private DataGridViewTextBoxColumn planDownBeginTime;
        private DataGridViewTextBoxColumn planUpBeginTime;
        private Panel pnlFilter;
        private DataGridViewTextBoxColumn regionDot;
        private DataGridViewTextBoxColumn regionId;
        private DataGridViewTextBoxColumn regionName;
        private DataGridViewCheckBoxColumn StartPoint;
        private DataGridViewCheckBoxColumn StopPoint;
        private ToolStrip toolStrip1;
        private ToolStripButton tsBtnFilter;
    }
}