namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class JTBitmSetPlatformRegionAlarm
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(JTBitmSetPlatformRegionAlarm));
            this.grpSelectRoute = new GroupBox();
            this.dgvDataList = new DataGridViewEx();
            this.pnlFilter = new Panel();
            this.comboBoxLines = new ComboBox();
            this.toolStrip1 = new ToolStrip();
            this.tsBtnFilter = new ToolStripButton();
            this.lbLine = new Label();
            this.pnlWait = new Panel();
            this.pbPicWait = new PictureBox();
            this.lblWaitText = new Label();
            this.区域名称 = new DataGridViewTextBoxColumn();
            this.区域ID = new DataGridViewTextBoxColumn();
            this.选择 = new DataGridViewCheckBoxColumn();
            this.进入 = new DataGridViewCheckBoxColumn();
            this.越出 = new DataGridViewCheckBoxColumn();
            this.inRegion = new DataGridViewCheckBoxColumn();
            this.outRegion = new DataGridViewCheckBoxColumn();
            this.开始时间 = new DataGridViewTextBoxColumn();
            this.结束时间 = new DataGridViewTextBoxColumn();
            this.分组ID = new DataGridViewTextBoxColumn();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpSelectRoute.SuspendLayout();
            ((ISupportInitialize) this.dgvDataList).BeginInit();
            this.pnlFilter.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.pnlWait.SuspendLayout();
            ((ISupportInitialize) this.pbPicWait).BeginInit();
            base.SuspendLayout();
            base.grpCar.Size = new Size(626, 116);
            base.pnlBtn.Controls.Add(this.pnlWait);
            base.pnlBtn.Location = new System.Drawing.Point(5, 367);
            base.pnlBtn.Size = new Size(626, 28);
            base.pnlBtn.Controls.SetChildIndex(base.btnOK, 0);
            base.pnlBtn.Controls.SetChildIndex(base.btnCancel, 0);
            base.pnlBtn.Controls.SetChildIndex(this.pnlWait, 0);
            base.btnCancel.Location = new System.Drawing.Point(548, 5);
            base.btnOK.Location = new System.Drawing.Point(463, 5);
            this.grpSelectRoute.Controls.Add(this.dgvDataList);
            this.grpSelectRoute.Controls.Add(this.pnlFilter);
            this.grpSelectRoute.Dock = DockStyle.Top;
            this.grpSelectRoute.Location = new System.Drawing.Point(5, 121);
            this.grpSelectRoute.Margin = new Padding(0);
            this.grpSelectRoute.Name = "grpSelectRoute";
            this.grpSelectRoute.Size = new Size(626, 246);
            this.grpSelectRoute.TabIndex = 11;
            this.grpSelectRoute.TabStop = false;
            this.grpSelectRoute.Text = "选择预设路线名称";
            this.dgvDataList.AllowUserToAddRows = false;
            this.dgvDataList.BackgroundColor = SystemColors.ControlLightLight;
            this.dgvDataList.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDataList.Columns.AddRange(new DataGridViewColumn[] { this.区域名称, this.区域ID, this.选择, this.进入, this.越出, this.inRegion, this.outRegion, this.开始时间, this.结束时间, this.分组ID });
            this.dgvDataList.Dock = DockStyle.Fill;
            this.dgvDataList.Location = new System.Drawing.Point(3, 43);
            this.dgvDataList.Name = "dgvDataList";
            this.dgvDataList.NotMultiSelectedColumnName = (List<string>)resources.GetObject("dgvDataList.NotMultiSelectedColumnName");
            this.dgvDataList.RowHeadersVisible = false;
            this.dgvDataList.RowTemplate.Height = 23;
            this.dgvDataList.Size = new Size(620, 200);
            this.dgvDataList.TabIndex = 4;
            this.dgvDataList.CellMouseUp += new DataGridViewCellMouseEventHandler(this.dgvDataList_CellMouseUp);
            this.dgvDataList.CellBeginEdit += new DataGridViewCellCancelEventHandler(this.dgvDataList_CellBeginEdit);
            this.dgvDataList.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvDataList_CellDoubleClick);
            this.dgvDataList.CellEndEdit += new DataGridViewCellEventHandler(this.dgvDataList_CellEndEdit);
            this.pnlFilter.Controls.Add(this.comboBoxLines);
            this.pnlFilter.Controls.Add(this.toolStrip1);
            this.pnlFilter.Controls.Add(this.lbLine);
            this.pnlFilter.Dock = DockStyle.Top;
            this.pnlFilter.Location = new System.Drawing.Point(3, 17);
            this.pnlFilter.Name = "pnlFilter";
            this.pnlFilter.Size = new Size(620, 26);
            this.pnlFilter.TabIndex = 3;
            this.comboBoxLines.DisplayMember = "PathgroupName";
            this.comboBoxLines.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBoxLines.FormattingEnabled = true;
            this.comboBoxLines.ImeMode =  System.Windows.Forms.ImeMode.NoControl;
            this.comboBoxLines.Location = new System.Drawing.Point(101, 3);
            this.comboBoxLines.Name = "comboBoxLines";
            this.comboBoxLines.Size = new Size(106, 20);
            this.comboBoxLines.TabIndex = 3;
            this.comboBoxLines.Tag = "999";
            this.comboBoxLines.ValueMember = "PathgroupID";
            this.toolStrip1.Dock = DockStyle.None;
            this.toolStrip1.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStrip1.Items.AddRange(new ToolStripItem[] { this.tsBtnFilter });
            this.toolStrip1.Location = new System.Drawing.Point(210, 1);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new Size(26, 25);
            this.toolStrip1.TabIndex = 2;
            this.toolStrip1.Text = "toolStrip1";
            this.tsBtnFilter.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.tsBtnFilter.Image = Resources.find;
            this.tsBtnFilter.ImageTransparentColor = Color.Magenta;
            this.tsBtnFilter.Name = "tsBtnFilter";
            this.tsBtnFilter.Size = new Size(23, 22);
            this.tsBtnFilter.Text = "搜索 ";
            this.tsBtnFilter.Click += new EventHandler(this.tsBtnFilter_Click);
            this.lbLine.AutoSize = true;
            this.lbLine.Location = new System.Drawing.Point(5, 7);
            this.lbLine.Name = "lbLine";
            this.lbLine.Size = new Size(89, 12);
            this.lbLine.TabIndex = 1;
            this.lbLine.Tag = "999";
            this.lbLine.Text = "区域分组名称：";
            this.pnlWait.Controls.Add(this.pbPicWait);
            this.pnlWait.Controls.Add(this.lblWaitText);
            this.pnlWait.Location = new System.Drawing.Point(6, 3);
            this.pnlWait.Name = "pnlWait";
            this.pnlWait.Size = new Size(129, 22);
            this.pnlWait.TabIndex = 14;
            this.pnlWait.Tag = "9999";
            this.pbPicWait.BackColor = Color.Transparent;
            this.pbPicWait.Image = Resources.loading;
            this.pbPicWait.InitialImage = null;
            this.pbPicWait.Location = new System.Drawing.Point(3, 3);
            this.pbPicWait.Name = "pbPicWait";
            this.pbPicWait.Size = new Size(16, 16);
            this.pbPicWait.TabIndex = 11;
            this.pbPicWait.TabStop = false;
            this.pbPicWait.Tag = "9999";
            this.pbPicWait.Visible = false;
            this.lblWaitText.AutoSize = true;
            this.lblWaitText.Location = new System.Drawing.Point(22, 5);
            this.lblWaitText.Name = "lblWaitText";
            this.lblWaitText.Size = new Size(89, 12);
            this.lblWaitText.TabIndex = 9;
            this.lblWaitText.Text = "正在执行中....";
            this.lblWaitText.Visible = false;
            this.区域名称.DataPropertyName = "regionName";
            this.区域名称.Frozen = true;
            this.区域名称.HeaderText = "区域名称";
            this.区域名称.Name = "区域名称";
            this.区域名称.ReadOnly = true;
            this.区域ID.DataPropertyName = "regionid";
            this.区域ID.HeaderText = "区域ID";
            this.区域ID.Name = "区域ID";
            this.区域ID.ReadOnly = true;
            this.区域ID.Visible = false;
            this.选择.DataPropertyName = "isCheck";
            this.选择.FalseValue = "False";
            this.选择.HeaderText = "选择";
            this.选择.Name = "选择";
            this.选择.TrueValue = "True";
            this.选择.Width = 50;
            this.进入.DataPropertyName = "isin";
            this.进入.FalseValue = "False";
            this.进入.HeaderText = "进入";
            this.进入.Name = "进入";
            this.进入.TrueValue = "True";
            this.进入.Width = 50;
            this.越出.DataPropertyName = "isout";
            this.越出.FalseValue = "False";
            this.越出.HeaderText = "越出";
            this.越出.Name = "越出";
            this.越出.TrueValue = "True";
            this.越出.Width = 50;
            this.inRegion.DataPropertyName = "inRegion";
            this.inRegion.FalseValue = "False";
            this.inRegion.FillWeight = 75f;
            this.inRegion.HeaderText = "区域内";
            this.inRegion.Name = "inRegion";
            this.inRegion.Resizable = DataGridViewTriState.True;
            this.inRegion.TrueValue = "True";
            this.inRegion.Width = 75;
            this.outRegion.DataPropertyName = "outRegion";
            this.outRegion.FalseValue = "False";
            this.outRegion.FillWeight = 75f;
            this.outRegion.HeaderText = "区域外";
            this.outRegion.Name = "outRegion";
            this.outRegion.Resizable = DataGridViewTriState.True;
            this.outRegion.TrueValue = "True";
            this.outRegion.Width = 75;
            this.开始时间.DataPropertyName = "begintime";
            this.开始时间.HeaderText = "开始时间";
            this.开始时间.Name = "开始时间";
            this.开始时间.ReadOnly = true;
            this.开始时间.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.开始时间.Width = 120;
            this.结束时间.DataPropertyName = "endtime";
            this.结束时间.HeaderText = "结束时间";
            this.结束时间.Name = "结束时间";
            this.结束时间.ReadOnly = true;
            this.结束时间.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.结束时间.Width = 120;
            this.分组ID.DataPropertyName = "PathGroupID";
            this.分组ID.HeaderText = "分组ID";
            this.分组ID.Name = "分组ID";
            this.分组ID.ReadOnly = true;
            this.分组ID.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.分组ID.Visible = false;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(636, 400);
            base.Controls.Add(this.grpSelectRoute);
            base.Name = "JTBitmSetPlatformRegionAlarm";
            this.Text = "JTBitmSetRegionAlarm";
            base.Load += new EventHandler(this.JTBitmSetRegionAlarm_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpSelectRoute, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpSelectRoute.ResumeLayout(false);
            ((ISupportInitialize) this.dgvDataList).EndInit();
            this.pnlFilter.ResumeLayout(false);
            this.pnlFilter.PerformLayout();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.pnlWait.ResumeLayout(false);
            this.pnlWait.PerformLayout();
            ((ISupportInitialize) this.pbPicWait).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private ComboBox comboBoxLines;
        private DataGridViewEx dgvDataList;
        private GroupBox grpSelectRoute;
        private DataGridViewCheckBoxColumn inRegion;
        private Label lbLine;
        private Label lblWaitText;
        private DataGridViewCheckBoxColumn outRegion;
        private PictureBox pbPicWait;
        private Panel pnlFilter;
        private Panel pnlWait;
        private ToolStrip toolStrip1;
        private ToolStripButton tsBtnFilter;
        private DataGridViewTextBoxColumn 分组ID;
        private DataGridViewTextBoxColumn 结束时间;
        private DataGridViewCheckBoxColumn 进入;
        private DataGridViewTextBoxColumn 开始时间;
        private DataGridViewTextBoxColumn 区域ID;
        private DataGridViewTextBoxColumn 区域名称;
        private DataGridViewCheckBoxColumn 选择;
        private DataGridViewCheckBoxColumn 越出;
    }
}