namespace Client
{
    using Properties;
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class JTBitmSetPlatformPathSegmentAlarm
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(JTBitmSetPlatformPathSegmentAlarm));
            this.pnlWait = new Panel();
            this.pbPicWait = new PictureBox();
            this.lblWaitText = new Label();
            this.grpSelectRoute = new GroupBox();
            this.grpSegment = new GroupBox();
            this.dgvPathSegment = new DataGridViewEx();
            this.路段名称 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new DataGridViewTextBoxColumn();
            this.PathSegmentID = new DataGridViewTextBoxColumn();
            this.速度 = new DataGridViewTextBoxColumn();
            this.panel1 = new Panel();
            this.btnCloseGrpSegment = new Button();
            this.btnSegmentSet = new Button();
            this.clbSelectRoute = new DataGridViewEx();
            this.路线名称 = new DataGridViewTextBoxColumn();
            this.选择 = new DataGridViewCheckBoxColumn();
            this.PathID = new DataGridViewTextBoxColumn();
            this.设置 = new DataGridViewButtonColumn();
            this.pnlFilter = new Panel();
            this.toolStrip2 = new ToolStrip();
            this.tsBtnSearchdata = new ToolStripButton();
            this.txtFindRoad = new TextBox();
            this.lblFindRoad = new Label();
            this.comboBoxLines = new ComboBox();
            this.toolStrip1 = new ToolStrip();
            this.tsBtnFilter = new ToolStripButton();
            this.lbLine = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.pnlWait.SuspendLayout();
            ((ISupportInitialize) this.pbPicWait).BeginInit();
            this.grpSelectRoute.SuspendLayout();
            this.grpSegment.SuspendLayout();
            ((ISupportInitialize) this.dgvPathSegment).BeginInit();
            this.panel1.SuspendLayout();
            ((ISupportInitialize) this.clbSelectRoute).BeginInit();
            this.pnlFilter.SuspendLayout();
            this.toolStrip2.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            base.SuspendLayout();
            base.grpCar.Size = new Size(734, 116);
            base.pnlBtn.Controls.Add(this.pnlWait);
            base.pnlBtn.Location = new System.Drawing.Point(5, 462);
            base.pnlBtn.Size = new Size(734, 28);
            base.pnlBtn.Controls.SetChildIndex(this.pnlWait, 0);
            base.pnlBtn.Controls.SetChildIndex(base.btnOK, 0);
            base.pnlBtn.Controls.SetChildIndex(base.btnCancel, 0);
            this.pnlWait.Controls.Add(this.pbPicWait);
            this.pnlWait.Controls.Add(this.lblWaitText);
            this.pnlWait.Location = new System.Drawing.Point(3, 3);
            this.pnlWait.Name = "pnlWait";
            this.pnlWait.Size = new Size(129, 22);
            this.pnlWait.TabIndex = 15;
            this.pnlWait.Tag = "9999";
            this.pbPicWait.BackColor = Color.Transparent;
            this.pbPicWait.Image = Resources.loading;
            this.pbPicWait.InitialImage = null;
            this.pbPicWait.Location = new System.Drawing.Point(3, 3);
            this.pbPicWait.Name = "pbPicWait";
            this.pbPicWait.Size = new Size(16, 16);
            this.pbPicWait.TabIndex = 11;
            this.pbPicWait.TabStop = false;
            this.pbPicWait.Tag = "9999";
            this.pbPicWait.Visible = false;
            this.lblWaitText.AutoSize = true;
            this.lblWaitText.Location = new System.Drawing.Point(22, 5);
            this.lblWaitText.Name = "lblWaitText";
            this.lblWaitText.Size = new Size(89, 12);
            this.lblWaitText.TabIndex = 9;
            this.lblWaitText.Text = "正在执行中....";
            this.lblWaitText.Visible = false;
            this.grpSelectRoute.Controls.Add(this.clbSelectRoute);
            this.grpSelectRoute.Controls.Add(this.pnlFilter);
            this.grpSelectRoute.Controls.Add(this.grpSegment);
            this.grpSelectRoute.Dock = DockStyle.Top;
            this.grpSelectRoute.Location = new System.Drawing.Point(5, 121);
            this.grpSelectRoute.Margin = new Padding(0);
            this.grpSelectRoute.Name = "grpSelectRoute";
            this.grpSelectRoute.Size = new Size(734, 341);
            this.grpSelectRoute.TabIndex = 11;
            this.grpSelectRoute.TabStop = false;
            this.grpSelectRoute.Text = "参数设置";
            this.grpSegment.Controls.Add(this.dgvPathSegment);
            this.grpSegment.Controls.Add(this.panel1);
            this.grpSegment.Location = new System.Drawing.Point(263, 79);
            this.grpSegment.Name = "grpSegment";
            this.grpSegment.Size = new Size(406, 174);
            this.grpSegment.TabIndex = 5;
            this.grpSegment.TabStop = false;
            this.grpSegment.Text = "路段属性设置";
            this.dgvPathSegment.AllowUserToAddRows = false;
            this.dgvPathSegment.BackgroundColor = Color.White;
            this.dgvPathSegment.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvPathSegment.Columns.AddRange(new DataGridViewColumn[] { this.路段名称, this.dataGridViewTextBoxColumn2, this.PathSegmentID, this.速度 });
            this.dgvPathSegment.Dock = DockStyle.Fill;
            this.dgvPathSegment.Location = new System.Drawing.Point(3, 17);
            this.dgvPathSegment.Name = "dgvPathSegment";
            this.dgvPathSegment.NotMultiSelectedColumnName = (List<string>)resources.GetObject("dgvPathSegment.NotMultiSelectedColumnName");
            this.dgvPathSegment.RowHeadersVisible = false;
            this.dgvPathSegment.RowTemplate.Height = 23;
            this.dgvPathSegment.Size = new Size(400, 122);
            this.dgvPathSegment.TabIndex = 5;
            this.路段名称.DataPropertyName = "PathSegmentName";
            this.路段名称.Frozen = true;
            this.路段名称.HeaderText = "路段名称";
            this.路段名称.Name = "路段名称";
            this.路段名称.ReadOnly = true;
            this.dataGridViewTextBoxColumn2.DataPropertyName = "PathID";
            this.dataGridViewTextBoxColumn2.HeaderText = "PathID";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.ReadOnly = true;
            this.dataGridViewTextBoxColumn2.Visible = false;
            this.PathSegmentID.DataPropertyName = "PathSegmentID";
            this.PathSegmentID.HeaderText = "PathSegmentID";
            this.PathSegmentID.Name = "PathSegmentID";
            this.PathSegmentID.ReadOnly = true;
            this.PathSegmentID.Visible = false;
            this.速度.DataPropertyName = "Speed";
            this.速度.HeaderText = "速度";
            this.速度.Name = "速度";
            this.panel1.Controls.Add(this.btnCloseGrpSegment);
            this.panel1.Controls.Add(this.btnSegmentSet);
            this.panel1.Dock = DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(3, 139);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(400, 32);
            this.panel1.TabIndex = 0;
            this.btnCloseGrpSegment.Location = new System.Drawing.Point(212, 6);
            this.btnCloseGrpSegment.Name = "btnCloseGrpSegment";
            this.btnCloseGrpSegment.Size = new Size(75, 23);
            this.btnCloseGrpSegment.TabIndex = 2;
            this.btnCloseGrpSegment.Text = "关闭";
            this.btnCloseGrpSegment.UseVisualStyleBackColor = true;
            this.btnCloseGrpSegment.Click += new EventHandler(this.btnCloseGrpSegment_Click);
            this.btnSegmentSet.Location = new System.Drawing.Point(131, 6);
            this.btnSegmentSet.Name = "btnSegmentSet";
            this.btnSegmentSet.Size = new Size(75, 23);
            this.btnSegmentSet.TabIndex = 0;
            this.btnSegmentSet.Text = "设置";
            this.btnSegmentSet.UseVisualStyleBackColor = true;
            this.btnSegmentSet.Click += new EventHandler(this.btnSegmentSet_Click);
            this.clbSelectRoute.AllowUserToAddRows = false;
            this.clbSelectRoute.BackgroundColor = Color.White;
            this.clbSelectRoute.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.clbSelectRoute.Columns.AddRange(new DataGridViewColumn[] { this.路线名称, this.选择, this.PathID, this.设置 });
            this.clbSelectRoute.Dock = DockStyle.Fill;
            this.clbSelectRoute.Location = new System.Drawing.Point(3, 43);
            this.clbSelectRoute.Name = "clbSelectRoute";
            this.clbSelectRoute.NotMultiSelectedColumnName = (List<string>)resources.GetObject("clbSelectRoute.NotMultiSelectedColumnName");
            this.clbSelectRoute.RowHeadersVisible = false;
            this.clbSelectRoute.RowTemplate.Height = 23;
            this.clbSelectRoute.Size = new Size(728, 295);
            this.clbSelectRoute.TabIndex = 4;
            this.clbSelectRoute.CellContentClick += new DataGridViewCellEventHandler(this.clbSelectRoute_CellContentClick);
            this.路线名称.DataPropertyName = "PathName";
            this.路线名称.Frozen = true;
            this.路线名称.HeaderText = "路线名称";
            this.路线名称.Name = "路线名称";
            this.路线名称.ReadOnly = true;
            this.选择.DataPropertyName = "IsCheck";
            this.选择.FalseValue = "0";
            this.选择.HeaderText = "选择";
            this.选择.Name = "选择";
            this.选择.Resizable = DataGridViewTriState.True;
            this.选择.SortMode = DataGridViewColumnSortMode.Automatic;
            this.选择.TrueValue = "1";
            this.选择.Width = 36;
            this.PathID.DataPropertyName = "PathID";
            this.PathID.HeaderText = "PathID";
            this.PathID.Name = "PathID";
            this.PathID.ReadOnly = true;
            this.PathID.Visible = false;
            this.设置.DataPropertyName = "IsSet";
            this.设置.HeaderText = "设置";
            this.设置.Name = "设置";
            this.设置.Text = "";
            this.pnlFilter.Controls.Add(this.toolStrip2);
            this.pnlFilter.Controls.Add(this.txtFindRoad);
            this.pnlFilter.Controls.Add(this.lblFindRoad);
            this.pnlFilter.Controls.Add(this.comboBoxLines);
            this.pnlFilter.Controls.Add(this.toolStrip1);
            this.pnlFilter.Controls.Add(this.lbLine);
            this.pnlFilter.Dock = DockStyle.Top;
            this.pnlFilter.Location = new System.Drawing.Point(3, 17);
            this.pnlFilter.Name = "pnlFilter";
            this.pnlFilter.Size = new Size(728, 26);
            this.pnlFilter.TabIndex = 3;
            this.toolStrip2.Dock = DockStyle.None;
            this.toolStrip2.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStrip2.Items.AddRange(new ToolStripItem[] { this.tsBtnSearchdata });
            this.toolStrip2.Location = new System.Drawing.Point(380, 1);
            this.toolStrip2.Name = "toolStrip2";
            this.toolStrip2.Size = new Size(26, 25);
            this.toolStrip2.TabIndex = 9;
            this.toolStrip2.Text = "toolStrip2";
            this.toolStrip2.Visible = false;
            this.tsBtnSearchdata.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.tsBtnSearchdata.Image = Resources.find;
            this.tsBtnSearchdata.ImageTransparentColor = Color.Magenta;
            this.tsBtnSearchdata.Name = "tsBtnSearchdata";
            this.tsBtnSearchdata.Size = new Size(23, 22);
            this.tsBtnSearchdata.Text = "路线过滤查找";
            this.txtFindRoad.Location = new System.Drawing.Point(310, 3);
            this.txtFindRoad.Name = "txtFindRoad";
            this.txtFindRoad.Size = new Size(67, 21);
            this.txtFindRoad.TabIndex = 5;
            this.txtFindRoad.Tag = "9999";
            this.txtFindRoad.Visible = false;
            this.lblFindRoad.AutoSize = true;
            this.lblFindRoad.Location = new System.Drawing.Point(243, 7);
            this.lblFindRoad.Name = "lblFindRoad";
            this.lblFindRoad.Size = new Size(65, 12);
            this.lblFindRoad.TabIndex = 4;
            this.lblFindRoad.Text = "查找路线：";
            this.lblFindRoad.Visible = false;
            this.comboBoxLines.DisplayMember = "PathgroupName";
            this.comboBoxLines.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBoxLines.FormattingEnabled = true;
            this.comboBoxLines.ImeMode =  System.Windows.Forms.ImeMode.NoControl;
            this.comboBoxLines.Location = new System.Drawing.Point(101, 3);
            this.comboBoxLines.Name = "comboBoxLines";
            this.comboBoxLines.Size = new Size(106, 20);
            this.comboBoxLines.TabIndex = 3;
            this.comboBoxLines.Tag = "999";
            this.comboBoxLines.ValueMember = "PathgroupID";
            this.toolStrip1.Dock = DockStyle.None;
            this.toolStrip1.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStrip1.Items.AddRange(new ToolStripItem[] { this.tsBtnFilter });
            this.toolStrip1.Location = new System.Drawing.Point(210, 1);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new Size(26, 25);
            this.toolStrip1.TabIndex = 2;
            this.toolStrip1.Text = "toolStrip1";
            this.tsBtnFilter.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.tsBtnFilter.Image = Resources.find;
            this.tsBtnFilter.ImageTransparentColor = Color.Magenta;
            this.tsBtnFilter.Name = "tsBtnFilter";
            this.tsBtnFilter.Size = new Size(23, 22);
            this.tsBtnFilter.Text = "搜索 ";
            this.lbLine.AutoSize = true;
            this.lbLine.Location = new System.Drawing.Point(5, 7);
            this.lbLine.Name = "lbLine";
            this.lbLine.Size = new Size(89, 12);
            this.lbLine.TabIndex = 1;
            this.lbLine.Tag = "999";
            this.lbLine.Text = "路线分组名称：";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(744, 495);
            base.Controls.Add(this.grpSelectRoute);
            base.Name = "JTBitmSetPlatformPathSegmentAlarm";
            this.Text = "JTBitmSetPlatformPathSegmentAlarm";
            base.Load += new EventHandler(this.JTBitmSetPlatformPathSegmentAlarm_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpSelectRoute, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.pnlWait.ResumeLayout(false);
            this.pnlWait.PerformLayout();
            ((ISupportInitialize) this.pbPicWait).EndInit();
            this.grpSelectRoute.ResumeLayout(false);
            this.grpSegment.ResumeLayout(false);
            ((ISupportInitialize) this.dgvPathSegment).EndInit();
            this.panel1.ResumeLayout(false);
            ((ISupportInitialize) this.clbSelectRoute).EndInit();
            this.pnlFilter.ResumeLayout(false);
            this.pnlFilter.PerformLayout();
            this.toolStrip2.ResumeLayout(false);
            this.toolStrip2.PerformLayout();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private Button btnCloseGrpSegment;
        private Button btnSegmentSet;
        private DataGridViewEx clbSelectRoute;
        private ComboBox comboBoxLines;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private DataGridViewEx dgvPathSegment;
        private GroupBox grpSegment;
        private GroupBox grpSelectRoute;
        private Label lblFindRoad;
        private Label lbLine;
        private Label lblWaitText;
        private Panel panel1;
        private DataGridViewTextBoxColumn PathID;
        private DataGridViewTextBoxColumn PathSegmentID;
        private PictureBox pbPicWait;
        private Panel pnlFilter;
        private Panel pnlWait;
        private ToolStrip toolStrip1;
        private ToolStrip toolStrip2;
        private ToolStripButton tsBtnFilter;
        private ToolStripButton tsBtnSearchdata;
        private TextBox txtFindRoad;
        private DataGridViewTextBoxColumn 路段名称;
        private DataGridViewTextBoxColumn 路线名称;
        private DataGridViewButtonColumn 设置;
        private DataGridViewTextBoxColumn 速度;
        private DataGridViewCheckBoxColumn 选择;
    }
}