namespace Client
{
    using PublicClass;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class QueryMap
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(QueryMap));
            this.picLoadMap = new PictureBox();
            this.wbMap = new GisMap();
            this.pnlSetRegion = new Panel();
            this.pnlBtn = new Panel();
            this.pnlHandle = new Panel();
            this.pnlRadius = new Panel();
            this.numRadius = new NumericUpDown();
            this.label3 = new Label();
            this.lblRadius = new Label();
            this.label2 = new Label();
            this.btnZoonOut = new Button();
            this.btnZoomIn = new Button();
            this.btnMove = new Button();
            this.btnRectangle = new Button();
            this.btnSetCircle = new Button();
            this.btnSet = new Button();
            this.btnTool = new Button();
            this.pnlRegion = new Panel();
            this.btnCancel = new Button();
            this.btnSumit = new Button();
            this.panel1 = new Panel();
            ((ISupportInitialize) this.picLoadMap).BeginInit();
            this.pnlSetRegion.SuspendLayout();
            this.pnlBtn.SuspendLayout();
            this.pnlHandle.SuspendLayout();
            this.pnlRadius.SuspendLayout();
            this.numRadius.BeginInit();
            this.pnlRegion.SuspendLayout();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            this.picLoadMap.Image = (Image)resources.GetObject("picLoadMap.Image");
            this.picLoadMap.Location = new Point(181, 179);
            this.picLoadMap.Name = "picLoadMap";
            this.picLoadMap.Size = new Size(167, 33);
            this.picLoadMap.TabIndex = 4;
            this.picLoadMap.TabStop = false;
            this.wbMap.Dock = DockStyle.Fill;
            this.wbMap.IsWebBrowserContextMenuEnabled = false;
            this.wbMap.Location = new Point(0, 0);
            this.wbMap.MinimumSize = new Size(20, 20);
            this.wbMap.Name = "wbMap";
            this.wbMap.ScrollBarsEnabled = false;
            this.wbMap.Size = new Size(564, 433);
            this.wbMap.TabIndex = 5;
            this.wbMap.WebBrowserShortcutsEnabled = false;
            this.wbMap.MapMouseUp += new HtmlElementEventHandler(this.wbMap_MapMouseUp);
            this.wbMap.DocumentCompleted += new WebBrowserDocumentCompletedEventHandler(this.gisMap1_DocumentCompleted);
            this.pnlSetRegion.Controls.Add(this.pnlBtn);
            this.pnlSetRegion.Controls.Add(this.pnlRegion);
            this.pnlSetRegion.Dock = DockStyle.Left;
            this.pnlSetRegion.Location = new Point(0, 0);
            this.pnlSetRegion.Name = "pnlSetRegion";
            this.pnlSetRegion.Size = new Size(135, 433);
            this.pnlSetRegion.TabIndex = 7;
            this.pnlBtn.Controls.Add(this.pnlHandle);
            this.pnlBtn.Controls.Add(this.btnSet);
            this.pnlBtn.Controls.Add(this.btnTool);
            this.pnlBtn.Dock = DockStyle.Fill;
            this.pnlBtn.Location = new Point(0, 0);
            this.pnlBtn.Name = "pnlBtn";
            this.pnlBtn.Size = new Size(135, 372);
            this.pnlBtn.TabIndex = 0;
            this.pnlHandle.Controls.Add(this.pnlRadius);
            this.pnlHandle.Controls.Add(this.btnZoonOut);
            this.pnlHandle.Controls.Add(this.btnZoomIn);
            this.pnlHandle.Controls.Add(this.btnMove);
            this.pnlHandle.Controls.Add(this.btnRectangle);
            this.pnlHandle.Controls.Add(this.btnSetCircle);
            this.pnlHandle.Dock = DockStyle.Fill;
            this.pnlHandle.Location = new Point(0, 23);
            this.pnlHandle.Name = "pnlHandle";
            this.pnlHandle.Size = new Size(135, 326);
            this.pnlHandle.TabIndex = 4;
            this.pnlRadius.Controls.Add(this.numRadius);
            this.pnlRadius.Controls.Add(this.label3);
            this.pnlRadius.Controls.Add(this.lblRadius);
            this.pnlRadius.Controls.Add(this.label2);
            this.pnlRadius.Dock = DockStyle.Top;
            this.pnlRadius.Location = new Point(0, 260);
            this.pnlRadius.Name = "pnlRadius";
            this.pnlRadius.Size = new Size(135, 55);
            this.pnlRadius.TabIndex = 8;
            this.pnlRadius.Visible = false;
            this.numRadius.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numRadius.Location = new Point(45, 12);
            int[] bits = new int[4];
            bits[0] = 65535;
            this.numRadius.Maximum = new decimal(bits);
            int[] numArray2 = new int[4];
            numArray2[0] = 10;
            this.numRadius.Minimum = new decimal(numArray2);
            this.numRadius.Name = "numRadius";
            this.numRadius.Size = new Size(66, 21);
            this.numRadius.TabIndex = 5;
            int[] numArray3 = new int[4];
            numArray3[0] = 500;
            this.numRadius.Value = new decimal(numArray3);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(46, 37);
            this.label3.Name = "label3";
            this.label3.Size = new Size(71, 12);
            this.label3.TabIndex = 6;
            this.label3.Text = "(10～65535)";
            this.lblRadius.AutoSize = true;
            this.lblRadius.Location = new Point(5, 16);
            this.lblRadius.Name = "lblRadius";
            this.lblRadius.Size = new Size(41, 12);
            this.lblRadius.TabIndex = 2;
            this.lblRadius.Text = "半径：";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(114, 16);
            this.label2.Name = "label2";
            this.label2.Size = new Size(17, 12);
            this.label2.TabIndex = 4;
            this.label2.Text = "米";
            this.btnZoonOut.Dock = DockStyle.Top;
            this.btnZoonOut.FlatStyle = FlatStyle.Popup;
            this.btnZoonOut.Image = (Image)resources.GetObject("btnZoonOut.Image");
            this.btnZoonOut.ImageAlign = ContentAlignment.TopCenter;
            this.btnZoonOut.Location = new Point(0, 208);
            this.btnZoonOut.Name = "btnZoonOut";
            this.btnZoonOut.Padding = new Padding(5);
            this.btnZoonOut.Size = new Size(135, 52);
            this.btnZoonOut.TabIndex = 5;
            this.btnZoonOut.Tag = "9999";
            this.btnZoonOut.Text = "缩小";
            this.btnZoonOut.TextAlign = ContentAlignment.BottomCenter;
            this.btnZoonOut.UseVisualStyleBackColor = true;
            this.btnZoonOut.Visible = false;
            this.btnZoonOut.Click += new EventHandler(this.btnZoomDown_Click);
            this.btnZoomIn.Dock = DockStyle.Top;
            this.btnZoomIn.FlatStyle = FlatStyle.Popup;
            this.btnZoomIn.Image = (Image)resources.GetObject("btnZoomIn.Image");
            this.btnZoomIn.ImageAlign = ContentAlignment.TopCenter;
            this.btnZoomIn.Location = new Point(0, 156);
            this.btnZoomIn.Name = "btnZoomIn";
            this.btnZoomIn.Padding = new Padding(5);
            this.btnZoomIn.Size = new Size(135, 52);
            this.btnZoomIn.TabIndex = 4;
            this.btnZoomIn.Tag = "9999";
            this.btnZoomIn.Text = "放大";
            this.btnZoomIn.TextAlign = ContentAlignment.BottomCenter;
            this.btnZoomIn.UseVisualStyleBackColor = true;
            this.btnZoomIn.Visible = false;
            this.btnZoomIn.Click += new EventHandler(this.btnZoomUp_Click);
            this.btnMove.Dock = DockStyle.Top;
            this.btnMove.FlatStyle = FlatStyle.Popup;
            this.btnMove.Image = (Image)resources.GetObject("btnMove.Image");
            this.btnMove.ImageAlign = ContentAlignment.TopCenter;
            this.btnMove.Location = new Point(0, 104);
            this.btnMove.Name = "btnMove";
            this.btnMove.Padding = new Padding(5);
            this.btnMove.Size = new Size(135, 52);
            this.btnMove.TabIndex = 3;
            this.btnMove.Tag = "9999";
            this.btnMove.Text = "移动";
            this.btnMove.TextAlign = ContentAlignment.BottomCenter;
            this.btnMove.UseVisualStyleBackColor = true;
            this.btnMove.Visible = false;
            this.btnMove.Click += new EventHandler(this.btnMove_Click);
            this.btnRectangle.Dock = DockStyle.Top;
            this.btnRectangle.FlatStyle = FlatStyle.Popup;
            this.btnRectangle.Location = new Point(0, 52);
            this.btnRectangle.Name = "btnRectangle";
            this.btnRectangle.Size = new Size(135, 52);
            this.btnRectangle.TabIndex = 1;
            this.btnRectangle.Tag = "9999";
            this.btnRectangle.Text = "设置矩形区域";
            this.btnRectangle.UseVisualStyleBackColor = true;
            this.btnRectangle.Click += new EventHandler(this.btnRectangle_Click);
            this.btnSetCircle.Dock = DockStyle.Top;
            this.btnSetCircle.FlatStyle = FlatStyle.Popup;
            this.btnSetCircle.Location = new Point(0, 0);
            this.btnSetCircle.Name = "btnSetCircle";
            this.btnSetCircle.Size = new Size(135, 52);
            this.btnSetCircle.TabIndex = 0;
            this.btnSetCircle.Tag = "9999";
            this.btnSetCircle.Text = "设置圆形区域";
            this.btnSetCircle.UseVisualStyleBackColor = true;
            this.btnSetCircle.Click += new EventHandler(this.btnSetCircle_Click);
            this.btnSet.Dock = DockStyle.Top;
            this.btnSet.Location = new Point(0, 0);
            this.btnSet.Name = "btnSet";
            this.btnSet.Size = new Size(135, 23);
            this.btnSet.TabIndex = 0;
            this.btnSet.Text = "设置";
            this.btnSet.UseVisualStyleBackColor = true;
            this.btnSet.Click += new EventHandler(this.btnSet_Click);
            this.btnTool.Dock = DockStyle.Bottom;
            this.btnTool.Location = new Point(0, 349);
            this.btnTool.Name = "btnTool";
            this.btnTool.Size = new Size(135, 23);
            this.btnTool.TabIndex = 2;
            this.btnTool.Text = "地图工具";
            this.btnTool.UseVisualStyleBackColor = true;
            this.btnTool.Click += new EventHandler(this.btnTool_Click);
            this.pnlRegion.Controls.Add(this.btnCancel);
            this.pnlRegion.Controls.Add(this.btnSumit);
            this.pnlRegion.Dock = DockStyle.Bottom;
            this.pnlRegion.Location = new Point(0, 372);
            this.pnlRegion.Name = "pnlRegion";
            this.pnlRegion.Size = new Size(135, 61);
            this.pnlRegion.TabIndex = 1;
            this.btnCancel.DialogResult =  System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new Point(24, 35);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(75, 23);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "取消";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new EventHandler(this.btnCancel_Click);
            this.btnSumit.Location = new Point(24, 6);
            this.btnSumit.Name = "btnSumit";
            this.btnSumit.Size = new Size(75, 23);
            this.btnSumit.TabIndex = 1;
            this.btnSumit.Text = "确定";
            this.btnSumit.UseVisualStyleBackColor = true;
            this.btnSumit.Click += new EventHandler(this.btnSubmit_Click);
            this.panel1.Controls.Add(this.picLoadMap);
            this.panel1.Controls.Add(this.wbMap);
            this.panel1.Dock = DockStyle.Fill;
            this.panel1.Location = new Point(135, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(564, 433);
            this.panel1.TabIndex = 8;
            base.AcceptButton = this.btnSumit;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.CancelButton = this.btnCancel;
            base.ClientSize = new Size(699, 433);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.pnlSetRegion);
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "QueryMap";
            this.Text = "日期查车位置范围";
            base.Load += new EventHandler(this.QueryMap_Load);
            base.FormClosing += new FormClosingEventHandler(this.QueryMap_FormClosing);
            ((ISupportInitialize) this.picLoadMap).EndInit();
            this.pnlSetRegion.ResumeLayout(false);
            this.pnlBtn.ResumeLayout(false);
            this.pnlHandle.ResumeLayout(false);
            this.pnlRadius.ResumeLayout(false);
            this.pnlRadius.PerformLayout();
            this.numRadius.EndInit();
            this.pnlRegion.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private string _dLat1;
        private string _dLat2;
        private string _dLon1;
        private string _dLon2;
        private int _iRadius;
        private Button btnCancel;
        private Button btnMove;
        private Button btnRectangle;
        private Button btnSet;
        private Button btnSetCircle;
        private Button btnSumit;
        private Button btnTool;
        private Button btnZoomIn;
        private Button btnZoonOut;
        private bool isClose;
        private Label label2;
        private Label label3;
        private Label lblRadius;
        private NumericUpDown numRadius;
        private Panel panel1;
        private PictureBox picLoadMap;
        private Panel pnlBtn;
        private Panel pnlHandle;
        private Panel pnlRadius;
        private Panel pnlRegion;
        private Panel pnlSetRegion;
        private GisMap wbMap;
    }
}