namespace Client.JTB
{
    using Client;
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class JTBControlTerminalConnectBySMS
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.grpWatchProperty = new GroupBox();
            this.numEffectiveTime = new NumericUpDown();
            this.btnShowDropControl = new Button();
            this.btnGetAuthCode = new Button();
            this.txtAuthCode = new TextBox();
            this.lblAuthCode = new Label();
            this.lblEffectiveTime = new Label();
            this.rdoOrignalServer = new RadioButton();
            this.lboxApnAccessMode = new ListBox();
            this.rdoDesignationServer = new RadioButton();
            this.numTcpPort = new NumericUpDown();
            this.lblTcpPort = new Label();
            this.txtApnAccessMode = new TextBox();
            this.txtPwd = new TextBox();
            this.lblPwd = new Label();
            this.txtUser = new TextBox();
            this.lblUser = new Label();
            this.numUdpPort = new NumericUpDown();
            this.lblUdpPort = new Label();
            this.txtServerIp = new IPAddressTextBox();
            this.lblServerIp = new Label();
            this.lblApnAccessMode = new Label();
            this.lblIntervalExplain2 = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpWatchProperty.SuspendLayout();
            this.numEffectiveTime.BeginInit();
            this.numTcpPort.BeginInit();
            this.numUdpPort.BeginInit();
            base.SuspendLayout();
            base.grpCar.Size = new Size(494, 116);
            base.pnlBtn.Location = new System.Drawing.Point(5, 265);
            base.pnlBtn.Size = new Size(494, 28);
            base.btnCancel.Location = new System.Drawing.Point(416, 3);
            base.btnOK.Location = new System.Drawing.Point(331, 3);
            this.grpWatchProperty.Controls.Add(this.numEffectiveTime);
            this.grpWatchProperty.Controls.Add(this.btnShowDropControl);
            this.grpWatchProperty.Controls.Add(this.btnGetAuthCode);
            this.grpWatchProperty.Controls.Add(this.txtAuthCode);
            this.grpWatchProperty.Controls.Add(this.lblAuthCode);
            this.grpWatchProperty.Controls.Add(this.lblEffectiveTime);
            this.grpWatchProperty.Controls.Add(this.rdoOrignalServer);
            this.grpWatchProperty.Controls.Add(this.lboxApnAccessMode);
            this.grpWatchProperty.Controls.Add(this.rdoDesignationServer);
            this.grpWatchProperty.Controls.Add(this.numTcpPort);
            this.grpWatchProperty.Controls.Add(this.lblTcpPort);
            this.grpWatchProperty.Controls.Add(this.txtApnAccessMode);
            this.grpWatchProperty.Controls.Add(this.txtPwd);
            this.grpWatchProperty.Controls.Add(this.lblPwd);
            this.grpWatchProperty.Controls.Add(this.txtUser);
            this.grpWatchProperty.Controls.Add(this.lblUser);
            this.grpWatchProperty.Controls.Add(this.numUdpPort);
            this.grpWatchProperty.Controls.Add(this.lblUdpPort);
            this.grpWatchProperty.Controls.Add(this.txtServerIp);
            this.grpWatchProperty.Controls.Add(this.lblServerIp);
            this.grpWatchProperty.Controls.Add(this.lblApnAccessMode);
            this.grpWatchProperty.Controls.Add(this.lblIntervalExplain2);
            this.grpWatchProperty.Dock = DockStyle.Top;
            this.grpWatchProperty.Location = new System.Drawing.Point(5, 121);
            this.grpWatchProperty.Name = "grpWatchProperty";
            this.grpWatchProperty.Size = new Size(494, 144);
            this.grpWatchProperty.TabIndex = 14;
            this.grpWatchProperty.TabStop = false;
            this.grpWatchProperty.Text = "参数设置";
            this.numEffectiveTime.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numEffectiveTime.Location = new System.Drawing.Point(338, 113);
            int[] bits = new int[4];
            bits[0] = 65535;
            this.numEffectiveTime.Maximum = new decimal(bits);
            this.numEffectiveTime.Name = "numEffectiveTime";
            this.numEffectiveTime.Size = new Size(58, 21);
            this.numEffectiveTime.TabIndex = 56;
            this.numEffectiveTime.Tag = "；";
            this.btnShowDropControl.Location = new System.Drawing.Point(236, 36);
            this.btnShowDropControl.Name = "btnShowDropControl";
            this.btnShowDropControl.Size = new Size(23, 23);
            this.btnShowDropControl.TabIndex = 55;
            this.btnShowDropControl.Text = "▼";
            this.btnShowDropControl.UseVisualStyleBackColor = true;
            this.btnShowDropControl.Click += new EventHandler(this.btnShowDropControl_Click);
            this.btnGetAuthCode.Location = new System.Drawing.Point(219, 113);
            this.btnGetAuthCode.Name = "btnGetAuthCode";
            this.btnGetAuthCode.Size = new Size(39, 23);
            this.btnGetAuthCode.TabIndex = 54;
            this.btnGetAuthCode.Text = "获取";
            this.btnGetAuthCode.UseVisualStyleBackColor = true;
            this.btnGetAuthCode.Click += new EventHandler(this.btnGetAuthCode_Click);
            this.txtAuthCode.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtAuthCode.Enabled = false;
            this.txtAuthCode.Location = new System.Drawing.Point(121, 113);
            this.txtAuthCode.MaxLength = 50;
            this.txtAuthCode.Name = "txtAuthCode";
            this.txtAuthCode.Size = new Size(96, 21);
            this.txtAuthCode.TabIndex = 53;
            this.txtAuthCode.Tag = "；";
            this.lblAuthCode.AutoSize = true;
            this.lblAuthCode.Location = new System.Drawing.Point(60, 115);
            this.lblAuthCode.Name = "lblAuthCode";
            this.lblAuthCode.Size = new Size(53, 12);
            this.lblAuthCode.TabIndex = 52;
            this.lblAuthCode.Text = "鉴权码：";
            this.lblEffectiveTime.AutoSize = true;
            this.lblEffectiveTime.Location = new System.Drawing.Point(265, 118);
            this.lblEffectiveTime.Name = "lblEffectiveTime";
            this.lblEffectiveTime.Size = new Size(65, 12);
            this.lblEffectiveTime.TabIndex = 49;
            this.lblEffectiveTime.Text = "有效时间：";
            this.rdoOrignalServer.AutoSize = true;
            this.rdoOrignalServer.Checked = true;
            this.rdoOrignalServer.Location = new System.Drawing.Point(121, 15);
            this.rdoOrignalServer.Name = "rdoOrignalServer";
            this.rdoOrignalServer.Size = new Size(131, 16);
            this.rdoOrignalServer.TabIndex = 47;
            this.rdoOrignalServer.TabStop = true;
            this.rdoOrignalServer.Text = "切换回原缺省服务器";
            this.rdoOrignalServer.UseVisualStyleBackColor = true;
            this.lboxApnAccessMode.FormattingEnabled = true;
            this.lboxApnAccessMode.ItemHeight = 12;
            this.lboxApnAccessMode.Items.AddRange(new object[] { "APN", "CDMA" });
            this.lboxApnAccessMode.Location = new System.Drawing.Point(121, 58);
            this.lboxApnAccessMode.Name = "lboxApnAccessMode";
            this.lboxApnAccessMode.Size = new Size(138, 28);
            this.lboxApnAccessMode.TabIndex = 44;
            this.lboxApnAccessMode.Visible = false;
            this.lboxApnAccessMode.SelectedIndexChanged += new EventHandler(this.lboxApnAccessMode_SelectedIndexChanged);
            this.rdoDesignationServer.AutoSize = true;
            this.rdoDesignationServer.Location = new System.Drawing.Point(275, 15);
            this.rdoDesignationServer.Name = "rdoDesignationServer";
            this.rdoDesignationServer.Size = new Size(131, 16);
            this.rdoDesignationServer.TabIndex = 46;
            this.rdoDesignationServer.Text = "切换到指定的服务器";
            this.rdoDesignationServer.UseVisualStyleBackColor = true;
            this.numTcpPort.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numTcpPort.Location = new System.Drawing.Point(338, 37);
            int[] numArray2 = new int[4];
            numArray2[0] = 65535;
            this.numTcpPort.Maximum = new decimal(numArray2);
            int[] numArray3 = new int[4];
            numArray3[0] = 1;
            this.numTcpPort.Minimum = new decimal(numArray3);
            this.numTcpPort.Name = "numTcpPort";
            this.numTcpPort.Size = new Size(58, 21);
            this.numTcpPort.TabIndex = 45;
            this.numTcpPort.Tag = "；";
            int[] numArray4 = new int[4];
            numArray4[0] = 1;
            this.numTcpPort.Value = new decimal(numArray4);
            this.lblTcpPort.AutoSize = true;
            this.lblTcpPort.Location = new System.Drawing.Point(273, 42);
            this.lblTcpPort.Name = "lblTcpPort";
            this.lblTcpPort.Size = new Size(59, 12);
            this.lblTcpPort.TabIndex = 44;
            this.lblTcpPort.Text = "TCP端口：";
            this.txtApnAccessMode.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtApnAccessMode.Location = new System.Drawing.Point(121, 37);
            this.txtApnAccessMode.MaxLength = 20;
            this.txtApnAccessMode.Name = "txtApnAccessMode";
            this.txtApnAccessMode.Size = new Size(115, 21);
            this.txtApnAccessMode.TabIndex = 43;
            this.txtApnAccessMode.TextChanged += new EventHandler(this.txtApnAccessMode_TextChanged);
            this.txtPwd.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPwd.Location = new System.Drawing.Point(338, 86);
            this.txtPwd.MaxLength = 16;
            this.txtPwd.Name = "txtPwd";
            this.txtPwd.PasswordChar = '*';
            this.txtPwd.Size = new Size(137, 21);
            this.txtPwd.TabIndex = 42;
            this.txtPwd.Tag = "；";
            this.lblPwd.AutoSize = true;
            this.lblPwd.Location = new System.Drawing.Point(267, 91);
            this.lblPwd.Name = "lblPwd";
            this.lblPwd.Size = new Size(65, 12);
            this.lblPwd.TabIndex = 40;
            this.lblPwd.Text = "拨号密码：";
            this.txtUser.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtUser.Location = new System.Drawing.Point(121, 86);
            this.txtUser.MaxLength = 16;
            this.txtUser.Name = "txtUser";
            this.txtUser.Size = new Size(138, 21);
            this.txtUser.TabIndex = 41;
            this.txtUser.Tag = "；";
            this.lblUser.AutoSize = true;
            this.lblUser.Location = new System.Drawing.Point(38, 91);
            this.lblUser.Name = "lblUser";
            this.lblUser.Size = new Size(77, 12);
            this.lblUser.TabIndex = 39;
            this.lblUser.Text = "拨号用户名：";
            this.numUdpPort.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numUdpPort.Location = new System.Drawing.Point(338, 61);
            int[] numArray5 = new int[4];
            numArray5[0] = 65535;
            this.numUdpPort.Maximum = new decimal(numArray5);
            int[] numArray6 = new int[4];
            numArray6[0] = 1;
            this.numUdpPort.Minimum = new decimal(numArray6);
            this.numUdpPort.Name = "numUdpPort";
            this.numUdpPort.Size = new Size(58, 21);
            this.numUdpPort.TabIndex = 38;
            this.numUdpPort.Tag = "；";
            int[] numArray7 = new int[4];
            numArray7[0] = 1;
            this.numUdpPort.Value = new decimal(numArray7);
            this.lblUdpPort.AutoSize = true;
            this.lblUdpPort.Location = new System.Drawing.Point(273, 66);
            this.lblUdpPort.Name = "lblUdpPort";
            this.lblUdpPort.Size = new Size(59, 12);
            this.lblUdpPort.TabIndex = 37;
            this.lblUdpPort.Text = "UDP端口：";
            this.txtServerIp.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtServerIp.Location = new System.Drawing.Point(121, 61);
            this.txtServerIp.Margin = new Padding(0);
            this.txtServerIp.Name = "txtServerIp";
            this.txtServerIp.Size = new Size(138, 21);
            this.txtServerIp.TabIndex = 35;
            this.txtServerIp.Tag = "；";
            this.lblServerIp.AutoSize = true;
            this.lblServerIp.Location = new System.Drawing.Point(48, 66);
            this.lblServerIp.Name = "lblServerIp";
            this.lblServerIp.Size = new Size(65, 12);
            this.lblServerIp.TabIndex = 36;
            this.lblServerIp.Text = "服务器IP：";
            this.lblApnAccessMode.AutoSize = true;
            this.lblApnAccessMode.Location = new System.Drawing.Point(8, 41);
            this.lblApnAccessMode.Name = "lblApnAccessMode";
            this.lblApnAccessMode.Size = new Size(107, 12);
            this.lblApnAccessMode.TabIndex = 34;
            this.lblApnAccessMode.Text = "APN拨号接入方式：";
            this.lblIntervalExplain2.AutoSize = true;
            this.lblIntervalExplain2.Location = new System.Drawing.Point(114, -15);
            this.lblIntervalExplain2.Name = "lblIntervalExplain2";
            this.lblIntervalExplain2.RightToLeft =  System.Windows.Forms.RightToLeft.Yes;
            this.lblIntervalExplain2.Size = new Size(167, 12);
            this.lblIntervalExplain2.TabIndex = 33;
            this.lblIntervalExplain2.Text = "0表示按最小间隔拍或一直录像";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(504, 298);
            base.Controls.Add(this.grpWatchProperty);
            base.Name = "JTBControlTerminalConnectBySMS";
            this.Text = "JTBControlTerminalConnectBySMS";
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpWatchProperty, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpWatchProperty.ResumeLayout(false);
            this.grpWatchProperty.PerformLayout();
            this.numEffectiveTime.EndInit();
            this.numTcpPort.EndInit();
            this.numUdpPort.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private AutoDropDown _appServerList;
        private Button btnGetAuthCode;
        private Button btnShowDropControl;
        private System.Windows.Forms.GroupBox grpWatchProperty;
        private Label lblApnAccessMode;
        private Label lblAuthCode;
        private Label lblEffectiveTime;
        private Label lblIntervalExplain2;
        private Label lblPwd;
        private Label lblServerIp;
        private Label lblTcpPort;
        private Label lblUdpPort;
        private Label lblUser;
        private ListBox lboxApnAccessMode;
        private NumericUpDown numEffectiveTime;
        private NumericUpDown numTcpPort;
        private NumericUpDown numUdpPort;
        private RadioButton rdoDesignationServer;
        private RadioButton rdoOrignalServer;
        private TextBox txtApnAccessMode;
        private TextBox txtAuthCode;
        private TextBox txtPwd;
        private IPAddressTextBox txtServerIp;
        private TextBox txtUser;
    }
}