namespace Client.JTB
{
    using Client;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    partial class JTBitmRealTimeReport
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.grpWatchProperty = new GroupBox();
            this.pnlLoginState = new Panel();
            this.lblNoLoginInterval = new Label();
            this.lblNoLoginSecond = new Label();
            this.numNoLoginInterval = new NumericUpDown();
            this.pnlDis2 = new Panel();
            this.lblNoLoginIntervalDis = new Label();
            this.lblReportIntervalDis = new Label();
            this.lblNoLoginDis = new Label();
            this.lblReportIntervalSecondDis = new Label();
            this.numNoLoginIntervalDis = new NumericUpDown();
            this.numReportIntervalDis = new NumericUpDown();
            this.pnlNeed2 = new Panel();
            this.lblReportInterval = new Label();
            this.lblRepair = new Label();
            this.lblReportIntervalSecond = new Label();
            this.numRepair = new NumericUpDown();
            this.numReportInterval = new NumericUpDown();
            this.lblAngle = new Label();
            this.pnlDis1 = new Panel();
            this.lblDormancyIntervalDis = new Label();
            this.lblEmergencyAlarmIntervalDis = new Label();
            this.numEmergencyAlarmIntervalDis = new NumericUpDown();
            this.EmergencyAlarmDis = new Label();
            this.numDormancyIntervalDis = new NumericUpDown();
            this.lblDormancyDis = new Label();
            this.pnlNeed1 = new Panel();
            this.lblDormancyInterval = new Label();
            this.lblEmergencyAlarmInterval = new Label();
            this.numEmergencyAlarmInterval = new NumericUpDown();
            this.EmergencyAlarmSecond = new Label();
            this.numDormancyInterval = new NumericUpDown();
            this.lblDormancySecond = new Label();
            this.panel1 = new Panel();
            this.lblWatchType = new Label();
            this.cmbWatchType = new ComboBox();
            this.lblWatchProgram = new Label();
            this.cmbWatchProgram = new ComboBox();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpWatchProperty.SuspendLayout();
            this.pnlLoginState.SuspendLayout();
            this.numNoLoginInterval.BeginInit();
            this.pnlDis2.SuspendLayout();
            this.numNoLoginIntervalDis.BeginInit();
            this.numReportIntervalDis.BeginInit();
            this.pnlNeed2.SuspendLayout();
            this.numRepair.BeginInit();
            this.numReportInterval.BeginInit();
            this.pnlDis1.SuspendLayout();
            this.numEmergencyAlarmIntervalDis.BeginInit();
            this.numDormancyIntervalDis.BeginInit();
            this.pnlNeed1.SuspendLayout();
            this.numEmergencyAlarmInterval.BeginInit();
            this.numDormancyInterval.BeginInit();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            base.grpCar.Size = new Size(444, 116);
            base.pnlBtn.Location = new System.Drawing.Point(5, 397);
            base.pnlBtn.Size = new Size(444, 28);
            base.btnCancel.Location = new System.Drawing.Point(366, 3);
            base.btnOK.Location = new System.Drawing.Point(281, 3);
            this.grpWatchProperty.Controls.Add(this.pnlLoginState);
            this.grpWatchProperty.Controls.Add(this.pnlDis2);
            this.grpWatchProperty.Controls.Add(this.pnlNeed2);
            this.grpWatchProperty.Controls.Add(this.pnlDis1);
            this.grpWatchProperty.Controls.Add(this.pnlNeed1);
            this.grpWatchProperty.Controls.Add(this.panel1);
            this.grpWatchProperty.Dock = DockStyle.Top;
            this.grpWatchProperty.Location = new System.Drawing.Point(5, 121);
            this.grpWatchProperty.Name = "grpWatchProperty";
            this.grpWatchProperty.Size = new Size(444, 276);
            this.grpWatchProperty.TabIndex = 9;
            this.grpWatchProperty.TabStop = false;
            this.grpWatchProperty.Text = "监控属性";
            this.pnlLoginState.AllowDrop = true;
            this.pnlLoginState.Controls.Add(this.lblNoLoginInterval);
            this.pnlLoginState.Controls.Add(this.lblNoLoginSecond);
            this.pnlLoginState.Controls.Add(this.numNoLoginInterval);
            this.pnlLoginState.Dock = DockStyle.Top;
            this.pnlLoginState.Location = new System.Drawing.Point(3, 165);
            this.pnlLoginState.Name = "pnlLoginState";
            this.pnlLoginState.Size = new Size(438, 25);
            this.pnlLoginState.TabIndex = 73;
            this.pnlLoginState.Visible = false;
            this.lblNoLoginInterval.AutoSize = true;
            this.lblNoLoginInterval.Location = new System.Drawing.Point(11, 4);
            this.lblNoLoginInterval.Name = "lblNoLoginInterval";
            this.lblNoLoginInterval.Size = new Size(101, 12);
            this.lblNoLoginInterval.TabIndex = 52;
            this.lblNoLoginInterval.Text = "未登录汇报间隔：";
            this.lblNoLoginSecond.AutoSize = true;
            this.lblNoLoginSecond.Location = new System.Drawing.Point(171, 4);
            this.lblNoLoginSecond.Name = "lblNoLoginSecond";
            this.lblNoLoginSecond.Size = new Size(17, 12);
            this.lblNoLoginSecond.TabIndex = 54;
            this.lblNoLoginSecond.Tag = "；";
            this.lblNoLoginSecond.Text = "秒";
            this.numNoLoginInterval.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numNoLoginInterval.Location = new System.Drawing.Point(116, 0);
            int[] bits = new int[4];
            bits[0] = 65535;
            this.numNoLoginInterval.Maximum = new decimal(bits);
            int[] numArray2 = new int[4];
            numArray2[0] = 1;
            this.numNoLoginInterval.Minimum = new decimal(numArray2);
            this.numNoLoginInterval.Name = "numNoLoginInterval";
            this.numNoLoginInterval.Size = new Size(54, 21);
            this.numNoLoginInterval.TabIndex = 53;
            int[] numArray3 = new int[4];
            numArray3[0] = 60;
            this.numNoLoginInterval.Value = new decimal(numArray3);
            this.pnlDis2.Controls.Add(this.lblNoLoginIntervalDis);
            this.pnlDis2.Controls.Add(this.lblReportIntervalDis);
            this.pnlDis2.Controls.Add(this.lblNoLoginDis);
            this.pnlDis2.Controls.Add(this.lblReportIntervalSecondDis);
            this.pnlDis2.Controls.Add(this.numNoLoginIntervalDis);
            this.pnlDis2.Controls.Add(this.numReportIntervalDis);
            this.pnlDis2.Dock = DockStyle.Top;
            this.pnlDis2.Location = new System.Drawing.Point(3, 140);
            this.pnlDis2.Name = "pnlDis2";
            this.pnlDis2.Size = new Size(438, 25);
            this.pnlDis2.TabIndex = 75;
            this.pnlDis2.Visible = false;
            this.lblNoLoginIntervalDis.AutoSize = true;
            this.lblNoLoginIntervalDis.Location = new System.Drawing.Point(226, 4);
            this.lblNoLoginIntervalDis.Name = "lblNoLoginIntervalDis";
            this.lblNoLoginIntervalDis.Size = new Size(101, 12);
            this.lblNoLoginIntervalDis.TabIndex = 55;
            this.lblNoLoginIntervalDis.Text = "未登录汇报间隔：";
            this.lblReportIntervalDis.AutoSize = true;
            this.lblReportIntervalDis.Location = new System.Drawing.Point(50, 4);
            this.lblReportIntervalDis.Name = "lblReportIntervalDis";
            this.lblReportIntervalDis.Size = new Size(65, 12);
            this.lblReportIntervalDis.TabIndex = 58;
            this.lblReportIntervalDis.Text = "汇报间隔：";
            this.lblNoLoginDis.AutoSize = true;
            this.lblNoLoginDis.Location = new System.Drawing.Point(386, 4);
            this.lblNoLoginDis.Name = "lblNoLoginDis";
            this.lblNoLoginDis.Size = new Size(17, 12);
            this.lblNoLoginDis.TabIndex = 57;
            this.lblNoLoginDis.Tag = "；";
            this.lblNoLoginDis.Text = "米";
            this.lblReportIntervalSecondDis.AutoSize = true;
            this.lblReportIntervalSecondDis.Location = new System.Drawing.Point(171, 4);
            this.lblReportIntervalSecondDis.Name = "lblReportIntervalSecondDis";
            this.lblReportIntervalSecondDis.Size = new Size(17, 12);
            this.lblReportIntervalSecondDis.TabIndex = 60;
            this.lblReportIntervalSecondDis.Tag = "；";
            this.lblReportIntervalSecondDis.Text = "米";
            this.numNoLoginIntervalDis.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numNoLoginIntervalDis.Location = new System.Drawing.Point(331, 0);
            int[] numArray4 = new int[4];
            numArray4[0] = 65535;
            this.numNoLoginIntervalDis.Maximum = new decimal(numArray4);
            int[] numArray5 = new int[4];
            numArray5[0] = 1;
            this.numNoLoginIntervalDis.Minimum = new decimal(numArray5);
            this.numNoLoginIntervalDis.Name = "numNoLoginIntervalDis";
            this.numNoLoginIntervalDis.Size = new Size(54, 21);
            this.numNoLoginIntervalDis.TabIndex = 56;
            int[] numArray6 = new int[4];
            numArray6[0] = 60;
            this.numNoLoginIntervalDis.Value = new decimal(numArray6);
            this.numReportIntervalDis.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numReportIntervalDis.Location = new System.Drawing.Point(116, 0);
            int[] numArray7 = new int[4];
            numArray7[0] = 65535;
            this.numReportIntervalDis.Maximum = new decimal(numArray7);
            int[] numArray8 = new int[4];
            numArray8[0] = 1;
            this.numReportIntervalDis.Minimum = new decimal(numArray8);
            this.numReportIntervalDis.Name = "numReportIntervalDis";
            this.numReportIntervalDis.Size = new Size(54, 21);
            this.numReportIntervalDis.TabIndex = 59;
            int[] numArray9 = new int[4];
            numArray9[0] = 60;
            this.numReportIntervalDis.Value = new decimal(numArray9);
            this.pnlNeed2.Controls.Add(this.lblReportInterval);
            this.pnlNeed2.Controls.Add(this.lblRepair);
            this.pnlNeed2.Controls.Add(this.lblReportIntervalSecond);
            this.pnlNeed2.Controls.Add(this.numRepair);
            this.pnlNeed2.Controls.Add(this.numReportInterval);
            this.pnlNeed2.Controls.Add(this.lblAngle);
            this.pnlNeed2.Dock = DockStyle.Top;
            this.pnlNeed2.Location = new System.Drawing.Point(3, 115);
            this.pnlNeed2.Name = "pnlNeed2";
            this.pnlNeed2.Size = new Size(438, 25);
            this.pnlNeed2.TabIndex = 74;
            this.lblReportInterval.AutoSize = true;
            this.lblReportInterval.Location = new System.Drawing.Point(265, 4);
            this.lblReportInterval.Name = "lblReportInterval";
            this.lblReportInterval.Size = new Size(65, 12);
            this.lblReportInterval.TabIndex = 55;
            this.lblReportInterval.Text = "汇报间隔：";
            this.lblRepair.AutoSize = true;
            this.lblRepair.Location = new System.Drawing.Point(47, 4);
            this.lblRepair.Name = "lblRepair";
            this.lblRepair.Size = new Size(65, 12);
            this.lblRepair.TabIndex = 43;
            this.lblRepair.Text = "拐点补偿：";
            this.lblReportIntervalSecond.AutoSize = true;
            this.lblReportIntervalSecond.Location = new System.Drawing.Point(386, 4);
            this.lblReportIntervalSecond.Name = "lblReportIntervalSecond";
            this.lblReportIntervalSecond.Size = new Size(17, 12);
            this.lblReportIntervalSecond.TabIndex = 57;
            this.lblReportIntervalSecond.Tag = "；";
            this.lblReportIntervalSecond.Text = "秒";
            this.numRepair.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numRepair.Location = new System.Drawing.Point(116, 0);
            int[] numArray10 = new int[4];
            numArray10[0] = 180;
            this.numRepair.Maximum = new decimal(numArray10);
            this.numRepair.Name = "numRepair";
            this.numRepair.Size = new Size(54, 21);
            this.numRepair.TabIndex = 44;
            this.numReportInterval.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numReportInterval.Location = new System.Drawing.Point(331, 0);
            int[] numArray11 = new int[4];
            numArray11[0] = 65535;
            this.numReportInterval.Maximum = new decimal(numArray11);
            int[] numArray12 = new int[4];
            numArray12[0] = 1;
            this.numReportInterval.Minimum = new decimal(numArray12);
            this.numReportInterval.Name = "numReportInterval";
            this.numReportInterval.Size = new Size(54, 21);
            this.numReportInterval.TabIndex = 56;
            int[] numArray13 = new int[4];
            numArray13[0] = 60;
            this.numReportInterval.Value = new decimal(numArray13);
            this.lblAngle.AutoSize = true;
            this.lblAngle.Location = new System.Drawing.Point(172, 4);
            this.lblAngle.Name = "lblAngle";
            this.lblAngle.Size = new Size(17, 12);
            this.lblAngle.TabIndex = 45;
            this.lblAngle.Tag = "；";
            this.lblAngle.Text = "度";
            this.pnlDis1.Controls.Add(this.lblDormancyIntervalDis);
            this.pnlDis1.Controls.Add(this.lblEmergencyAlarmIntervalDis);
            this.pnlDis1.Controls.Add(this.numEmergencyAlarmIntervalDis);
            this.pnlDis1.Controls.Add(this.EmergencyAlarmDis);
            this.pnlDis1.Controls.Add(this.numDormancyIntervalDis);
            this.pnlDis1.Controls.Add(this.lblDormancyDis);
            this.pnlDis1.Dock = DockStyle.Top;
            this.pnlDis1.Location = new System.Drawing.Point(3, 90);
            this.pnlDis1.Name = "pnlDis1";
            this.pnlDis1.Size = new Size(438, 25);
            this.pnlDis1.TabIndex = 72;
            this.pnlDis1.Visible = false;
            this.lblDormancyIntervalDis.AutoSize = true;
            this.lblDormancyIntervalDis.Location = new System.Drawing.Point(11, 4);
            this.lblDormancyIntervalDis.Name = "lblDormancyIntervalDis";
            this.lblDormancyIntervalDis.Size = new Size(101, 12);
            this.lblDormancyIntervalDis.TabIndex = 61;
            this.lblDormancyIntervalDis.Text = "休眠时汇报间隔：";
            this.lblEmergencyAlarmIntervalDis.AutoSize = true;
            this.lblEmergencyAlarmIntervalDis.Location = new System.Drawing.Point(217, 4);
            this.lblEmergencyAlarmIntervalDis.Name = "lblEmergencyAlarmIntervalDis";
            this.lblEmergencyAlarmIntervalDis.Size = new Size(113, 12);
            this.lblEmergencyAlarmIntervalDis.TabIndex = 64;
            this.lblEmergencyAlarmIntervalDis.Text = "紧急报警汇报间隔：";
            this.numEmergencyAlarmIntervalDis.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numEmergencyAlarmIntervalDis.Location = new System.Drawing.Point(331, 0);
            int[] numArray14 = new int[4];
            numArray14[0] = 65535;
            this.numEmergencyAlarmIntervalDis.Maximum = new decimal(numArray14);
            int[] numArray15 = new int[4];
            numArray15[0] = 1;
            this.numEmergencyAlarmIntervalDis.Minimum = new decimal(numArray15);
            this.numEmergencyAlarmIntervalDis.Name = "numEmergencyAlarmIntervalDis";
            this.numEmergencyAlarmIntervalDis.Size = new Size(54, 21);
            this.numEmergencyAlarmIntervalDis.TabIndex = 65;
            int[] numArray16 = new int[4];
            numArray16[0] = 60;
            this.numEmergencyAlarmIntervalDis.Value = new decimal(numArray16);
            this.EmergencyAlarmDis.AutoSize = true;
            this.EmergencyAlarmDis.Location = new System.Drawing.Point(388, 4);
            this.EmergencyAlarmDis.Name = "EmergencyAlarmDis";
            this.EmergencyAlarmDis.Size = new Size(17, 12);
            this.EmergencyAlarmDis.TabIndex = 66;
            this.EmergencyAlarmDis.Tag = "；";
            this.EmergencyAlarmDis.Text = "米";
            this.numDormancyIntervalDis.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numDormancyIntervalDis.Location = new System.Drawing.Point(116, 0);
            int[] numArray17 = new int[4];
            numArray17[0] = 65535;
            this.numDormancyIntervalDis.Maximum = new decimal(numArray17);
            int[] numArray18 = new int[4];
            numArray18[0] = 1;
            this.numDormancyIntervalDis.Minimum = new decimal(numArray18);
            this.numDormancyIntervalDis.Name = "numDormancyIntervalDis";
            this.numDormancyIntervalDis.Size = new Size(54, 21);
            this.numDormancyIntervalDis.TabIndex = 62;
            int[] numArray19 = new int[4];
            numArray19[0] = 60;
            this.numDormancyIntervalDis.Value = new decimal(numArray19);
            this.lblDormancyDis.AutoSize = true;
            this.lblDormancyDis.Location = new System.Drawing.Point(171, 4);
            this.lblDormancyDis.Name = "lblDormancyDis";
            this.lblDormancyDis.Size = new Size(17, 12);
            this.lblDormancyDis.TabIndex = 63;
            this.lblDormancyDis.Tag = "；";
            this.lblDormancyDis.Text = "米";
            this.pnlNeed1.Controls.Add(this.lblDormancyInterval);
            this.pnlNeed1.Controls.Add(this.lblEmergencyAlarmInterval);
            this.pnlNeed1.Controls.Add(this.numEmergencyAlarmInterval);
            this.pnlNeed1.Controls.Add(this.EmergencyAlarmSecond);
            this.pnlNeed1.Controls.Add(this.numDormancyInterval);
            this.pnlNeed1.Controls.Add(this.lblDormancySecond);
            this.pnlNeed1.Dock = DockStyle.Top;
            this.pnlNeed1.Location = new System.Drawing.Point(3, 62);
            this.pnlNeed1.Name = "pnlNeed1";
            this.pnlNeed1.Size = new Size(438, 28);
            this.pnlNeed1.TabIndex = 71;
            this.lblDormancyInterval.AutoSize = true;
            this.lblDormancyInterval.Location = new System.Drawing.Point(11, 7);
            this.lblDormancyInterval.Name = "lblDormancyInterval";
            this.lblDormancyInterval.Size = new Size(101, 12);
            this.lblDormancyInterval.TabIndex = 55;
            this.lblDormancyInterval.Text = "休眠时汇报间隔：";
            this.lblEmergencyAlarmInterval.AutoSize = true;
            this.lblEmergencyAlarmInterval.Location = new System.Drawing.Point(217, 7);
            this.lblEmergencyAlarmInterval.Name = "lblEmergencyAlarmInterval";
            this.lblEmergencyAlarmInterval.Size = new Size(113, 12);
            this.lblEmergencyAlarmInterval.TabIndex = 58;
            this.lblEmergencyAlarmInterval.Text = "紧急报警汇报间隔：";
            this.numEmergencyAlarmInterval.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numEmergencyAlarmInterval.Location = new System.Drawing.Point(331, 3);
            int[] numArray20 = new int[4];
            numArray20[0] = 65535;
            this.numEmergencyAlarmInterval.Maximum = new decimal(numArray20);
            int[] numArray21 = new int[4];
            numArray21[0] = 1;
            this.numEmergencyAlarmInterval.Minimum = new decimal(numArray21);
            this.numEmergencyAlarmInterval.Name = "numEmergencyAlarmInterval";
            this.numEmergencyAlarmInterval.Size = new Size(54, 21);
            this.numEmergencyAlarmInterval.TabIndex = 59;
            int[] numArray22 = new int[4];
            numArray22[0] = 60;
            this.numEmergencyAlarmInterval.Value = new decimal(numArray22);
            this.EmergencyAlarmSecond.AutoSize = true;
            this.EmergencyAlarmSecond.Location = new System.Drawing.Point(388, 7);
            this.EmergencyAlarmSecond.Name = "EmergencyAlarmSecond";
            this.EmergencyAlarmSecond.Size = new Size(17, 12);
            this.EmergencyAlarmSecond.TabIndex = 60;
            this.EmergencyAlarmSecond.Tag = "；";
            this.EmergencyAlarmSecond.Text = "秒";
            this.numDormancyInterval.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numDormancyInterval.Location = new System.Drawing.Point(116, 3);
            int[] numArray23 = new int[4];
            numArray23[0] = 65535;
            this.numDormancyInterval.Maximum = new decimal(numArray23);
            int[] numArray24 = new int[4];
            numArray24[0] = 1;
            this.numDormancyInterval.Minimum = new decimal(numArray24);
            this.numDormancyInterval.Name = "numDormancyInterval";
            this.numDormancyInterval.Size = new Size(54, 21);
            this.numDormancyInterval.TabIndex = 56;
            int[] numArray25 = new int[4];
            numArray25[0] = 60;
            this.numDormancyInterval.Value = new decimal(numArray25);
            this.lblDormancySecond.AutoSize = true;
            this.lblDormancySecond.Location = new System.Drawing.Point(171, 7);
            this.lblDormancySecond.Name = "lblDormancySecond";
            this.lblDormancySecond.Size = new Size(17, 12);
            this.lblDormancySecond.TabIndex = 57;
            this.lblDormancySecond.Tag = "；";
            this.lblDormancySecond.Text = "秒";
            this.panel1.Controls.Add(this.lblWatchType);
            this.panel1.Controls.Add(this.cmbWatchType);
            this.panel1.Controls.Add(this.lblWatchProgram);
            this.panel1.Controls.Add(this.cmbWatchProgram);
            this.panel1.Dock = DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(3, 17);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(438, 45);
            this.panel1.TabIndex = 70;
            this.lblWatchType.AutoSize = true;
            this.lblWatchType.Location = new System.Drawing.Point(44, 3);
            this.lblWatchType.Name = "lblWatchType";
            this.lblWatchType.Size = new Size(65, 12);
            this.lblWatchType.TabIndex = 39;
            this.lblWatchType.Text = "汇报策略：";
            this.cmbWatchType.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbWatchType.FormattingEnabled = true;
            this.cmbWatchType.Items.AddRange(new object[] { "定时汇报", "定距汇报", "定时+定距" });
            this.cmbWatchType.Location = new System.Drawing.Point(116, 0);
            this.cmbWatchType.Name = "cmbWatchType";
            this.cmbWatchType.Size = new Size(161, 20);
            this.cmbWatchType.TabIndex = 40;
            this.cmbWatchType.SelectedIndexChanged += new EventHandler(this.cmbWatchType_SelectedIndexChanged);
            this.lblWatchProgram.AutoSize = true;
            this.lblWatchProgram.Location = new System.Drawing.Point(44, 24);
            this.lblWatchProgram.Name = "lblWatchProgram";
            this.lblWatchProgram.Size = new Size(65, 12);
            this.lblWatchProgram.TabIndex = 41;
            this.lblWatchProgram.Text = "汇报方案：";
            this.cmbWatchProgram.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbWatchProgram.FormattingEnabled = true;
            this.cmbWatchProgram.Items.AddRange(new object[] { "根据ACC状态", "根据登录状态+ACC状态" });
            this.cmbWatchProgram.Location = new System.Drawing.Point(116, 21);
            this.cmbWatchProgram.Name = "cmbWatchProgram";
            this.cmbWatchProgram.Size = new Size(161, 20);
            this.cmbWatchProgram.TabIndex = 42;
            this.cmbWatchProgram.SelectedIndexChanged += new EventHandler(this.cmbWatchProgram_SelectedIndexChanged);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(454, 430);
            base.Controls.Add(this.grpWatchProperty);
            base.Name = "JTBitmRealTimeReport";
            this.Text = "JTBitmRealTimeReport";
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpWatchProperty, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpWatchProperty.ResumeLayout(false);
            this.pnlLoginState.ResumeLayout(false);
            this.pnlLoginState.PerformLayout();
            this.numNoLoginInterval.EndInit();
            this.pnlDis2.ResumeLayout(false);
            this.pnlDis2.PerformLayout();
            this.numNoLoginIntervalDis.EndInit();
            this.numReportIntervalDis.EndInit();
            this.pnlNeed2.ResumeLayout(false);
            this.pnlNeed2.PerformLayout();
            this.numRepair.EndInit();
            this.numReportInterval.EndInit();
            this.pnlDis1.ResumeLayout(false);
            this.pnlDis1.PerformLayout();
            this.numEmergencyAlarmIntervalDis.EndInit();
            this.numDormancyIntervalDis.EndInit();
            this.pnlNeed1.ResumeLayout(false);
            this.pnlNeed1.PerformLayout();
            this.numEmergencyAlarmInterval.EndInit();
            this.numDormancyInterval.EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private ComboBox cmbWatchProgram;
        private ComboBox cmbWatchType;
        private Label EmergencyAlarmDis;
        private Label EmergencyAlarmSecond;
        private System.Windows.Forms.GroupBox grpWatchProperty;
        private Label lblAngle;
        private Label lblDormancyDis;
        private Label lblDormancyInterval;
        private Label lblDormancyIntervalDis;
        private Label lblDormancySecond;
        private Label lblEmergencyAlarmInterval;
        private Label lblEmergencyAlarmIntervalDis;
        private Label lblNoLoginDis;
        private Label lblNoLoginInterval;
        private Label lblNoLoginIntervalDis;
        private Label lblNoLoginSecond;
        private Label lblRepair;
        private Label lblReportInterval;
        private Label lblReportIntervalDis;
        private Label lblReportIntervalSecond;
        private Label lblReportIntervalSecondDis;
        private Label lblWatchProgram;
        private Label lblWatchType;
        private NumericUpDown numDormancyInterval;
        private NumericUpDown numDormancyIntervalDis;
        private NumericUpDown numEmergencyAlarmInterval;
        private NumericUpDown numEmergencyAlarmIntervalDis;
        private NumericUpDown numNoLoginInterval;
        private NumericUpDown numNoLoginIntervalDis;
        private NumericUpDown numRepair;
        private NumericUpDown numReportInterval;
        private NumericUpDown numReportIntervalDis;
        private Panel panel1;
        private Panel pnlDis1;
        private Panel pnlDis2;
        private Panel pnlLoginState;
        private Panel pnlNeed1;
        private Panel pnlNeed2;
    }
}