namespace Client.JTB
{
    using Client;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    partial class JTBSetPictureParam
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.grpWatchProperty = new GroupBox();
            this.lblChromaValue = new Label();
            this.lblSaturationValue = new Label();
            this.lblContrastValue = new Label();
            this.lblImageLightValue = new Label();
            this.lblQualityValue = new Label();
            this.lblChromaExplain = new Label();
            this.lblSaturationExplain = new Label();
            this.lblContrastExplain = new Label();
            this.lblImageLightExplain = new Label();
            this.lblQualityExplain = new Label();
            this.lblQuality = new Label();
            this.trkQuality = new TrackBar();
            this.lblLight = new Label();
            this.trkLight = new TrackBar();
            this.lblContrast = new Label();
            this.trkContrast = new TrackBar();
            this.lblSaturation = new Label();
            this.trkSaturation = new TrackBar();
            this.lblChroma = new Label();
            this.trkChroma = new TrackBar();
            this.lblIntervalExplain2 = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpWatchProperty.SuspendLayout();
            this.trkQuality.BeginInit();
            this.trkLight.BeginInit();
            this.trkContrast.BeginInit();
            this.trkSaturation.BeginInit();
            this.trkChroma.BeginInit();
            base.SuspendLayout();
            base.pnlBtn.Location = new System.Drawing.Point(5, 266);
            this.grpWatchProperty.Controls.Add(this.lblChromaValue);
            this.grpWatchProperty.Controls.Add(this.lblSaturationValue);
            this.grpWatchProperty.Controls.Add(this.lblContrastValue);
            this.grpWatchProperty.Controls.Add(this.lblImageLightValue);
            this.grpWatchProperty.Controls.Add(this.lblQualityValue);
            this.grpWatchProperty.Controls.Add(this.lblChromaExplain);
            this.grpWatchProperty.Controls.Add(this.lblSaturationExplain);
            this.grpWatchProperty.Controls.Add(this.lblContrastExplain);
            this.grpWatchProperty.Controls.Add(this.lblImageLightExplain);
            this.grpWatchProperty.Controls.Add(this.lblQualityExplain);
            this.grpWatchProperty.Controls.Add(this.lblQuality);
            this.grpWatchProperty.Controls.Add(this.trkQuality);
            this.grpWatchProperty.Controls.Add(this.lblLight);
            this.grpWatchProperty.Controls.Add(this.trkLight);
            this.grpWatchProperty.Controls.Add(this.lblContrast);
            this.grpWatchProperty.Controls.Add(this.trkContrast);
            this.grpWatchProperty.Controls.Add(this.lblSaturation);
            this.grpWatchProperty.Controls.Add(this.trkSaturation);
            this.grpWatchProperty.Controls.Add(this.lblChroma);
            this.grpWatchProperty.Controls.Add(this.trkChroma);
            this.grpWatchProperty.Controls.Add(this.lblIntervalExplain2);
            this.grpWatchProperty.Dock = DockStyle.Top;
            this.grpWatchProperty.Location = new System.Drawing.Point(5, 121);
            this.grpWatchProperty.Name = "grpWatchProperty";
            this.grpWatchProperty.Size = new Size(363, 145);
            this.grpWatchProperty.TabIndex = 13;
            this.grpWatchProperty.TabStop = false;
            this.grpWatchProperty.Text = "参数设置";
            this.lblChromaValue.AutoSize = true;
            this.lblChromaValue.Location = new System.Drawing.Point(247, 120);
            this.lblChromaValue.Name = "lblChromaValue";
            this.lblChromaValue.Size = new Size(23, 12);
            this.lblChromaValue.TabIndex = 45;
            this.lblChromaValue.Tag = "9999";
            this.lblChromaValue.Text = "128";
            this.lblSaturationValue.AutoSize = true;
            this.lblSaturationValue.Location = new System.Drawing.Point(247, 96);
            this.lblSaturationValue.Name = "lblSaturationValue";
            this.lblSaturationValue.Size = new Size(17, 12);
            this.lblSaturationValue.TabIndex = 46;
            this.lblSaturationValue.Tag = "9999";
            this.lblSaturationValue.Text = "64";
            this.lblContrastValue.AutoSize = true;
            this.lblContrastValue.Location = new System.Drawing.Point(247, 69);
            this.lblContrastValue.Name = "lblContrastValue";
            this.lblContrastValue.Size = new Size(17, 12);
            this.lblContrastValue.TabIndex = 43;
            this.lblContrastValue.Tag = "9999";
            this.lblContrastValue.Text = "71";
            this.lblImageLightValue.AutoSize = true;
            this.lblImageLightValue.Location = new System.Drawing.Point(247, 42);
            this.lblImageLightValue.Name = "lblImageLightValue";
            this.lblImageLightValue.Size = new Size(23, 12);
            this.lblImageLightValue.TabIndex = 44;
            this.lblImageLightValue.Tag = "9999";
            this.lblImageLightValue.Text = "128";
            this.lblQualityValue.AutoSize = true;
            this.lblQualityValue.Location = new System.Drawing.Point(247, 15);
            this.lblQualityValue.Name = "lblQualityValue";
            this.lblQualityValue.Size = new Size(11, 12);
            this.lblQualityValue.TabIndex = 49;
            this.lblQualityValue.Tag = "9999";
            this.lblQualityValue.Text = "3";
            this.lblChromaExplain.AutoSize = true;
            this.lblChromaExplain.Location = new System.Drawing.Point(277, 120);
            this.lblChromaExplain.Name = "lblChromaExplain";
            this.lblChromaExplain.Size = new Size(47, 12);
            this.lblChromaExplain.TabIndex = 50;
            this.lblChromaExplain.Tag = "9999";
            this.lblChromaExplain.Text = "(0-255)";
            this.lblSaturationExplain.AutoSize = true;
            this.lblSaturationExplain.Location = new System.Drawing.Point(277, 96);
            this.lblSaturationExplain.Name = "lblSaturationExplain";
            this.lblSaturationExplain.Size = new Size(47, 12);
            this.lblSaturationExplain.TabIndex = 47;
            this.lblSaturationExplain.Tag = "9999";
            this.lblSaturationExplain.Text = "(0-127)";
            this.lblContrastExplain.AutoSize = true;
            this.lblContrastExplain.Location = new System.Drawing.Point(277, 69);
            this.lblContrastExplain.Name = "lblContrastExplain";
            this.lblContrastExplain.Size = new Size(47, 12);
            this.lblContrastExplain.TabIndex = 48;
            this.lblContrastExplain.Tag = "9999";
            this.lblContrastExplain.Text = "(0-127)";
            this.lblImageLightExplain.AutoSize = true;
            this.lblImageLightExplain.Location = new System.Drawing.Point(277, 42);
            this.lblImageLightExplain.Name = "lblImageLightExplain";
            this.lblImageLightExplain.Size = new Size(47, 12);
            this.lblImageLightExplain.TabIndex = 42;
            this.lblImageLightExplain.Tag = "9999";
            this.lblImageLightExplain.Text = "(0-255)";
            this.lblQualityExplain.AutoSize = true;
            this.lblQualityExplain.Location = new System.Drawing.Point(277, 15);
            this.lblQualityExplain.Name = "lblQualityExplain";
            this.lblQualityExplain.Size = new Size(41, 12);
            this.lblQualityExplain.TabIndex = 40;
            this.lblQualityExplain.Tag = "9999";
            this.lblQualityExplain.Text = "(0-10)";
            this.lblQuality.AutoSize = true;
            this.lblQuality.Location = new System.Drawing.Point(47, 15);
            this.lblQuality.Name = "lblQuality";
            this.lblQuality.Size = new Size(65, 12);
            this.lblQuality.TabIndex = 34;
            this.lblQuality.Text = "图像质量：";
            this.trkQuality.AutoSize = false;
            this.trkQuality.Location = new System.Drawing.Point(109, 10);
            this.trkQuality.Name = "trkQuality";
            this.trkQuality.Size = new Size(136, 23);
            this.trkQuality.TabIndex = 39;
            this.trkQuality.Tag = "；";
            this.trkQuality.TickStyle = TickStyle.None;
            this.trkQuality.Value = 3;
            this.trkQuality.ValueChanged += new EventHandler(this.trkQuality_ValueChanged);
            this.lblLight.AutoSize = true;
            this.lblLight.Location = new System.Drawing.Point(47, 42);
            this.lblLight.Name = "lblLight";
            this.lblLight.Size = new Size(65, 12);
            this.lblLight.TabIndex = 35;
            this.lblLight.Text = "图像亮度：";
            this.trkLight.AutoSize = false;
            this.trkLight.Location = new System.Drawing.Point(109, 37);
            this.trkLight.Maximum = 255;
            this.trkLight.Name = "trkLight";
            this.trkLight.Size = new Size(136, 23);
            this.trkLight.TabIndex = 41;
            this.trkLight.Tag = "；";
            this.trkLight.TickStyle = TickStyle.None;
            this.trkLight.Value = 128;
            this.trkLight.ValueChanged += new EventHandler(this.trkImageLight_ValueChanged);
            this.lblContrast.AutoSize = true;
            this.lblContrast.Location = new System.Drawing.Point(59, 69);
            this.lblContrast.Name = "lblContrast";
            this.lblContrast.Size = new Size(53, 12);
            this.lblContrast.TabIndex = 36;
            this.lblContrast.Text = "对比度：";
            this.trkContrast.AutoSize = false;
            this.trkContrast.Location = new System.Drawing.Point(109, 64);
            this.trkContrast.Maximum = 127;
            this.trkContrast.Name = "trkContrast";
            this.trkContrast.Size = new Size(136, 23);
            this.trkContrast.TabIndex = 51;
            this.trkContrast.Tag = "；";
            this.trkContrast.TickStyle = TickStyle.None;
            this.trkContrast.Value = 71;
            this.trkContrast.ValueChanged += new EventHandler(this.trkContrast_ValueChanged);
            this.lblSaturation.AutoSize = true;
            this.lblSaturation.Location = new System.Drawing.Point(59, 96);
            this.lblSaturation.Name = "lblSaturation";
            this.lblSaturation.Size = new Size(53, 12);
            this.lblSaturation.TabIndex = 38;
            this.lblSaturation.Text = "饱和度：";
            this.trkSaturation.AutoSize = false;
            this.trkSaturation.Location = new System.Drawing.Point(109, 91);
            this.trkSaturation.Maximum = 127;
            this.trkSaturation.Name = "trkSaturation";
            this.trkSaturation.Size = new Size(136, 23);
            this.trkSaturation.TabIndex = 52;
            this.trkSaturation.Tag = "；";
            this.trkSaturation.TickStyle = TickStyle.None;
            this.trkSaturation.Value = 64;
            this.trkSaturation.ValueChanged += new EventHandler(this.trkSaturation_ValueChanged);
            this.lblChroma.AutoSize = true;
            this.lblChroma.Location = new System.Drawing.Point(71, 120);
            this.lblChroma.Name = "lblChroma";
            this.lblChroma.Size = new Size(41, 12);
            this.lblChroma.TabIndex = 37;
            this.lblChroma.Text = "色度：";
            this.trkChroma.AutoSize = false;
            this.trkChroma.Location = new System.Drawing.Point(109, 115);
            this.trkChroma.Maximum = 255;
            this.trkChroma.Name = "trkChroma";
            this.trkChroma.Size = new Size(136, 23);
            this.trkChroma.TabIndex = 53;
            this.trkChroma.Tag = "；";
            this.trkChroma.TickStyle = TickStyle.None;
            this.trkChroma.Value = 128;
            this.trkChroma.ValueChanged += new EventHandler(this.trkChroma_ValueChanged);
            this.lblIntervalExplain2.AutoSize = true;
            this.lblIntervalExplain2.Location = new System.Drawing.Point(114, -15);
            this.lblIntervalExplain2.Name = "lblIntervalExplain2";
            this.lblIntervalExplain2.RightToLeft =  System.Windows.Forms.RightToLeft.Yes;
            this.lblIntervalExplain2.Size = new Size(167, 12);
            this.lblIntervalExplain2.TabIndex = 33;
            this.lblIntervalExplain2.Text = "0表示按最小间隔拍或一直录像";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(373, 299);
            base.Controls.Add(this.grpWatchProperty);
            base.Name = "JTBSetPictureParam";
            this.Text = "JTBSetPictureParam";
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpWatchProperty, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpWatchProperty.ResumeLayout(false);
            this.grpWatchProperty.PerformLayout();
            this.trkQuality.EndInit();
            this.trkLight.EndInit();
            this.trkContrast.EndInit();
            this.trkSaturation.EndInit();
            this.trkChroma.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private System.Windows.Forms.GroupBox grpWatchProperty;
        private Label lblChroma;
        private Label lblChromaExplain;
        private Label lblChromaValue;
        private Label lblContrast;
        private Label lblContrastExplain;
        private Label lblContrastValue;
        private Label lblImageLightExplain;
        private Label lblImageLightValue;
        private Label lblIntervalExplain2;
        private Label lblLight;
        private Label lblQuality;
        private Label lblQualityExplain;
        private Label lblQualityValue;
        private Label lblSaturation;
        private Label lblSaturationExplain;
        private Label lblSaturationValue;
        private TrackBar trkChroma;
        private TrackBar trkContrast;
        private TrackBar trkLight;
        private TrackBar trkQuality;
        private TrackBar trkSaturation;
    }
}