namespace Client.JTB
{
    using Client;
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Text;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class JTBWirelessUpgradeCommand
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            this.grpWatchProperty = new GroupBox();
            this.btnShowDropControl = new Button();
            this.numTcpPort = new NumericUpDown();
            this.lblTcpPort = new Label();
            this.btnGetManufatureId = new Button();
            this.lboxApnAccessMode = new ListBox();
            this.txtApnAccessMode = new TextBox();
            this.label4 = new Label();
            this.numEffectiveTime = new NumericUpDown();
            this.lblEffectiveTime = new Label();
            this.txtTerminalUpgradeAddress = new TextBox();
            this.lblTerminalUpgradeAddress = new Label();
            this.txtFirmWareNum = new TextBox();
            this.lblFirmWareNum = new Label();
            this.txtHardWareNum = new TextBox();
            this.lblHardWareNum = new Label();
            this.txtManufacturerID = new TextBox();
            this.lblManufacturerID = new Label();
            this.txtPwd = new TextBox();
            this.lblPwd = new Label();
            this.txtUser = new TextBox();
            this.lblUser = new Label();
            this.lblUdpPort = new Label();
            this.txtUpgradeServerIp = new IPAddressTextBox();
            this.lblUpgradeServerIp = new Label();
            this.lblApnAccessMode = new Label();
            this.numUdpPort = new TextBox();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpWatchProperty.SuspendLayout();
            this.numTcpPort.BeginInit();
            this.numEffectiveTime.BeginInit();
            base.SuspendLayout();
            base.grpCar.Size = new Size(469, 116);
            base.pnlBtn.Location = new System.Drawing.Point(5, 290);
            base.pnlBtn.Size = new Size(469, 28);
            base.btnCancel.Location = new System.Drawing.Point(391, 3);
            base.btnOK.Location = new System.Drawing.Point(306, 3);
            this.grpWatchProperty.Controls.Add(this.numUdpPort);
            this.grpWatchProperty.Controls.Add(this.btnShowDropControl);
            this.grpWatchProperty.Controls.Add(this.numTcpPort);
            this.grpWatchProperty.Controls.Add(this.lblTcpPort);
            this.grpWatchProperty.Controls.Add(this.btnGetManufatureId);
            this.grpWatchProperty.Controls.Add(this.lboxApnAccessMode);
            this.grpWatchProperty.Controls.Add(this.txtApnAccessMode);
            this.grpWatchProperty.Controls.Add(this.label4);
            this.grpWatchProperty.Controls.Add(this.numEffectiveTime);
            this.grpWatchProperty.Controls.Add(this.lblEffectiveTime);
            this.grpWatchProperty.Controls.Add(this.txtTerminalUpgradeAddress);
            this.grpWatchProperty.Controls.Add(this.lblTerminalUpgradeAddress);
            this.grpWatchProperty.Controls.Add(this.txtFirmWareNum);
            this.grpWatchProperty.Controls.Add(this.lblFirmWareNum);
            this.grpWatchProperty.Controls.Add(this.txtHardWareNum);
            this.grpWatchProperty.Controls.Add(this.lblHardWareNum);
            this.grpWatchProperty.Controls.Add(this.txtManufacturerID);
            this.grpWatchProperty.Controls.Add(this.lblManufacturerID);
            this.grpWatchProperty.Controls.Add(this.txtPwd);
            this.grpWatchProperty.Controls.Add(this.lblPwd);
            this.grpWatchProperty.Controls.Add(this.txtUser);
            this.grpWatchProperty.Controls.Add(this.lblUser);
            this.grpWatchProperty.Controls.Add(this.lblUdpPort);
            this.grpWatchProperty.Controls.Add(this.txtUpgradeServerIp);
            this.grpWatchProperty.Controls.Add(this.lblUpgradeServerIp);
            this.grpWatchProperty.Controls.Add(this.lblApnAccessMode);
            this.grpWatchProperty.Dock = DockStyle.Top;
            this.grpWatchProperty.Location = new System.Drawing.Point(5, 121);
            this.grpWatchProperty.Name = "grpWatchProperty";
            this.grpWatchProperty.Size = new Size(469, 169);
            this.grpWatchProperty.TabIndex = 11;
            this.grpWatchProperty.TabStop = false;
            this.grpWatchProperty.Text = "设置参数";
            this.btnShowDropControl.Location = new System.Drawing.Point(221, 12);
            this.btnShowDropControl.Name = "btnShowDropControl";
            this.btnShowDropControl.Size = new Size(23, 23);
            this.btnShowDropControl.TabIndex = 27;
            this.btnShowDropControl.Text = "▼";
            this.btnShowDropControl.UseVisualStyleBackColor = true;
            this.btnShowDropControl.Click += new EventHandler(this.btnShowDropControl_Click);
            this.numTcpPort.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numTcpPort.Location = new System.Drawing.Point(339, 13);
            int[] bits = new int[4];
            bits[0] = 65535;
            this.numTcpPort.Maximum = new decimal(bits);
            int[] numArray2 = new int[4];
            numArray2[0] = 1;
            this.numTcpPort.Minimum = new decimal(numArray2);
            this.numTcpPort.Name = "numTcpPort";
            this.numTcpPort.Size = new Size(58, 21);
            this.numTcpPort.TabIndex = 26;
            this.numTcpPort.Tag = "；";
            int[] numArray3 = new int[4];
            numArray3[0] = 1;
            this.numTcpPort.Value = new decimal(numArray3);
            this.lblTcpPort.AutoSize = true;
            this.lblTcpPort.Location = new System.Drawing.Point(274, 17);
            this.lblTcpPort.Name = "lblTcpPort";
            this.lblTcpPort.Size = new Size(59, 12);
            this.lblTcpPort.TabIndex = 25;
            this.lblTcpPort.Text = "TCP端口：";
            this.btnGetManufatureId.Location = new System.Drawing.Point(204, 89);
            this.btnGetManufatureId.Name = "btnGetManufatureId";
            this.btnGetManufatureId.Size = new Size(39, 23);
            this.btnGetManufatureId.TabIndex = 24;
            this.btnGetManufatureId.Text = "获取";
            this.btnGetManufatureId.UseVisualStyleBackColor = true;
            this.btnGetManufatureId.Click += new EventHandler(this.btnGetManufatureId_Click);
            this.lboxApnAccessMode.FormattingEnabled = true;
            this.lboxApnAccessMode.ItemHeight = 12;
            this.lboxApnAccessMode.Items.AddRange(new object[] { "APN", "CDMA", "CMNET" });
            this.lboxApnAccessMode.Location = new System.Drawing.Point(122, 34);
            this.lboxApnAccessMode.Name = "lboxApnAccessMode";
            this.lboxApnAccessMode.Size = new Size(121, 40);
            this.lboxApnAccessMode.TabIndex = 23;
            this.lboxApnAccessMode.Visible = false;
            this.lboxApnAccessMode.SelectedIndexChanged += new EventHandler(this.lboxApnAccessMode_SelectedIndexChanged);
            this.txtApnAccessMode.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtApnAccessMode.Location = new System.Drawing.Point(122, 13);
            this.txtApnAccessMode.MaxLength = 20;
            this.txtApnAccessMode.Name = "txtApnAccessMode";
            this.txtApnAccessMode.Size = new Size(99, 21);
            this.txtApnAccessMode.TabIndex = 22;
            this.txtApnAccessMode.TextChanged += new EventHandler(this.txtApnAccessMode_TextChanged);
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(403, 147);
            this.label4.Name = "label4";
            this.label4.Size = new Size(29, 12);
            this.label4.TabIndex = 21;
            this.label4.Text = "分钟";
            this.numEffectiveTime.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numEffectiveTime.Location = new System.Drawing.Point(339, 143);
            int[] numArray4 = new int[4];
            numArray4[0] = 65535;
            this.numEffectiveTime.Maximum = new decimal(numArray4);
            int[] numArray5 = new int[4];
            numArray5[0] = 1;
            this.numEffectiveTime.Minimum = new decimal(numArray5);
            this.numEffectiveTime.Name = "numEffectiveTime";
            this.numEffectiveTime.Size = new Size(58, 21);
            this.numEffectiveTime.TabIndex = 20;
            this.numEffectiveTime.Tag = "；";
            int[] numArray6 = new int[4];
            numArray6[0] = 1;
            this.numEffectiveTime.Value = new decimal(numArray6);
            this.lblEffectiveTime.AutoSize = true;
            this.lblEffectiveTime.Location = new System.Drawing.Point(196, 148);
            this.lblEffectiveTime.Name = "lblEffectiveTime";
            this.lblEffectiveTime.Size = new Size(137, 12);
            this.lblEffectiveTime.TabIndex = 19;
            this.lblEffectiveTime.Text = "收到升级指令有效时间：";
            this.txtTerminalUpgradeAddress.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTerminalUpgradeAddress.Location = new System.Drawing.Point(339, 116);
            this.txtTerminalUpgradeAddress.MaxLength = 50;
            this.txtTerminalUpgradeAddress.Name = "txtTerminalUpgradeAddress";
            this.txtTerminalUpgradeAddress.Size = new Size(121, 21);
            this.txtTerminalUpgradeAddress.TabIndex = 18;
            this.lblTerminalUpgradeAddress.AutoSize = true;
            this.lblTerminalUpgradeAddress.Location = new System.Drawing.Point(244, 119);
            this.lblTerminalUpgradeAddress.Name = "lblTerminalUpgradeAddress";
            this.lblTerminalUpgradeAddress.Size = new Size(89, 12);
            this.lblTerminalUpgradeAddress.TabIndex = 17;
            this.lblTerminalUpgradeAddress.Text = "终端升级地址：";
            this.txtFirmWareNum.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtFirmWareNum.Location = new System.Drawing.Point(122, 116);
            this.txtFirmWareNum.MaxLength = 20;
            this.txtFirmWareNum.Name = "txtFirmWareNum";
            this.txtFirmWareNum.Size = new Size(121, 21);
            this.txtFirmWareNum.TabIndex = 16;
            this.lblFirmWareNum.AutoSize = true;
            this.lblFirmWareNum.Location = new System.Drawing.Point(51, 119);
            this.lblFirmWareNum.Name = "lblFirmWareNum";
            this.lblFirmWareNum.Size = new Size(65, 12);
            this.lblFirmWareNum.TabIndex = 15;
            this.lblFirmWareNum.Text = "固件版本：";
            this.txtHardWareNum.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtHardWareNum.Location = new System.Drawing.Point(339, 89);
            this.txtHardWareNum.MaxLength = 20;
            this.txtHardWareNum.Name = "txtHardWareNum";
            this.txtHardWareNum.Size = new Size(121, 21);
            this.txtHardWareNum.TabIndex = 14;
            this.lblHardWareNum.AutoSize = true;
            this.lblHardWareNum.Location = new System.Drawing.Point(268, 92);
            this.lblHardWareNum.Name = "lblHardWareNum";
            this.lblHardWareNum.Size = new Size(65, 12);
            this.lblHardWareNum.TabIndex = 13;
            this.lblHardWareNum.Text = "硬件版本：";
            this.txtManufacturerID.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtManufacturerID.Location = new System.Drawing.Point(122, 89);
            this.txtManufacturerID.MaxLength = 20;
            this.txtManufacturerID.Name = "txtManufacturerID";
            this.txtManufacturerID.Size = new Size(79, 21);
            this.txtManufacturerID.TabIndex = 12;
            this.txtManufacturerID.KeyPress += new KeyPressEventHandler(this.txtManufacturerID_KeyPress);
            this.lblManufacturerID.AutoSize = true;
            this.lblManufacturerID.Location = new System.Drawing.Point(51, 92);
            this.lblManufacturerID.Name = "lblManufacturerID";
            this.lblManufacturerID.Size = new Size(65, 12);
            this.lblManufacturerID.TabIndex = 11;
            this.lblManufacturerID.Text = "制造商ID：";
            this.txtPwd.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPwd.Location = new System.Drawing.Point(339, 62);
            this.txtPwd.MaxLength = 16;
            this.txtPwd.Name = "txtPwd";
            this.txtPwd.PasswordChar = '*';
            this.txtPwd.Size = new Size(121, 21);
            this.txtPwd.TabIndex = 10;
            this.txtPwd.Tag = "；";
            this.lblPwd.AutoSize = true;
            this.lblPwd.Location = new System.Drawing.Point(268, 67);
            this.lblPwd.Name = "lblPwd";
            this.lblPwd.Size = new Size(65, 12);
            this.lblPwd.TabIndex = 8;
            this.lblPwd.Text = "拨号密码：";
            this.txtUser.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtUser.Location = new System.Drawing.Point(122, 62);
            this.txtUser.MaxLength = 16;
            this.txtUser.Name = "txtUser";
            this.txtUser.Size = new Size(121, 21);
            this.txtUser.TabIndex = 9;
            this.txtUser.Tag = "；";
            this.lblUser.AutoSize = true;
            this.lblUser.Location = new System.Drawing.Point(39, 67);
            this.lblUser.Name = "lblUser";
            this.lblUser.Size = new Size(77, 12);
            this.lblUser.TabIndex = 7;
            this.lblUser.Text = "拨号用户名：";
            this.lblUdpPort.AutoSize = true;
            this.lblUdpPort.Location = new System.Drawing.Point(274, 42);
            this.lblUdpPort.Name = "lblUdpPort";
            this.lblUdpPort.Size = new Size(59, 12);
            this.lblUdpPort.TabIndex = 5;
            this.lblUdpPort.Text = "UDP端口：";
            this.txtUpgradeServerIp.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtUpgradeServerIp.Location = new System.Drawing.Point(122, 37);
            this.txtUpgradeServerIp.Margin = new Padding(0);
            this.txtUpgradeServerIp.Name = "txtUpgradeServerIp";
            this.txtUpgradeServerIp.Size = new Size(121, 21);
            this.txtUpgradeServerIp.TabIndex = 3;
            this.txtUpgradeServerIp.Tag = "；";
            this.lblUpgradeServerIp.AutoSize = true;
            this.lblUpgradeServerIp.Location = new System.Drawing.Point(26, 42);
            this.lblUpgradeServerIp.Name = "lblUpgradeServerIp";
            this.lblUpgradeServerIp.Size = new Size(89, 12);
            this.lblUpgradeServerIp.TabIndex = 4;
            this.lblUpgradeServerIp.Text = "升级服务器IP：";
            this.lblApnAccessMode.AutoSize = true;
            this.lblApnAccessMode.Location = new System.Drawing.Point(9, 17);
            this.lblApnAccessMode.Name = "lblApnAccessMode";
            this.lblApnAccessMode.Size = new Size(107, 12);
            this.lblApnAccessMode.TabIndex = 0;
            this.lblApnAccessMode.Text = "APN拨号接入方式：";
            this.numUdpPort.Location = new System.Drawing.Point(339, 38);
            this.numUdpPort.MaxLength = 5;
            this.numUdpPort.Name = "numUdpPort";
            this.numUdpPort.Size = new Size(58, 21);
            this.numUdpPort.TabIndex = 28;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(479, 323);
            base.Controls.Add(this.grpWatchProperty);
            base.Name = "JTBWirelessUpgradeCommand";
            this.Text = "JTBWirelessUpgradeCommand";
            base.Load += new EventHandler(this.JTBWirelessUpgradeCommand_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpWatchProperty, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpWatchProperty.ResumeLayout(false);
            this.grpWatchProperty.PerformLayout();
            this.numTcpPort.EndInit();
            this.numEffectiveTime.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private AutoDropDown _appServerList;
        private Button btnGetManufatureId;
        private Button btnShowDropControl;
        private System.Windows.Forms.GroupBox grpWatchProperty;
        private Label label4;
        private Label lblApnAccessMode;
        private Label lblEffectiveTime;
        private Label lblFirmWareNum;
        private Label lblHardWareNum;
        private Label lblManufacturerID;
        private Label lblPwd;
        private Label lblTcpPort;
        private Label lblTerminalUpgradeAddress;
        private Label lblUdpPort;
        private Label lblUpgradeServerIp;
        private Label lblUser;
        private ListBox lboxApnAccessMode;
        private NumericUpDown numEffectiveTime;
        private NumericUpDown numTcpPort;
        private TextBox numUdpPort;
        private TextBox txtApnAccessMode;
        private TextBox txtFirmWareNum;
        private TextBox txtHardWareNum;
        private TextBox txtManufacturerID;
        private TextBox txtPwd;
        private TextBox txtTerminalUpgradeAddress;
        private IPAddressTextBox txtUpgradeServerIp;
        private TextBox txtUser;
    }
}