namespace Client.M2M
{
    using Client;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class m2mLedDelMsg
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(m2mLedDelMsg));
            this.grpMsgParam = new GroupBox();
            this.pnlLedMsg = new Panel();
            this.lblLedMsgIndex = new Label();
            this.numLedMsgIndex = new NumericUpDown();
            this.lblDelIndex = new Label();
            this.pnlLedMsgParam = new Panel();
            this.chkShowModel = new CheckBox();
            this.grpShowModel = new GroupBox();
            this.rdoDrive = new RadioButton();
            this.rdoStop = new RadioButton();
            this.rdoAll = new RadioButton();
            this.grpScreenModel = new GroupBox();
            this.rdoLeft = new RadioButton();
            this.rdoUpDown = new RadioButton();
            this.chkShowFont = new CheckBox();
            this.cmbShowFont = new ComBox();
            this.chkShowSpeed = new CheckBox();
            this.cmbShowSpeed = new ComBox();
            this.chkShowTimes = new CheckBox();
            this.numShowTimes = new NumericUpDown();
            this.chkInterval = new CheckBox();
            this.numInterval = new NumericUpDown();
            this.lblIntervalUnit = new Label();
            this.chkLighteness = new CheckBox();
            this.numLighteness = new NumericUpDown();
            this.chkStopTime = new CheckBox();
            this.numStopTime = new NumericUpDown();
            this.label1 = new Label();
            this.chkShowTime = new CheckBox();
            this.pnlShowTime = new Panel();
            this.lblBetween = new Label();
            this.dtpStartDate = new DateTimePicker();
            this.dtpStartTime = new DateTimePicker();
            this.dtpEndDate = new DateTimePicker();
            this.dtpEndTime = new DateTimePicker();
            this.chkShowTimeSecond = new CheckBox();
            this.pnlShowTimeSecond = new Panel();
            this.tsAddDel = new ToolStrip();
            this.tsbAdd = new ToolStripButton();
            this.tsbDel = new ToolStripButton();
            this.lblBetween2 = new Label();
            this.dtpStartDate2 = new DateTimePicker();
            this.dtpEndDate2 = new DateTimePicker();
            this.dtpStartTime2 = new DateTimePicker();
            this.dtpEndTime2 = new DateTimePicker();
            this.lvLedLight = new ListView();
            this.label2 = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpMsgParam.SuspendLayout();
            this.pnlLedMsg.SuspendLayout();
            this.numLedMsgIndex.BeginInit();
            this.pnlLedMsgParam.SuspendLayout();
            this.grpShowModel.SuspendLayout();
            this.grpScreenModel.SuspendLayout();
            this.numShowTimes.BeginInit();
            this.numInterval.BeginInit();
            this.numLighteness.BeginInit();
            this.numStopTime.BeginInit();
            this.pnlShowTime.SuspendLayout();
            this.pnlShowTimeSecond.SuspendLayout();
            this.tsAddDel.SuspendLayout();
            base.SuspendLayout();
            base.grpCar.TabIndex = 0;
            base.pnlBtn.Location = new System.Drawing.Point(5, 529);
            base.pnlBtn.TabIndex = 2;
            this.grpMsgParam.AutoSize = true;
            this.grpMsgParam.Controls.Add(this.pnlLedMsg);
            this.grpMsgParam.Controls.Add(this.pnlLedMsgParam);
            this.grpMsgParam.Dock = DockStyle.Top;
            this.grpMsgParam.Location = new System.Drawing.Point(5, 121);
            this.grpMsgParam.Name = "grpMsgParam";
            this.grpMsgParam.Size = new Size(363, 408);
            this.grpMsgParam.TabIndex = 1;
            this.grpMsgParam.TabStop = false;
            this.pnlLedMsg.AutoSize = true;
            this.pnlLedMsg.Controls.Add(this.lblLedMsgIndex);
            this.pnlLedMsg.Controls.Add(this.numLedMsgIndex);
            this.pnlLedMsg.Controls.Add(this.lblDelIndex);
            this.pnlLedMsg.Dock = DockStyle.Bottom;
            this.pnlLedMsg.Location = new System.Drawing.Point(3, 17);
            this.pnlLedMsg.Name = "pnlLedMsg";
            this.pnlLedMsg.Size = new Size(357, 38);
            this.pnlLedMsg.TabIndex = 0;
            this.lblLedMsgIndex.AutoSize = true;
            this.lblLedMsgIndex.Location = new System.Drawing.Point(47, 6);
            this.lblLedMsgIndex.Name = "lblLedMsgIndex";
            this.lblLedMsgIndex.Size = new Size(65, 12);
            this.lblLedMsgIndex.TabIndex = 2;
            this.lblLedMsgIndex.Text = "短信索引：";
            this.numLedMsgIndex.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numLedMsgIndex.Location = new System.Drawing.Point(119, 2);
            int[] bits = new int[4];
            bits[0] = 65536;
            this.numLedMsgIndex.Maximum = new decimal(bits);
            int[] numArray2 = new int[4];
            numArray2[0] = 1;
            this.numLedMsgIndex.Minimum = new decimal(numArray2);
            this.numLedMsgIndex.Name = "numLedMsgIndex";
            this.numLedMsgIndex.Size = new Size(161, 21);
            this.numLedMsgIndex.TabIndex = 0;
            this.numLedMsgIndex.Tag = "；";
            int[] numArray3 = new int[4];
            numArray3[0] = 1;
            this.numLedMsgIndex.Value = new decimal(numArray3);
            this.lblDelIndex.AutoSize = true;
            this.lblDelIndex.Location = new System.Drawing.Point(110, 26);
            this.lblDelIndex.Name = "lblDelIndex";
            this.lblDelIndex.Size = new Size(215, 12);
            this.lblDelIndex.TabIndex = 4;
            this.lblDelIndex.Tag = "9999";
            this.lblDelIndex.Text = "（注：0表示删除全部。范围0～65535）";
            this.pnlLedMsgParam.Controls.Add(this.chkShowModel);
            this.pnlLedMsgParam.Controls.Add(this.grpShowModel);
            this.pnlLedMsgParam.Controls.Add(this.grpScreenModel);
            this.pnlLedMsgParam.Controls.Add(this.chkShowFont);
            this.pnlLedMsgParam.Controls.Add(this.cmbShowFont);
            this.pnlLedMsgParam.Controls.Add(this.chkShowSpeed);
            this.pnlLedMsgParam.Controls.Add(this.cmbShowSpeed);
            this.pnlLedMsgParam.Controls.Add(this.chkShowTimes);
            this.pnlLedMsgParam.Controls.Add(this.numShowTimes);
            this.pnlLedMsgParam.Controls.Add(this.chkInterval);
            this.pnlLedMsgParam.Controls.Add(this.numInterval);
            this.pnlLedMsgParam.Controls.Add(this.lblIntervalUnit);
            this.pnlLedMsgParam.Controls.Add(this.chkLighteness);
            this.pnlLedMsgParam.Controls.Add(this.numLighteness);
            this.pnlLedMsgParam.Controls.Add(this.chkStopTime);
            this.pnlLedMsgParam.Controls.Add(this.numStopTime);
            this.pnlLedMsgParam.Controls.Add(this.label1);
            this.pnlLedMsgParam.Controls.Add(this.chkShowTime);
            this.pnlLedMsgParam.Controls.Add(this.pnlShowTime);
            this.pnlLedMsgParam.Controls.Add(this.chkShowTimeSecond);
            this.pnlLedMsgParam.Controls.Add(this.pnlShowTimeSecond);
            this.pnlLedMsgParam.Controls.Add(this.label2);
            this.pnlLedMsgParam.Dock = DockStyle.Bottom;
            this.pnlLedMsgParam.Location = new System.Drawing.Point(3, 55);
            this.pnlLedMsgParam.Name = "pnlLedMsgParam";
            this.pnlLedMsgParam.Size = new Size(357, 350);
            this.pnlLedMsgParam.TabIndex = 1;
            this.pnlLedMsgParam.Visible = false;
            this.chkShowModel.AutoSize = true;
            this.chkShowModel.Location = new System.Drawing.Point(21, 11);
            this.chkShowModel.Name = "chkShowModel";
            this.chkShowModel.Size = new Size(72, 16);
            this.chkShowModel.TabIndex = 31;
            this.chkShowModel.Text = "显示模式";
            this.chkShowModel.UseVisualStyleBackColor = true;
            this.chkShowModel.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.grpShowModel.Controls.Add(this.rdoDrive);
            this.grpShowModel.Controls.Add(this.rdoStop);
            this.grpShowModel.Controls.Add(this.rdoAll);
            this.grpShowModel.Enabled = false;
            this.grpShowModel.Location = new System.Drawing.Point(102, 0);
            this.grpShowModel.Name = "grpShowModel";
            this.grpShowModel.Size = new Size(229, 30);
            this.grpShowModel.TabIndex = 51;
            this.grpShowModel.TabStop = false;
            this.rdoDrive.AutoSize = true;
            this.rdoDrive.Checked = true;
            this.rdoDrive.Location = new System.Drawing.Point(6, 10);
            this.rdoDrive.Name = "rdoDrive";
            this.rdoDrive.Size = new Size(71, 16);
            this.rdoDrive.TabIndex = 0;
            this.rdoDrive.TabStop = true;
            this.rdoDrive.Text = "开车显示";
            this.rdoDrive.UseVisualStyleBackColor = true;
            this.rdoStop.AutoSize = true;
            this.rdoStop.Location = new System.Drawing.Point(83, 10);
            this.rdoStop.Name = "rdoStop";
            this.rdoStop.Size = new Size(71, 16);
            this.rdoStop.TabIndex = 1;
            this.rdoStop.Text = "停车显示";
            this.rdoStop.UseVisualStyleBackColor = true;
            this.rdoAll.AutoSize = true;
            this.rdoAll.Location = new System.Drawing.Point(160, 10);
            this.rdoAll.Name = "rdoAll";
            this.rdoAll.Size = new Size(59, 16);
            this.rdoAll.TabIndex = 2;
            this.rdoAll.Text = "均显示";
            this.rdoAll.UseVisualStyleBackColor = true;
            this.grpScreenModel.Controls.Add(this.rdoLeft);
            this.grpScreenModel.Controls.Add(this.rdoUpDown);
            this.grpScreenModel.Enabled = false;
            this.grpScreenModel.Location = new System.Drawing.Point(102, 29);
            this.grpScreenModel.Name = "grpScreenModel";
            this.grpScreenModel.Size = new Size(229, 30);
            this.grpScreenModel.TabIndex = 52;
            this.grpScreenModel.TabStop = false;
            this.rdoLeft.AutoSize = true;
            this.rdoLeft.Checked = true;
            this.rdoLeft.Location = new System.Drawing.Point(6, 10);
            this.rdoLeft.Name = "rdoLeft";
            this.rdoLeft.Size = new Size(59, 16);
            this.rdoLeft.TabIndex = 0;
            this.rdoLeft.TabStop = true;
            this.rdoLeft.Text = "左滚屏";
            this.rdoLeft.UseVisualStyleBackColor = true;
            this.rdoUpDown.AutoSize = true;
            this.rdoUpDown.Location = new System.Drawing.Point(83, 10);
            this.rdoUpDown.Name = "rdoUpDown";
            this.rdoUpDown.Size = new Size(71, 16);
            this.rdoUpDown.TabIndex = 1;
            this.rdoUpDown.Text = "上下滚屏";
            this.rdoUpDown.UseVisualStyleBackColor = true;
            this.chkShowFont.AutoSize = true;
            this.chkShowFont.Location = new System.Drawing.Point(21, 66);
            this.chkShowFont.Name = "chkShowFont";
            this.chkShowFont.Size = new Size(72, 16);
            this.chkShowFont.TabIndex = 32;
            this.chkShowFont.Text = "显示字体";
            this.chkShowFont.UseVisualStyleBackColor = true;
            this.chkShowFont.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.cmbShowFont.DisplayMember = "Display";
            this.cmbShowFont.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbShowFont.Enabled = false;
            this.cmbShowFont.FlatStyle = FlatStyle.Flat;
            this.cmbShowFont.FormattingEnabled = true;
            this.cmbShowFont.Location = new System.Drawing.Point(102, 64);
            this.cmbShowFont.Name = "cmbShowFont";
            this.cmbShowFont.Size = new Size(65, 20);
            this.cmbShowFont.TabIndex = 33;
            this.cmbShowFont.Tag = "；";
            this.cmbShowFont.ValueMember = "Value";
            this.chkShowSpeed.AutoSize = true;
            this.chkShowSpeed.Location = new System.Drawing.Point(173, 66);
            this.chkShowSpeed.Name = "chkShowSpeed";
            this.chkShowSpeed.Size = new Size(72, 16);
            this.chkShowSpeed.TabIndex = 34;
            this.chkShowSpeed.Text = "显示速度";
            this.chkShowSpeed.UseVisualStyleBackColor = true;
            this.chkShowSpeed.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.cmbShowSpeed.DisplayMember = "Display";
            this.cmbShowSpeed.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbShowSpeed.Enabled = false;
            this.cmbShowSpeed.FlatStyle = FlatStyle.Flat;
            this.cmbShowSpeed.FormattingEnabled = true;
            this.cmbShowSpeed.Location = new System.Drawing.Point(245, 64);
            this.cmbShowSpeed.Name = "cmbShowSpeed";
            this.cmbShowSpeed.Size = new Size(84, 20);
            this.cmbShowSpeed.TabIndex = 35;
            this.cmbShowSpeed.Tag = "；";
            this.cmbShowSpeed.ValueMember = "Value";
            this.chkShowTimes.AutoSize = true;
            this.chkShowTimes.Location = new System.Drawing.Point(21, 90);
            this.chkShowTimes.Name = "chkShowTimes";
            this.chkShowTimes.Size = new Size(72, 16);
            this.chkShowTimes.TabIndex = 38;
            this.chkShowTimes.Text = "显示次数";
            this.chkShowTimes.UseVisualStyleBackColor = true;
            this.chkShowTimes.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.numShowTimes.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numShowTimes.Enabled = false;
            this.numShowTimes.Location = new System.Drawing.Point(102, 87);
            int[] numArray4 = new int[4];
            numArray4[0] = 65535;
            this.numShowTimes.Maximum = new decimal(numArray4);
            int[] numArray5 = new int[4];
            numArray5[0] = 1;
            this.numShowTimes.Minimum = new decimal(numArray5);
            this.numShowTimes.Name = "numShowTimes";
            this.numShowTimes.Size = new Size(64, 21);
            this.numShowTimes.TabIndex = 39;
            this.numShowTimes.Tag = "；";
            int[] numArray6 = new int[4];
            numArray6[0] = 1;
            this.numShowTimes.Value = new decimal(numArray6);
            this.chkInterval.AutoSize = true;
            this.chkInterval.Location = new System.Drawing.Point(173, 89);
            this.chkInterval.Name = "chkInterval";
            this.chkInterval.Size = new Size(72, 16);
            this.chkInterval.TabIndex = 36;
            this.chkInterval.Text = "翻屏间隔";
            this.chkInterval.UseVisualStyleBackColor = true;
            this.chkInterval.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.numInterval.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numInterval.Enabled = false;
            this.numInterval.Location = new System.Drawing.Point(245, 87);
            int[] numArray7 = new int[4];
            numArray7[0] = 65535;
            this.numInterval.Maximum = new decimal(numArray7);
            int[] numArray8 = new int[4];
            numArray8[0] = 1;
            this.numInterval.Minimum = new decimal(numArray8);
            this.numInterval.Name = "numInterval";
            this.numInterval.Size = new Size(54, 21);
            this.numInterval.TabIndex = 37;
            this.numInterval.Tag = "\x00d7";
            int[] numArray9 = new int[4];
            numArray9[0] = 1;
            this.numInterval.Value = new decimal(numArray9);
            this.lblIntervalUnit.AutoSize = true;
            this.lblIntervalUnit.Location = new System.Drawing.Point(300, 91);
            this.lblIntervalUnit.Name = "lblIntervalUnit";
            this.lblIntervalUnit.Size = new Size(35, 12);
            this.lblIntervalUnit.TabIndex = 48;
            this.lblIntervalUnit.Tag = "；";
            this.lblIntervalUnit.Text = "0.1秒";
            this.chkLighteness.AutoSize = true;
            this.chkLighteness.Location = new System.Drawing.Point(21, 114);
            this.chkLighteness.Name = "chkLighteness";
            this.chkLighteness.Size = new Size(72, 16);
            this.chkLighteness.TabIndex = 42;
            this.chkLighteness.Text = "显示亮度";
            this.chkLighteness.UseVisualStyleBackColor = true;
            this.chkLighteness.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.numLighteness.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numLighteness.Enabled = false;
            this.numLighteness.Location = new System.Drawing.Point(102, 112);
            int[] numArray10 = new int[4];
            numArray10[0] = 65535;
            this.numLighteness.Maximum = new decimal(numArray10);
            int[] numArray11 = new int[4];
            numArray11[0] = 1;
            this.numLighteness.Minimum = new decimal(numArray11);
            this.numLighteness.Name = "numLighteness";
            this.numLighteness.Size = new Size(64, 21);
            this.numLighteness.TabIndex = 43;
            this.numLighteness.Tag = "；";
            int[] numArray12 = new int[4];
            numArray12[0] = 1;
            this.numLighteness.Value = new decimal(numArray12);
            this.chkStopTime.AutoSize = true;
            this.chkStopTime.Location = new System.Drawing.Point(173, 114);
            this.chkStopTime.Name = "chkStopTime";
            this.chkStopTime.Size = new Size(72, 16);
            this.chkStopTime.TabIndex = 40;
            this.chkStopTime.Text = "停留时间";
            this.chkStopTime.UseVisualStyleBackColor = true;
            this.chkStopTime.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.numStopTime.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numStopTime.Enabled = false;
            this.numStopTime.Location = new System.Drawing.Point(245, 112);
            int[] numArray13 = new int[4];
            numArray13[0] = 65535;
            this.numStopTime.Maximum = new decimal(numArray13);
            this.numStopTime.Name = "numStopTime";
            this.numStopTime.Size = new Size(54, 21);
            this.numStopTime.TabIndex = 41;
            this.numStopTime.Tag = "\x00d7";
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(299, 116);
            this.label1.Name = "label1";
            this.label1.Size = new Size(35, 12);
            this.label1.TabIndex = 47;
            this.label1.Tag = "；";
            this.label1.Text = "0.1秒";
            this.chkShowTime.AutoSize = true;
            this.chkShowTime.Location = new System.Drawing.Point(21, 140);
            this.chkShowTime.Name = "chkShowTime";
            this.chkShowTime.Size = new Size(72, 16);
            this.chkShowTime.TabIndex = 44;
            this.chkShowTime.Text = "单时间段";
            this.chkShowTime.UseVisualStyleBackColor = true;
            this.chkShowTime.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.pnlShowTime.Controls.Add(this.lblBetween);
            this.pnlShowTime.Controls.Add(this.dtpStartDate);
            this.pnlShowTime.Controls.Add(this.dtpStartTime);
            this.pnlShowTime.Controls.Add(this.dtpEndDate);
            this.pnlShowTime.Controls.Add(this.dtpEndTime);
            this.pnlShowTime.Enabled = false;
            this.pnlShowTime.Location = new System.Drawing.Point(94, 136);
            this.pnlShowTime.Name = "pnlShowTime";
            this.pnlShowTime.Size = new Size(211, 60);
            this.pnlShowTime.TabIndex = 45;
            this.lblBetween.AutoSize = true;
            this.lblBetween.Location = new System.Drawing.Point(217, 8);
            this.lblBetween.Name = "lblBetween";
            this.lblBetween.Size = new Size(17, 12);
            this.lblBetween.TabIndex = 4;
            this.lblBetween.Text = "～";
            this.dtpStartDate.CustomFormat = "yyyy-MM-dd";
            this.dtpStartDate.Format = DateTimePickerFormat.Custom;
            this.dtpStartDate.Location = new System.Drawing.Point(8, 1);
            this.dtpStartDate.Name = "dtpStartDate";
            this.dtpStartDate.Size = new Size(88, 21);
            this.dtpStartDate.TabIndex = 0;
            this.dtpStartDate.Tag = " ";
            this.dtpStartTime.CustomFormat = "HH:mm:ss";
            this.dtpStartTime.Format = DateTimePickerFormat.Custom;
            this.dtpStartTime.Location = new System.Drawing.Point(103, 1);
            this.dtpStartTime.Name = "dtpStartTime";
            this.dtpStartTime.ShowUpDown = true;
            this.dtpStartTime.Size = new Size(83, 21);
            this.dtpStartTime.TabIndex = 1;
            this.dtpStartTime.TabStop = false;
            this.dtpStartTime.Tag = "～";
            this.dtpStartTime.Value = new DateTime(2010, 8, 5, 0, 0, 0, 0);
            this.dtpEndDate.CustomFormat = "yyyy-MM-dd";
            this.dtpEndDate.Format = DateTimePickerFormat.Custom;
            this.dtpEndDate.Location = new System.Drawing.Point(8, 31);
            this.dtpEndDate.Name = "dtpEndDate";
            this.dtpEndDate.Size = new Size(88, 21);
            this.dtpEndDate.TabIndex = 2;
            this.dtpEndDate.Tag = " ";
            this.dtpEndTime.CustomFormat = "HH:mm:ss";
            this.dtpEndTime.Format = DateTimePickerFormat.Custom;
            this.dtpEndTime.Location = new System.Drawing.Point(103, 31);
            this.dtpEndTime.Name = "dtpEndTime";
            this.dtpEndTime.ShowUpDown = true;
            this.dtpEndTime.Size = new Size(83, 21);
            this.dtpEndTime.TabIndex = 3;
            this.dtpEndTime.Tag = "；";
            this.chkShowTimeSecond.AutoSize = true;
            this.chkShowTimeSecond.Location = new System.Drawing.Point(21, 213);
            this.chkShowTimeSecond.Name = "chkShowTimeSecond";
            this.chkShowTimeSecond.Size = new Size(72, 16);
            this.chkShowTimeSecond.TabIndex = 46;
            this.chkShowTimeSecond.Text = "多时间段";
            this.chkShowTimeSecond.UseVisualStyleBackColor = true;
            this.chkShowTimeSecond.CheckedChanged += new EventHandler(this.chkShowTimeSecond_CheckedChanged);
            this.pnlShowTimeSecond.Controls.Add(this.tsAddDel);
            this.pnlShowTimeSecond.Controls.Add(this.lblBetween2);
            this.pnlShowTimeSecond.Controls.Add(this.dtpStartDate2);
            this.pnlShowTimeSecond.Controls.Add(this.dtpEndDate2);
            this.pnlShowTimeSecond.Controls.Add(this.dtpStartTime2);
            this.pnlShowTimeSecond.Controls.Add(this.dtpEndTime2);
            this.pnlShowTimeSecond.Controls.Add(this.lvLedLight);
            this.pnlShowTimeSecond.Enabled = false;
            this.pnlShowTimeSecond.Location = new System.Drawing.Point(94, 202);
            this.pnlShowTimeSecond.Name = "pnlShowTimeSecond";
            this.pnlShowTimeSecond.Size = new Size(211, 126);
            this.pnlShowTimeSecond.TabIndex = 50;
            this.tsAddDel.BackColor = Color.Transparent;
            this.tsAddDel.Dock = DockStyle.None;
            this.tsAddDel.GripStyle = ToolStripGripStyle.Hidden;
            this.tsAddDel.ImageScalingSize = new Size(17, 20);
            this.tsAddDel.Items.AddRange(new ToolStripItem[] { this.tsbAdd, this.tsbDel });
            this.tsAddDel.Location = new System.Drawing.Point(165, 31);
            this.tsAddDel.Name = "tsAddDel";
            this.tsAddDel.Padding = new Padding(0);
            this.tsAddDel.Size = new Size(48, 25);
            this.tsAddDel.TabIndex = 8;
            this.tsAddDel.Tag = "";
            this.tsbAdd.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.tsbAdd.Image = (Image) resources.GetObject("tsbAdd.Image");
            this.tsbAdd.ImageScaling = ToolStripItemImageScaling.None;
            this.tsbAdd.ImageTransparentColor = Color.Magenta;
            this.tsbAdd.Margin = new Padding(0, 0, 0, 1);
            this.tsbAdd.Name = "tsbAdd";
            this.tsbAdd.Padding = new Padding(2, 0, 1, 0);
            this.tsbAdd.Size = new Size(23, 24);
            this.tsbAdd.Tag = "9999";
            this.tsbAdd.Text = "添加";
            this.tsbAdd.Click += new EventHandler(this.tsbAdd_Click);
            this.tsbDel.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.tsbDel.Image = (Image) resources.GetObject("tsbDel.Image");
            this.tsbDel.ImageScaling = ToolStripItemImageScaling.None;
            this.tsbDel.ImageTransparentColor = Color.Magenta;
            this.tsbDel.Margin = new Padding(0, 0, 0, 1);
            this.tsbDel.Name = "tsbDel";
            this.tsbDel.Padding = new Padding(2, 0, 1, 0);
            this.tsbDel.Size = new Size(23, 24);
            this.tsbDel.Tag = "9999";
            this.tsbDel.Text = "删除";
            this.tsbDel.Click += new EventHandler(this.tsbDel_Click);
            this.lblBetween2.AutoSize = true;
            this.lblBetween2.Location = new System.Drawing.Point(220, 11);
            this.lblBetween2.Name = "lblBetween2";
            this.lblBetween2.Size = new Size(17, 12);
            this.lblBetween2.TabIndex = 10;
            this.lblBetween2.Text = "～";
            this.dtpStartDate2.CustomFormat = "yyyy-MM-dd";
            this.dtpStartDate2.Format = DateTimePickerFormat.Custom;
            this.dtpStartDate2.Location = new System.Drawing.Point(9, 7);
            this.dtpStartDate2.Name = "dtpStartDate2";
            this.dtpStartDate2.Size = new Size(88, 21);
            this.dtpStartDate2.TabIndex = 4;
            this.dtpStartDate2.Tag = "～";
            this.dtpEndDate2.AccessibleRole =  System.Windows.Forms.AccessibleRole.None;
            this.dtpEndDate2.CustomFormat = "yyyy-MM-dd";
            this.dtpEndDate2.Format = DateTimePickerFormat.Custom;
            this.dtpEndDate2.Location = new System.Drawing.Point(102, 7);
            this.dtpEndDate2.Name = "dtpEndDate2";
            this.dtpEndDate2.Size = new Size(84, 21);
            this.dtpEndDate2.TabIndex = 6;
            this.dtpEndDate2.Tag = "；";
            this.dtpStartTime2.CustomFormat = "HH:mm:ss";
            this.dtpStartTime2.Format = DateTimePickerFormat.Custom;
            this.dtpStartTime2.Location = new System.Drawing.Point(8, 34);
            this.dtpStartTime2.Name = "dtpStartTime2";
            this.dtpStartTime2.ShowUpDown = true;
            this.dtpStartTime2.Size = new Size(73, 21);
            this.dtpStartTime2.TabIndex = 5;
            this.dtpStartTime2.TabStop = false;
            this.dtpStartTime2.Tag = "999";
            this.dtpStartTime2.Value = new DateTime(2010, 8, 5, 0, 0, 0, 0);
            this.dtpEndTime2.CustomFormat = "HH:mm:ss";
            this.dtpEndTime2.Format = DateTimePickerFormat.Custom;
            this.dtpEndTime2.Location = new System.Drawing.Point(87, 34);
            this.dtpEndTime2.Name = "dtpEndTime2";
            this.dtpEndTime2.ShowUpDown = true;
            this.dtpEndTime2.Size = new Size(71, 21);
            this.dtpEndTime2.TabIndex = 7;
            this.dtpEndTime2.Tag = "999";
            this.lvLedLight.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lvLedLight.FullRowSelect = true;
            this.lvLedLight.HeaderStyle = ColumnHeaderStyle.None;
            this.lvLedLight.HideSelection = false;
            this.lvLedLight.Location = new System.Drawing.Point(6, 62);
            this.lvLedLight.MultiSelect = false;
            this.lvLedLight.Name = "lvLedLight";
            this.lvLedLight.Size = new Size(200, 60);
            this.lvLedLight.TabIndex = 9;
            this.lvLedLight.Tag = "；";
            this.lvLedLight.UseCompatibleStateImageBehavior = false;
            this.lvLedLight.View = View.SmallIcon;
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(53, 332);
            this.label2.Name = "label2";
            this.label2.Size = new Size(275, 12);
            this.label2.TabIndex = 49;
            this.label2.Tag = "9999";
            this.label2.Text = "（注：停留时间参数为0时，表示不采用停留方式）";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(373, 565);
            base.Controls.Add(this.grpMsgParam);
            base.Name = "m2mLedDelMsg";
            this.Text = "位置查询";
            base.Load += new EventHandler(this.m2mLedDelMsg_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(this.grpMsgParam, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpMsgParam.ResumeLayout(false);
            this.grpMsgParam.PerformLayout();
            this.pnlLedMsg.ResumeLayout(false);
            this.pnlLedMsg.PerformLayout();
            this.numLedMsgIndex.EndInit();
            this.pnlLedMsgParam.ResumeLayout(false);
            this.pnlLedMsgParam.PerformLayout();
            this.grpShowModel.ResumeLayout(false);
            this.grpShowModel.PerformLayout();
            this.grpScreenModel.ResumeLayout(false);
            this.grpScreenModel.PerformLayout();
            this.numShowTimes.EndInit();
            this.numInterval.EndInit();
            this.numLighteness.EndInit();
            this.numStopTime.EndInit();
            this.pnlShowTime.ResumeLayout(false);
            this.pnlShowTime.PerformLayout();
            this.pnlShowTimeSecond.ResumeLayout(false);
            this.pnlShowTimeSecond.PerformLayout();
            this.tsAddDel.ResumeLayout(false);
            this.tsAddDel.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private CheckBox chkInterval;
        private CheckBox chkLighteness;
        private CheckBox chkShowFont;
        private CheckBox chkShowModel;
        private CheckBox chkShowSpeed;
        private CheckBox chkShowTime;
        private CheckBox chkShowTimes;
        private CheckBox chkShowTimeSecond;
        private CheckBox chkStopTime;
        private ComBox cmbShowFont;
        private ComBox cmbShowSpeed;
        private DataTable dt;
        private DateTimePicker dtpEndDate;
        private DateTimePicker dtpEndDate2;
        private DateTimePicker dtpEndTime;
        private DateTimePicker dtpEndTime2;
        private DateTimePicker dtpStartDate;
        private DateTimePicker dtpStartDate2;
        private DateTimePicker dtpStartTime;
        private DateTimePicker dtpStartTime2;
        private GroupBox grpMsgParam;
        private GroupBox grpScreenModel;
        private GroupBox grpShowModel;
        private Label label1;
        private Label label2;
        private Label lblBetween;
        private Label lblBetween2;
        private Label lblDelIndex;
        private Label lblIntervalUnit;
        private Label lblLedMsgIndex;
        private ListView lvLedLight;
        private NumericUpDown numInterval;
        private NumericUpDown numLedMsgIndex;
        private NumericUpDown numLighteness;
        private NumericUpDown numShowTimes;
        private NumericUpDown numStopTime;
        private Panel pnlLedMsg;
        private Panel pnlLedMsgParam;
        private Panel pnlShowTime;
        private Panel pnlShowTimeSecond;
        private RadioButton rdoAll;
        private RadioButton rdoDrive;
        private RadioButton rdoLeft;
        private RadioButton rdoStop;
        private RadioButton rdoUpDown;
        private ToolStrip tsAddDel;
        private ToolStripButton tsbAdd;
        private ToolStripButton tsbDel;
    }
}