namespace Client.M2M
{
    using Client;
    using PublicClass;
    using Remoting;
    using System;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;
    using WinFormsUI.Controls;

    partial class m2mPreSetRegion
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(m2mPreSetRegion));
            this.wbMap = new GisMap();
            this.pnlSetRegion = new Panel();
            this.pnlBtn = new Panel();
            this.pnlHandle = new Panel();
            this.btnRefresh = new Button();
            this.btnZoonOut = new Button();
            this.btnZoomIn = new Button();
            this.btnMove = new Button();
            this.btnPreviewDel = new Button();
            this.btnCircle = new Button();
            this.btnRectangle = new Button();
            this.btnSetRegion = new Button();
            this.btnSet = new Button();
            this.btnDisplay = new Button();
            this.btnTool = new Button();
            this.pnlRegion = new Panel();
            this.btnDelRegion = new Button();
            this.cmbRegion = new ComboBox();
            this.lblRegion = new Label();
            this.picLoadMap = new PictureBox();
            this.btnModifyRegion = new Button();
            this.pnlSetRegion.SuspendLayout();
            this.pnlBtn.SuspendLayout();
            this.pnlHandle.SuspendLayout();
            this.pnlRegion.SuspendLayout();
            ((ISupportInitialize) this.picLoadMap).BeginInit();
            base.SuspendLayout();
            this.wbMap.Dock = DockStyle.Fill;
            this.wbMap.IsWebBrowserContextMenuEnabled = false;
            this.wbMap.Location = new Point(156, 5);
            this.wbMap.MinimumSize = new Size(20, 20);
            this.wbMap.Name = "wbMap";
            this.wbMap.Size = new Size(533, 469);
            this.wbMap.TabIndex = 1;
            this.wbMap.WebBrowserShortcutsEnabled = false;
            this.wbMap.MapMouseUp += new HtmlElementEventHandler(this.wbMap_MouseUp);
            this.wbMap.DocumentCompleted += new WebBrowserDocumentCompletedEventHandler(this.wbMap_DocumentCompleted);
            this.wbMap.MapDoubleClick += new HtmlElementEventHandler(this.wbMap_DoubleClick);
            this.pnlSetRegion.Controls.Add(this.pnlBtn);
            this.pnlSetRegion.Controls.Add(this.pnlRegion);
            this.pnlSetRegion.Dock = DockStyle.Left;
            this.pnlSetRegion.Location = new Point(5, 5);
            this.pnlSetRegion.Name = "pnlSetRegion";
            this.pnlSetRegion.Size = new Size(151, 469);
            this.pnlSetRegion.TabIndex = 0;
            this.pnlBtn.Controls.Add(this.pnlHandle);
            this.pnlBtn.Controls.Add(this.btnSet);
            this.pnlBtn.Controls.Add(this.btnDisplay);
            this.pnlBtn.Controls.Add(this.btnTool);
            this.pnlBtn.Dock = DockStyle.Fill;
            this.pnlBtn.Location = new Point(0, 0);
            this.pnlBtn.Name = "pnlBtn";
            this.pnlBtn.Size = new Size(151, 384);
            this.pnlBtn.TabIndex = 0;
            this.pnlHandle.Controls.Add(this.btnRefresh);
            this.pnlHandle.Controls.Add(this.btnZoonOut);
            this.pnlHandle.Controls.Add(this.btnZoomIn);
            this.pnlHandle.Controls.Add(this.btnMove);
            this.pnlHandle.Controls.Add(this.btnPreviewDel);
            this.pnlHandle.Controls.Add(this.btnCircle);
            this.pnlHandle.Controls.Add(this.btnRectangle);
            this.pnlHandle.Controls.Add(this.btnSetRegion);
            this.pnlHandle.Dock = DockStyle.Fill;
            this.pnlHandle.Location = new Point(0, 23);
            this.pnlHandle.Name = "pnlHandle";
            this.pnlHandle.Size = new Size(151, 315);
            this.pnlHandle.TabIndex = 4;
            this.btnRefresh.Dock = DockStyle.Top;
            this.btnRefresh.FlatStyle = FlatStyle.Popup;
            this.btnRefresh.Image = (Image) resources.GetObject("btnRefresh.Image");
            this.btnRefresh.ImageAlign = ContentAlignment.TopCenter;
            this.btnRefresh.Location = new Point(0, 364);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Padding = new Padding(5);
            this.btnRefresh.Size = new Size(151, 52);
            this.btnRefresh.TabIndex = 6;
            this.btnRefresh.Tag = "9999";
            this.btnRefresh.Text = "刷新";
            this.btnRefresh.TextAlign = ContentAlignment.BottomCenter;
            this.btnRefresh.UseVisualStyleBackColor = true;
            this.btnRefresh.Visible = false;
            this.btnRefresh.Click += new EventHandler(this.btnRefresh_Click);
            this.btnZoonOut.Dock = DockStyle.Top;
            this.btnZoonOut.FlatStyle = FlatStyle.Popup;
            this.btnZoonOut.Image = (Image)resources.GetObject("btnZoonOut.Image");
            this.btnZoonOut.ImageAlign = ContentAlignment.TopCenter;
            this.btnZoonOut.Location = new Point(0, 312);
            this.btnZoonOut.Name = "btnZoonOut";
            this.btnZoonOut.Padding = new Padding(5);
            this.btnZoonOut.Size = new Size(151, 52);
            this.btnZoonOut.TabIndex = 5;
            this.btnZoonOut.Tag = "9999";
            this.btnZoonOut.Text = "缩小";
            this.btnZoonOut.TextAlign = ContentAlignment.BottomCenter;
            this.btnZoonOut.UseVisualStyleBackColor = true;
            this.btnZoonOut.Visible = false;
            this.btnZoonOut.Click += new EventHandler(this.btnZoonOut_Click);
            this.btnZoomIn.Dock = DockStyle.Top;
            this.btnZoomIn.FlatStyle = FlatStyle.Popup;
            this.btnZoomIn.Image = (Image)resources.GetObject("btnZoomIn.Image");
            this.btnZoomIn.ImageAlign = ContentAlignment.TopCenter;
            this.btnZoomIn.Location = new Point(0, 260);
            this.btnZoomIn.Name = "btnZoomIn";
            this.btnZoomIn.Padding = new Padding(5);
            this.btnZoomIn.Size = new Size(151, 52);
            this.btnZoomIn.TabIndex = 4;
            this.btnZoomIn.Tag = "9999";
            this.btnZoomIn.Text = "放大";
            this.btnZoomIn.TextAlign = ContentAlignment.BottomCenter;
            this.btnZoomIn.UseVisualStyleBackColor = true;
            this.btnZoomIn.Visible = false;
            this.btnZoomIn.Click += new EventHandler(this.btnZoomIn_Click);
            this.btnMove.Dock = DockStyle.Top;
            this.btnMove.FlatStyle = FlatStyle.Popup;
            this.btnMove.Image = (Image)resources.GetObject("btnMove.Image");
            this.btnMove.ImageAlign = ContentAlignment.TopCenter;
            this.btnMove.Location = new Point(0, 208);
            this.btnMove.Name = "btnMove";
            this.btnMove.Padding = new Padding(5);
            this.btnMove.Size = new Size(151, 52);
            this.btnMove.TabIndex = 3;
            this.btnMove.Tag = "9999";
            this.btnMove.Text = "移动";
            this.btnMove.TextAlign = ContentAlignment.BottomCenter;
            this.btnMove.UseVisualStyleBackColor = true;
            this.btnMove.Visible = false;
            this.btnMove.Click += new EventHandler(this.btnMove_Click);
            this.btnPreviewDel.Dock = DockStyle.Top;
            this.btnPreviewDel.FlatStyle = FlatStyle.Popup;
            this.btnPreviewDel.Location = new Point(0, 156);
            this.btnPreviewDel.Name = "btnPreviewDel";
            this.btnPreviewDel.Size = new Size(151, 52);
            this.btnPreviewDel.TabIndex = 2;
            this.btnPreviewDel.Tag = "9999";
            this.btnPreviewDel.Text = "预览/删除区域";
            this.btnPreviewDel.UseVisualStyleBackColor = true;
            this.btnPreviewDel.Visible = false;
            this.btnPreviewDel.Click += new EventHandler(this.btnPreviewDel_Click);
            this.btnCircle.Dock = DockStyle.Top;
            this.btnCircle.FlatStyle = FlatStyle.Popup;
            this.btnCircle.Location = new Point(0, 104);
            this.btnCircle.Name = "btnCircle";
            this.btnCircle.Size = new Size(151, 52);
            this.btnCircle.TabIndex = 7;
            this.btnCircle.Tag = "9999";
            this.btnCircle.Text = "设置圆形区域";
            this.btnCircle.UseVisualStyleBackColor = true;
            this.btnCircle.Click += new EventHandler(this.btnCircle_Click);
            this.btnRectangle.Dock = DockStyle.Top;
            this.btnRectangle.FlatStyle = FlatStyle.Popup;
            this.btnRectangle.Location = new Point(0, 52);
            this.btnRectangle.Name = "btnRectangle";
            this.btnRectangle.Size = new Size(151, 52);
            this.btnRectangle.TabIndex = 1;
            this.btnRectangle.Tag = "9999";
            this.btnRectangle.Text = "设置矩形区域";
            this.btnRectangle.UseVisualStyleBackColor = true;
            this.btnRectangle.Click += new EventHandler(this.btnRectangle_Click);
            this.btnSetRegion.Dock = DockStyle.Top;
            this.btnSetRegion.FlatStyle = FlatStyle.Popup;
            this.btnSetRegion.Location = new Point(0, 0);
            this.btnSetRegion.Name = "btnSetRegion";
            this.btnSetRegion.Size = new Size(151, 52);
            this.btnSetRegion.TabIndex = 0;
            this.btnSetRegion.Tag = "9999";
            this.btnSetRegion.Text = "设置多边形区域";
            this.btnSetRegion.UseVisualStyleBackColor = true;
            this.btnSetRegion.Click += new EventHandler(this.btnSetRegion_Click);
            this.btnSet.Dock = DockStyle.Top;
            this.btnSet.Location = new Point(0, 0);
            this.btnSet.Name = "btnSet";
            this.btnSet.Size = new Size(151, 23);
            this.btnSet.TabIndex = 0;
            this.btnSet.Text = "设置";
            this.btnSet.UseVisualStyleBackColor = true;
            this.btnSet.Click += new EventHandler(this.btnSet_Click);
            this.btnDisplay.Dock = DockStyle.Bottom;
            this.btnDisplay.Location = new Point(0, 338);
            this.btnDisplay.Name = "btnDisplay";
            this.btnDisplay.Size = new Size(151, 23);
            this.btnDisplay.TabIndex = 1;
            this.btnDisplay.Text = "显示";
            this.btnDisplay.UseVisualStyleBackColor = true;
            this.btnDisplay.Click += new EventHandler(this.btnDisplay_Click);
            this.btnTool.Dock = DockStyle.Bottom;
            this.btnTool.Location = new Point(0, 361);
            this.btnTool.Name = "btnTool";
            this.btnTool.Size = new Size(151, 23);
            this.btnTool.TabIndex = 2;
            this.btnTool.Text = "地图工具";
            this.btnTool.UseVisualStyleBackColor = true;
            this.btnTool.Click += new EventHandler(this.btnTool_Click);
            this.pnlRegion.Controls.Add(this.btnModifyRegion);
            this.pnlRegion.Controls.Add(this.btnDelRegion);
            this.pnlRegion.Controls.Add(this.cmbRegion);
            this.pnlRegion.Controls.Add(this.lblRegion);
            this.pnlRegion.Dock = DockStyle.Bottom;
            this.pnlRegion.Location = new Point(0, 384);
            this.pnlRegion.Name = "pnlRegion";
            this.pnlRegion.Size = new Size(151, 85);
            this.pnlRegion.TabIndex = 1;
            this.pnlRegion.Visible = false;
            this.btnDelRegion.Location = new Point(70, 56);
            this.btnDelRegion.Name = "btnDelRegion";
            this.btnDelRegion.Size = new Size(75, 23);
            this.btnDelRegion.TabIndex = 1;
            this.btnDelRegion.Text = "删除区域";
            this.btnDelRegion.UseVisualStyleBackColor = true;
            this.btnDelRegion.Click += new EventHandler(this.btnDelRegion_Click);
            this.cmbRegion.DisplayMember = "regionName";
            this.cmbRegion.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmbRegion.FlatStyle = FlatStyle.Flat;
            this.cmbRegion.FormattingEnabled = true;
            this.cmbRegion.Location = new Point(5, 28);
            this.cmbRegion.Name = "cmbRegion";
            this.cmbRegion.Size = new Size(142, 20);
            this.cmbRegion.TabIndex = 0;
            this.cmbRegion.ValueMember = "regionDot";
            this.cmbRegion.SelectedIndexChanged += new EventHandler(this.cmbRegion_SelectedIndexChanged);
            this.lblRegion.AutoSize = true;
            this.lblRegion.Location = new Point(3, 10);
            this.lblRegion.Name = "lblRegion";
            this.lblRegion.Size = new Size(65, 12);
            this.lblRegion.TabIndex = 0;
            this.lblRegion.Text = "区域名称：";
            this.picLoadMap.BackgroundImage = (Image)resources.GetObject("picLoadMap.BackgroundImage");
            this.picLoadMap.Location = new Point(323, 203);
            this.picLoadMap.Name = "picLoadMap";
            this.picLoadMap.Size = new Size(167, 33);
            this.picLoadMap.TabIndex = 6;
            this.picLoadMap.TabStop = false;
            this.picLoadMap.Visible = false;
            this.btnModifyRegion.Location = new Point(0, 56);
            this.btnModifyRegion.Name = "btnModifyRegion";
            this.btnModifyRegion.Size = new Size(68, 23);
            this.btnModifyRegion.TabIndex = 3;
            this.btnModifyRegion.Text = "修改区域";
            this.btnModifyRegion.UseVisualStyleBackColor = true;
            this.btnModifyRegion.Click += new EventHandler(this.btnModifyRegion_Click);
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            base.ClientSize = new Size(694, 479);
            base.Controls.Add(this.picLoadMap);
            base.Controls.Add(this.wbMap);
            base.Controls.Add(this.pnlSetRegion);
            base.Icon = (Icon)resources.GetObject("$this.Icon");
            base.Name = "m2mPreSetRegion";
            base.Padding = new Padding(5);
            this.Text = "预设报警区域";
            base.Load += new EventHandler(this.itmPreSetRegion_Load);
            base.FormClosing += new FormClosingEventHandler(this.itmPreSetRegion_FormClosing);
            this.pnlSetRegion.ResumeLayout(false);
            this.pnlBtn.ResumeLayout(false);
            this.pnlHandle.ResumeLayout(false);
            this.pnlRegion.ResumeLayout(false);
            this.pnlRegion.PerformLayout();
            ((ISupportInitialize) this.picLoadMap).EndInit();
            base.ResumeLayout(false);
        }

       
        private IContainer components;
        private Button btnCircle;
        private Button btnDelRegion;
        private Button btnDisplay;
        private Button btnModifyRegion;
        private Button btnMove;
        private Button btnPreviewDel;
        private Button btnRectangle;
        private Button btnRefresh;
        private Button btnSet;
        private Button btnSetRegion;
        private Button btnTool;
        private Button btnZoomIn;
        private Button btnZoonOut;
        private ComboBox cmbRegion;
        private int currentRegionType;
        private bool isModify;
        private Label lblRegion;
        private PictureBox picLoadMap;
        private Panel pnlBtn;
        private Panel pnlHandle;
        private Panel pnlRegion;
        private Panel pnlSetRegion;
        private itmPreSetPath.PreType preType;
        private GisMap wbMap;
    }
}