namespace Client.M2M
{
    using Client;
    using PublicClass;
    using Remoting;
    using ParamLibrary.Application;
    using ParamLibrary.CmdParamInfo;
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Data;
    using System.Drawing;
    using System.Windows.Forms;

    partial class m2mSetRegionAlarm
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

       
        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.grpArea = new GroupBox();
            this.dgvArea = new DataGridView();
            this.regionName = new DataGridViewTextBoxColumn();
            this.InRegion = new DataGridViewCheckBoxColumn();
            this.OutRegion = new DataGridViewCheckBoxColumn();
            this.InOutRegion = new DataGridViewCheckBoxColumn();
            this.ColseGSm = new DataGridViewCheckBoxColumn();
            this.ColseData = new DataGridViewCheckBoxColumn();
            this.StartPoint = new DataGridViewCheckBoxColumn();
            this.PassPoint = new DataGridViewCheckBoxColumn();
            this.EndPoint = new DataGridViewCheckBoxColumn();
            this.distanceToBegin = new DataGridViewTextBoxColumn();
            this.distanceToEnd = new DataGridViewTextBoxColumn();
            this.planUpBeginTime = new DataGridViewTextBoxColumn();
            this.planDownBeginTime = new DataGridViewTextBoxColumn();
            this.StopPoint = new DataGridViewCheckBoxColumn();
            this.beginTime = new DataGridViewTextBoxColumn();
            this.endTime = new DataGridViewTextBoxColumn();
            this.AlarmCondition = new DataGridViewTextBoxColumn();
            this.regionId = new DataGridViewTextBoxColumn();
            this.regionDot = new DataGridViewTextBoxColumn();
            this.pnlCarRecord = new Panel();
            this.numStartIndex = new NumericUpDown();
            this.lblStartIndex = new Label();
            base.grpCar.SuspendLayout();
            base.pnlBtn.SuspendLayout();
            this.grpArea.SuspendLayout();
            ((ISupportInitialize) this.dgvArea).BeginInit();
            this.pnlCarRecord.SuspendLayout();
            this.numStartIndex.BeginInit();
            base.SuspendLayout();
            base.grpCar.TabIndex = 0;
            base.pnlBtn.Dock = DockStyle.Bottom;
            base.pnlBtn.Location = new System.Drawing.Point(5, 353);
            base.pnlBtn.TabIndex = 2;
            base.btnCancel.Location = new System.Drawing.Point(287, 3);
            base.btnCancel.TabIndex = 1;
            base.btnOK.Location = new System.Drawing.Point(206, 3);
            base.btnOK.TabIndex = 0;
            this.grpArea.Controls.Add(this.dgvArea);
            this.grpArea.Controls.Add(this.pnlCarRecord);
            this.grpArea.Dock = DockStyle.Fill;
            this.grpArea.Location = new System.Drawing.Point(5, 121);
            this.grpArea.Name = "grpArea";
            this.grpArea.Size = new Size(363, 232);
            this.grpArea.TabIndex = 1;
            this.grpArea.TabStop = false;
            this.grpArea.Text = "预设区域";
            this.dgvArea.AllowUserToAddRows = false;
            this.dgvArea.AllowUserToResizeRows = false;
            this.dgvArea.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.AllCells;
            this.dgvArea.BackgroundColor = SystemColors.ControlLightLight;
            this.dgvArea.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvArea.Columns.AddRange(new DataGridViewColumn[] { 
                this.regionName, this.InRegion, this.OutRegion, this.InOutRegion, this.ColseGSm, this.ColseData, this.StartPoint, this.PassPoint, this.EndPoint, this.distanceToBegin, this.distanceToEnd, this.planUpBeginTime, this.planDownBeginTime, this.StopPoint, this.beginTime, this.endTime, 
                this.AlarmCondition, this.regionId, this.regionDot
             });
            this.dgvArea.Dock = DockStyle.Top;
            this.dgvArea.Location = new System.Drawing.Point(3, 49);
            this.dgvArea.Name = "dgvArea";
            this.dgvArea.RowHeadersVisible = false;
            this.dgvArea.RowTemplate.Height = 20;
            this.dgvArea.SelectionMode = DataGridViewSelectionMode.CellSelect;
            this.dgvArea.Size = new Size(357, 177);
            this.dgvArea.TabIndex = 0;
            this.dgvArea.CellValueChanged += new DataGridViewCellEventHandler(this.dgvArea_CellValueChanged);
            this.dgvArea.CellMouseUp += new DataGridViewCellMouseEventHandler(this.dgvArea_CellMouseUp);
            this.regionName.DataPropertyName = "regionName";
            style.BackColor = Color.FromArgb(192, 192, 255);
            this.regionName.DefaultCellStyle = style;
            this.regionName.Frozen = true;
            this.regionName.HeaderText = "区域名称";
            this.regionName.MinimumWidth = 100;
            this.regionName.Name = "regionName";
            this.regionName.ReadOnly = true;
            this.regionName.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.InRegion.DataPropertyName = "InRegion";
            this.InRegion.FalseValue = "False";
            this.InRegion.HeaderText = "进入";
            this.InRegion.MinimumWidth = 45;
            this.InRegion.Name = "InRegion";
            this.InRegion.TrueValue = "True";
            this.InRegion.Width = 45;
            this.OutRegion.DataPropertyName = "OutRegion";
            this.OutRegion.FalseValue = "False";
            this.OutRegion.HeaderText = "越出";
            this.OutRegion.MinimumWidth = 45;
            this.OutRegion.Name = "OutRegion";
            this.OutRegion.TrueValue = "True";
            this.OutRegion.Width = 45;
            this.InOutRegion.DataPropertyName = "InOutRegion";
            this.InOutRegion.FalseValue = "False";
            this.InOutRegion.HeaderText = "进入/越出";
            this.InOutRegion.MinimumWidth = 75;
            this.InOutRegion.Name = "InOutRegion";
            this.InOutRegion.TrueValue = "True";
            this.InOutRegion.Width = 75;
            this.ColseGSm.DataPropertyName = "ColseGSm";
            this.ColseGSm.FalseValue = "False";
            this.ColseGSm.HeaderText = "关闭GSM模块";
            this.ColseGSm.MinimumWidth = 90;
            this.ColseGSm.Name = "ColseGSm";
            this.ColseGSm.ReadOnly = true;
            this.ColseGSm.Resizable = DataGridViewTriState.False;
            this.ColseGSm.TrueValue = "True";
            this.ColseGSm.Visible = false;
            this.ColseGSm.Width = 90;
            this.ColseData.DataPropertyName = "ColseData";
            this.ColseData.FalseValue = "False";
            this.ColseData.HeaderText = "关闭数据拨号";
            this.ColseData.MinimumWidth = 90;
            this.ColseData.Name = "ColseData";
            this.ColseData.ReadOnly = true;
            this.ColseData.Resizable = DataGridViewTriState.False;
            this.ColseData.TrueValue = "True";
            this.ColseData.Visible = false;
            this.ColseData.Width = 90;
            this.StartPoint.DataPropertyName = "StartPoint";
            this.StartPoint.FalseValue = "False";
            this.StartPoint.HeaderText = "起点站";
            this.StartPoint.MinimumWidth = 60;
            this.StartPoint.Name = "StartPoint";
            this.StartPoint.TrueValue = "True";
            this.StartPoint.Visible = false;
            this.StartPoint.Width = 60;
            this.PassPoint.DataPropertyName = "PassPoint";
            this.PassPoint.FalseValue = "False";
            this.PassPoint.HeaderText = "经停站";
            this.PassPoint.MinimumWidth = 60;
            this.PassPoint.Name = "PassPoint";
            this.PassPoint.TrueValue = "True";
            this.PassPoint.Visible = false;
            this.PassPoint.Width = 60;
            this.EndPoint.DataPropertyName = "EndPoint";
            this.EndPoint.FalseValue = "False";
            this.EndPoint.HeaderText = "终点站";
            this.EndPoint.MinimumWidth = 60;
            this.EndPoint.Name = "EndPoint";
            this.EndPoint.TrueValue = "True";
            this.EndPoint.Visible = false;
            this.EndPoint.Width = 60;
            this.distanceToBegin.DataPropertyName = "distanceToBegin";
            this.distanceToBegin.HeaderText = "去程车程时长(小时)";
            this.distanceToBegin.MinimumWidth = 120;
            this.distanceToBegin.Name = "distanceToBegin";
            this.distanceToBegin.ReadOnly = true;
            this.distanceToBegin.Resizable = DataGridViewTriState.False;
            this.distanceToBegin.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.distanceToBegin.Visible = false;
            this.distanceToBegin.Width = 120;
            this.distanceToEnd.DataPropertyName = "distanceToEnd";
            this.distanceToEnd.HeaderText = "返程车程时长(小时)";
            this.distanceToEnd.MinimumWidth = 120;
            this.distanceToEnd.Name = "distanceToEnd";
            this.distanceToEnd.ReadOnly = true;
            this.distanceToEnd.Resizable = DataGridViewTriState.False;
            this.distanceToEnd.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.distanceToEnd.Visible = false;
            this.distanceToEnd.Width = 120;
            this.planUpBeginTime.DataPropertyName = "planUpBeginTime";
            this.planUpBeginTime.HeaderText = "去程规定始发时间";
            this.planUpBeginTime.MinimumWidth = 120;
            this.planUpBeginTime.Name = "planUpBeginTime";
            this.planUpBeginTime.ReadOnly = true;
            this.planUpBeginTime.Resizable = DataGridViewTriState.False;
            this.planUpBeginTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.planUpBeginTime.Visible = false;
            this.planUpBeginTime.Width = 120;
            this.planDownBeginTime.DataPropertyName = "planDownBeginTime";
            this.planDownBeginTime.HeaderText = "返程规定始发时间";
            this.planDownBeginTime.MinimumWidth = 120;
            this.planDownBeginTime.Name = "planDownBeginTime";
            this.planDownBeginTime.ReadOnly = true;
            this.planDownBeginTime.Resizable = DataGridViewTriState.False;
            this.planDownBeginTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.planDownBeginTime.Visible = false;
            this.planDownBeginTime.Width = 120;
            this.StopPoint.DataPropertyName = "StopPoint";
            this.StopPoint.FalseValue = "False";
            this.StopPoint.HeaderText = "停车点";
            this.StopPoint.MinimumWidth = 60;
            this.StopPoint.Name = "StopPoint";
            this.StopPoint.Resizable = DataGridViewTriState.False;
            this.StopPoint.TrueValue = "True";
            this.StopPoint.Visible = false;
            this.StopPoint.Width = 60;
            this.beginTime.DataPropertyName = "beginTime";
            this.beginTime.HeaderText = "起始时间";
            this.beginTime.MaxInputLength = 19;
            this.beginTime.MinimumWidth = 60;
            this.beginTime.Name = "beginTime";
            this.beginTime.ReadOnly = true;
            this.beginTime.Resizable = DataGridViewTriState.False;
            this.beginTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.beginTime.Visible = false;
            this.beginTime.Width = 60;
            this.endTime.DataPropertyName = "endTime";
            this.endTime.HeaderText = "终止时间";
            this.endTime.MaxInputLength = 19;
            this.endTime.MinimumWidth = 60;
            this.endTime.Name = "endTime";
            this.endTime.ReadOnly = true;
            this.endTime.Resizable = DataGridViewTriState.False;
            this.endTime.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.endTime.Visible = false;
            this.endTime.Width = 60;
            this.AlarmCondition.DataPropertyName = "AlarmCondition";
            this.AlarmCondition.HeaderText = "允许报警条件";
            this.AlarmCondition.MinimumWidth = 100;
            this.AlarmCondition.Name = "AlarmCondition";
            this.AlarmCondition.ReadOnly = true;
            this.AlarmCondition.Resizable = DataGridViewTriState.False;
            this.AlarmCondition.SortMode = DataGridViewColumnSortMode.NotSortable;
            this.AlarmCondition.Visible = false;
            this.regionId.DataPropertyName = "regionId";
            this.regionId.HeaderText = "区域ID";
            this.regionId.Name = "regionId";
            this.regionId.Visible = false;
            this.regionId.Width = 66;
            this.regionDot.DataPropertyName = "regionDot";
            this.regionDot.HeaderText = "区域点坐标集";
            this.regionDot.Name = "regionDot";
            this.regionDot.Visible = false;
            this.regionDot.Width = 102;
            this.pnlCarRecord.Controls.Add(this.lblStartIndex);
            this.pnlCarRecord.Controls.Add(this.numStartIndex);
            this.pnlCarRecord.Dock = DockStyle.Top;
            this.pnlCarRecord.Location = new System.Drawing.Point(3, 17);
            this.pnlCarRecord.Name = "pnlCarRecord";
            this.pnlCarRecord.Size = new Size(357, 32);
            this.pnlCarRecord.TabIndex = 2;
            this.numStartIndex.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.numStartIndex.Location = new System.Drawing.Point(119, 5);
            this.numStartIndex.Name = "numStartIndex";
            this.numStartIndex.Size = new Size(120, 21);
            this.numStartIndex.TabIndex = 1;
            this.lblStartIndex.AutoSize = true;
            this.lblStartIndex.Location = new System.Drawing.Point(47, 9);
            this.lblStartIndex.Name = "lblStartIndex";
            this.lblStartIndex.Size = new Size(65, 12);
            this.lblStartIndex.TabIndex = 0;
            this.lblStartIndex.Text = "起始标号：";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode =  System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            base.ClientSize = new Size(373, 386);
            base.Controls.Add(this.grpArea);
            base.FormBorderStyle =  System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.Name = "m2mSetRegionAlarm";
            this.Text = "SetAreaAlarm";
            base.Load += new EventHandler(this.SetAreaAlarm_Load);
            base.Controls.SetChildIndex(base.grpCar, 0);
            base.Controls.SetChildIndex(base.pnlBtn, 0);
            base.Controls.SetChildIndex(this.grpArea, 0);
            base.grpCar.ResumeLayout(false);
            base.grpCar.PerformLayout();
            base.pnlBtn.ResumeLayout(false);
            this.grpArea.ResumeLayout(false);
            ((ISupportInitialize) this.dgvArea).EndInit();
            this.pnlCarRecord.ResumeLayout(false);
            this.pnlCarRecord.PerformLayout();
            this.numStartIndex.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

       
        private IContainer components;
        private DataGridViewTextBoxColumn AlarmCondition;
        private DataGridViewTextBoxColumn beginTime;
        private bool bSameChange;
        private DataGridViewCheckBoxColumn ColseData;
        private DataGridViewCheckBoxColumn ColseGSm;
        private DataGridView dgvArea;
        private DataGridViewTextBoxColumn distanceToBegin;
        private DataGridViewTextBoxColumn distanceToEnd;
        private DataGridViewCheckBoxColumn EndPoint;
        private DataGridViewTextBoxColumn endTime;
        private GroupBox grpArea;
        private DataGridViewCheckBoxColumn InOutRegion;
        private DataGridViewCheckBoxColumn InRegion;
        private Label lblStartIndex;
        private NumericUpDown numStartIndex;
        private DataGridViewCheckBoxColumn OutRegion;
        private DataGridViewCheckBoxColumn PassPoint;
        private DataGridViewTextBoxColumn planDownBeginTime;
        private DataGridViewTextBoxColumn planUpBeginTime;
        private Panel pnlCarRecord;
        private DataGridViewTextBoxColumn regionDot;
        private DataGridViewTextBoxColumn regionId;
        private DataGridViewTextBoxColumn regionName;
        private DataGridViewCheckBoxColumn StartPoint;
        private DataGridViewCheckBoxColumn StopPoint;
    }
}